import fs from 'node:fs';
import { ipcMain } from 'electron';
import { IPC } from '../../../shared/ipc-channels';
import { SessionRepository } from '../../db/repositories/session-repository';
import { UsageHistoryRepository } from '../../db/repositories/usage-history-repository';
import { captureGitChurn, resolveDefaultBaseBranch } from './git-stats-capture';
import { WorktreeManager, type GitWaitProgress } from '../../git/worktree-manager';
import { candidateWorktreePathsFor, legacyAutoBranchNameFor } from '../../git/task-worktree-folder';
import { isAutoGeneratedBranch } from '../../git/git-checks';
import { getProjectDb } from '../../db/database';
import {
  getProjectRepos,
  ensureTaskWorktree,
  ensureTaskBranchCheckout,
  createTransitionEngine,
  captureSessionLeftovers,
  cleanupTaskResources,
  deleteTaskWorktree,
  reapSessionLeftovers,
  spawnAgent,
} from '../helpers';
import { autoLinkPRForTask } from '../../pr/pr-linking';
import { sendToRenderer } from '../send-to-renderer';
import { resolveProjectContext } from '../helpers/project-repos';
import { interpolateTaskTemplate, resolveTaskTemplateVars } from '../../agent/shared';
import { trackEvent } from '../../analytics/analytics';
import { trackMilestone } from '../../analytics/usage';
import { getDevPortForTask } from '../../dev-ports/dev-port-allocator';
import { parseModelId } from '../../../shared/model-id';
import { captureSessionMetrics, refineTranscriptTokens, refineTranscriptToolCounts } from './session-metrics';
import { markRecordExited, markRecordSuspended } from '../../transition-engine/session-lifecycle';
import type { IpcContext } from '../ipc-context';
import { isAbortError } from '../../../shared/abort-utils';
import { abortBacklogPromotion } from './backlog';
import { withTaskLock } from '../task-lifecycle-lock';
import { isShuttingDown } from '../../shutdown-state';
import { runWithProjectLogContext } from '../../diagnostics/project-log-context';
import { emitSpawnProgress, emitSpawnWaiting, clearSpawnProgress, createProgressCallback, getInFlightSpawnProgress, type SpawnPhase } from '../../transition-engine/spawn-progress';
import { resolveTargetAgent } from '../../transition-engine/agent-resolver';
import { agentRegistry } from '../../agent/agent-registry';
import { prepareInjectionPlan, resolveLiveEffort, resolveSourceEffort } from '../../transition-engine/injection-plan';
import { resolveIsolatedSwimlaneId, resolveForceFresh } from '../../transition-engine/session-isolation';
import { resolveEffectiveAutoCommand, applyProfileToLane } from '../../transition-engine/column-strategy';
import { loadTaskProfile } from '../helpers/task-profile';
import { reportAutoCommandOutcome } from '../helpers/auto-command-outcome';
import { restartSessionForSettingsChange } from './session-reconcile';
import type { Task, Swimlane, SessionRecord, TaskUpdateInput } from '../../../shared/types';
import type { AtomicRouteInput } from '../../db/repositories/task-repository';

/**
 * Per-task AbortController to cancel in-flight moves when a newer move
 * supersedes the current one. Prevents orphaned sessions from spawning
 * when the user quickly moves a task back before the async spawn completes.
 * The signal propagates through the async call chain; each helper throws
 * AbortError when cancelled, and cleanup is centralized in a single catch.
 */
const taskMoveControllers = new Map<string, AbortController>();
const routeDispatchCompletions = new Map<string, Promise<void>>();

export function routeLifecycleNeedsRecovery(task: Pick<Task, 'pending_dispatch_id'> | null | undefined, dispatchId: string): boolean {
  return Boolean(task && task.pending_dispatch_id === dispatchId);
}

export async function retireOrphanTaskSessions(
  sessionManager: IpcContext['sessionManager'],
  taskId: string,
): Promise<void> {
  const orphanIds = sessionManager.listSessions()
    .filter((session) => session.taskId === taskId)
    .map((session) => session.id);
  sessionManager.killByTaskId(taskId);
  await Promise.all(orphanIds.map((sessionId) => sessionManager.awaitExit(sessionId)));
  sessionManager.removeByTaskId(taskId);
}

export function restorePendingRouteDestination(
  tasks: ReturnType<typeof getProjectRepos>['tasks'],
  swimlanes: ReturnType<typeof getProjectRepos>['swimlanes'],
  task: Task,
  input: { taskId: string; targetSwimlaneId: string; targetPosition: number },
): Task {
  if (task.swimlane_id === input.targetSwimlaneId) return task;
  const currentLane = swimlanes.getById(task.swimlane_id);
  if (currentLane?.role !== 'todo') throw new Error('Cannot recover router lifecycle from an unexpected column');
  tasks.move(input);
  const restored = tasks.getById(input.taskId);
  if (!restored) throw new Error('Task disappeared while restoring a pending route');
  return restored;
}

/**
 * Suspend a live PTY session so Phase 3 can respawn it with new CLI flags:
 * emit a spawn-progress label naming the handoff, capture metrics while
 * caches are populated, mark the DB record suspended (or exited for queued
 * records that never started), suspend the PTY, and clear task.session_id.
 * Shared by all four same-column respawn triggers: a model change, an
 * effort delta to a concrete target on an adapter with no live `/effort`
 * swap, a session-track switch (isolated column entry/exit or
 * `always_spawn_new`), and a cross-agent handoff.
 *
 * `phase` is required, not optional: every caller must name what the user
 * is about to see instead of the suspended session's stale "Paused" state,
 * so a future respawn branch cannot silently opt out of labeling its own
 * window (see the flash bug this fixes - the suspend used to leave the
 * card and task detail reading "Paused"/"Resume session" for the entire
 * unlocked Phase 2 gap). Emitted as the FIRST statement, before the record
 * is even marked suspended: while the session is still 'running',
 * getTaskProgress lets it own the display (task-progress.ts:166 applies a
 * label only when there is no session or the session is 'suspended'), so the
 * early emit is inert until the suspend actually lands and is never a source
 * of its own gap.
 */
async function suspendLiveSessionForRespawn(args: {
  context: IpcContext;
  tasks: ReturnType<typeof getProjectRepos>['tasks'];
  sessionRepo: SessionRepository;
  usageHistoryRepo: UsageHistoryRepository;
  taskId: string;
  liveSessionId: string;
  record: SessionRecord | undefined | null;
  task: Task;
  projectPath: string | null;
  defaultBaseBranch: string;
  phase: SpawnPhase;
  // `session_id` is excluded, not merely omitted by convention: it is spread
  // after `session_id: null` below, so a caller that passed one would silently
  // defeat the null-out this helper exists to guarantee.
  additionalTaskUpdates?: Partial<Omit<TaskUpdateInput, 'id' | 'session_id'>>;
}): Promise<void> {
  const { context, tasks, sessionRepo, usageHistoryRepo, taskId, liveSessionId, record, task, projectPath, defaultBaseBranch, phase, additionalTaskUpdates } = args;
  emitSpawnProgress(context.mainWindow, taskId, phase);
  // Everything after the emit runs in Phase 1, INSIDE the withTaskLock call.
  // That call sits under a try whose only clause is a `finally` (the
  // AbortController cleanup); the catch that retires labels belongs to a
  // separate, later try covering Phase 2/3 only. So a throw here - a rejecting
  // sessionManager.suspend, or a locked-DB markRecordSuspended / tasks.update -
  // would escape handleTaskMove entirely and strand the label just emitted
  // until the 120s TTL. Clear it and rethrow so the caller's behavior is
  // otherwise unchanged.
  //
  // This retires the LABEL only. A throw partway through still leaves the DB
  // half-written (record marked suspended without session_id cleared, or the
  // reverse); Phase 1 has no rollback and that is unchanged here.
  try {
    if (record && record.agent_session_id
        && (record.status === 'running' || record.status === 'exited')) {
      captureSessionMetrics(
        context.sessionManager,
        sessionRepo,
        usageHistoryRepo,
        liveSessionId,
        record.id,
        record.started_at,
        record.session_type,
      );
      refineTranscriptTokens(context.sessionManager, sessionRepo, liveSessionId, record.id);
      refineTranscriptToolCounts(context.sessionManager, sessionRepo, liveSessionId, record.id);
      captureGitChurn(task, sessionRepo, usageHistoryRepo, record.id, projectPath, defaultBaseBranch);
      markRecordSuspended(sessionRepo, record.id, 'system');
    } else if (record && record.status === 'queued') {
      markRecordExited(sessionRepo, record.id);
    }
    await context.sessionManager.suspend(liveSessionId);
    tasks.update({ id: taskId, session_id: null, ...additionalTaskUpdates });
  } catch (error) {
    clearSpawnProgress(context.mainWindow, taskId);
    throw error;
  }
}

/**
 * Abort the in-flight move/spawn for a task, if any. Returns true if a move
 * was actually aborted. The abort is deliberately OUTSIDE any task lock (per
 * the task-lifecycle-lock contract): the holder observes the signal and runs
 * the existing AbortError path, which clears spawn progress and rolls the move
 * back. Used by the TASK_CANCEL_SPAWN handler so the user can cancel a spawn
 * that is parked in the git queue or stuck fetching.
 */
export function abortTaskMove(taskId: string): boolean {
  const controller = taskMoveControllers.get(taskId);
  if (!controller) return false;
  controller.abort();
  return true;
}

/**
 * Core task-move logic shared by the TASK_MOVE IPC handler and the
 * plan-exit auto-move listener. Moves the task, runs transitions, and
 * manages session lifecycle based on the target column's role.
 */
/**
 * Plan returned from Phase 1 when the move needs a subsequent worktree +
 * spawn. Priorities 1 / 2 / 2.5 / 3b / 3c handle the entire move under the
 * Phase 1 lock and return null; only Priority 3a (handoff) and Priority 4
 * (no active session) carry through to Phase 2/3.
 */
type MoveSpawnPlan = {
  task: Task;
  fromSwimlaneId: string;
  /**
   * The SOURCE lane the task lived in before this move, captured at Phase 1.
   * Threaded to spawnAgent as `settingsSourceLane`: the first-spawn override
   * lock resolves still-inherited Advanced fields against the lane the user
   * configured the task in, never the destination column. Required (not
   * optional) so every plan-return site threads it through explicitly.
   */
  fromLane: Swimlane | undefined;
  originalPosition: number;
  toLane: Swimlane | undefined;
  skipPromptTemplate: boolean;
  resolvedProjectId: string;
  resolvedProjectPath: string | null;
  /**
   * Delivered as the resumed session's next message by spawnAgent's fallback
   * when the destination column has no auto_command. Set by the plan-exit
   * auto-move so a respawned session does not sit idle. Required (not optional)
   * so every return site that builds a plan must thread it through explicitly;
   * a new respawn sub-case that forgets it is a compile error, not a silent
   * dropped continuation.
   */
  continuationPrompt: string | undefined;
  /**
   * Recovery move out of Done: spawnAgent must resume the session WITHOUT
   * injecting the destination column's auto_command. Required (not optional) so
   * every plan-return site threads it through explicitly; a new respawn sub-case
   * that forgets it is a compile error, not a silently-injected command on a
   * restore. See spawnAgent's `suppressAutoCommand`.
   */
  suppressAutoCommand: boolean;
};

/**
 * Who asked for this move. Required (not optional, and never a field on the
 * `options` bag) so a new call site cannot forget it: adding a caller without
 * naming its origin is a compile error, not a board that silently goes stale.
 *
 * This exists because `handleTaskMove` used to announce nothing at all, leaving
 * each caller to fan out the notifications itself. Three of the four got it
 * wrong in different ways, and the mobile bridge did neither half - a task moved
 * from the phone left the desktop board rendering the card in its old column
 * indefinitely.
 */
export type TaskMoveOrigin = 'renderer' | 'agent' | 'mobile' | 'auto-move';

/**
 * The renderer push for each origin, or null for "say nothing".
 *
 * A `Record` rather than a switch so a new `TaskMoveOrigin` member is a compile
 * error here too. The asymmetry is deliberate:
 *
 * - `renderer` is silent because it initiated the move and already updated
 *   optimistically. Pushing would cost a redundant board reload, and on the
 *   agent channel the user would toast themselves.
 * - `mobile` gets its own QUIET channel rather than reusing
 *   TASK_UPDATED_BY_AGENT, whose listener toasts `Task updated by agent`. No
 *   agent touched a task the user dragged on their own phone.
 *
 * The board-changed bus emit is NOT part of this table: it is unconditional for
 * every origin. See the announce block at the end of `handleTaskMove` for why.
 */
const MOVE_PUSH_BY_ORIGIN: Record<
  TaskMoveOrigin,
  ((context: IpcContext, projectId: string, input: { taskId: string; targetSwimlaneId: string }, title: string) => void) | null
> = {
  renderer: null,
  agent: (context, projectId, input, title) =>
    sendToRenderer(context.mainWindow, IPC.TASK_UPDATED_BY_AGENT, input.taskId, title, projectId),
  mobile: (context, projectId) =>
    sendToRenderer(context.mainWindow, IPC.TASK_MOVED_BY_MOBILE, projectId),
  'auto-move': (context, projectId, input, title) =>
    sendToRenderer(context.mainWindow, IPC.TASK_AUTO_MOVED, input.taskId, input.targetSwimlaneId, title, projectId),
};

/** Persist the human GO represented by Draft -> Approved. */
export function labelsAfterHumanDraftApproval(
  labels: string[],
  fromLaneName: string | null | undefined,
  toLaneName: string | null | undefined,
  origin: TaskMoveOrigin,
): string[] {
  if (!['renderer', 'mobile'].includes(origin)
      || fromLaneName !== 'Draft'
      || toLaneName !== 'Approved'
      || labels.some((label) => label.trim().toLowerCase() === 'approved')) {
    return labels;
  }
  return [...labels, 'approved'];
}

export async function handleTaskMove(
  context: IpcContext,
  input: {
    taskId: string;
    targetSwimlaneId: string;
    targetPosition: number;
    expectedSwimlaneId?: string;
    expectedRevision?: number;
  },
  origin: TaskMoveOrigin,
  projectId?: string | null,
  projectPath?: string | null,
  // Kept out of `input` (which flows raw from the renderer over IPC) so the
  // renderer cannot inject prompts; only main-process callers (the plan-exit
  // listener) can pass a continuation.
  //
  // `onCommitted` fires the moment the board row is on disk (see the commit
  // point inside Phase 1), which is long before the returned promise settles:
  // a Done move suspends, reaps and deletes the worktree after that point, and
  // an auto-spawn move creates a worktree and spawns. A caller that has to
  // answer someone on a deadline (the mobile bridge verb, against the phone's
  // 10s per-verb budget) answers on this signal and lets the tail finish behind
  // the response. Every other caller keeps awaiting the whole move.
  options?: { continuationPrompt?: string; onCommitted?: () => void; route?: AtomicRouteInput },
): Promise<void> {
  // MCP clients may retry after a network timeout while the original route is
  // still creating a worktree. A normal newer move intentionally aborts the
  // previous one; the SAME dispatch must instead join it, or the retry would
  // cancel the one operation it is trying to confirm.
  const routeDispatchId = options?.route?.dispatchId;
  if (routeDispatchId) {
    const active = routeDispatchCompletions.get(routeDispatchId);
    if (active) return active;
  }
  const routeSettlement: {
    resolve?: () => void;
    reject?: (error: unknown) => void;
  } = {};
  if (routeDispatchId) {
    const completion = new Promise<void>((resolve, reject) => {
      routeSettlement.resolve = resolve;
      routeSettlement.reject = reject;
    });
    // The originating caller receives the real throw below. This catch only
    // prevents an unhandled-rejection warning when nobody happened to retry.
    void completion.catch(() => undefined);
    routeDispatchCompletions.set(routeDispatchId, completion);
  }
  try {
  // Abort any in-flight move or promotion BEFORE queueing on the lock - the
  // existing holder must see its abort and return so we can acquire the lock.
  taskMoveControllers.get(input.taskId)?.abort();
  abortBacklogPromotion(input.taskId);
  const moveController = new AbortController();
  taskMoveControllers.set(input.taskId, moveController);
  const { signal } = moveController;

  // Tag every project-scoped log emitted across Phases 1-3 (worktree + spawn)
  // with the project this move targets, so concurrent moves on different
  // projects stay distinguishable in the dev terminal. Resolve the name from
  // the same id Phase 1 resolves; an unresolvable id (no project open) skips
  // the tag so the body inherits no misleading ambient context.
  const announceProjectId = projectId ?? context.currentProjectId;
  const logProjectName = announceProjectId
    ? context.projectRepo.getById(announceProjectId)?.name ?? null
    : null;

  // The board-changed bus emit, shared by the two announce points: once at the
  // commit point inside Phase 1, and once from the `finally` after the whole
  // move has settled. The rationale for announcing at all (and for erring
  // toward a duplicate) is on the settle-time block below; the rationale for
  // the commit-time one is at the commit point.
  //
  // The shutdown gate is load-bearing rather than defensive: on that path the
  // DB is already closed and the window is going away, but the bus would still
  // wake a phone subscription mid-teardown. Wrapped because BoardEventBus is a
  // plain EventEmitter that dispatches synchronously on this stack, so a
  // subscriber that threw would either replace the error runMove is already
  // propagating, or turn a committed move into a rejection with the rest of
  // Phase 1 (the Done cleanup) skipped. Announcing is best-effort by design.
  const emitBoardChanged = (): void => {
    if (!announceProjectId || isShuttingDown()) return;
    try {
      context.boardEvents.emitBoardChanged({
        projectId: announceProjectId,
        change: 'task-updated',
        ids: [input.taskId],
      });
    } catch (announceError) {
      console.error(`[TASK_MOVE] Announce failed for task ${input.taskId.slice(0, 8)}:`, announceError);
    }
  };

  // Whether Phase 1's DB write actually landed, and the title captured with it.
  //
  // Both are set INSIDE the lock, on the line after the move + archive pair,
  // rather than where Phase 1 returns: Phase 1 crosses await boundaries after
  // the move (see the shutdown comment on the catch below), so a throw in that
  // window would otherwise lose a change that is already committed.
  //
  // The title has to be captured rather than read at announce time. `task` is
  // scoped to the Phase 1 closure and only escapes via the returned
  // MoveSpawnPlan, and Phase 1 returns null for every move it fully handles -
  // so on the common paths there is no task in scope by the time we announce.
  let moveCommitted = false;
  let movedTaskTitle = '';
  const runMove = async (): Promise<void> => {
  try {
    // === Phase 1 (locked, short) ===
    // All DB mutations and PTY kill/suspend dispatch for priorities 1-3.
    // Returns null when the move is fully handled inside Phase 1 (Priorities
    // 1, 2, 2.5, 3b, 3c), or a plan for Priority 3a / Priority 4 which need
    // slow worktree + spawn work in Phase 2/3.
    const plan = await withTaskLock(input.taskId, async (): Promise<MoveSpawnPlan | null> => {
      const resolvedProjectId = projectId ?? context.currentProjectId;
      // Use !== undefined (not ??) to distinguish "caller passed null" from "caller omitted the arg"
      const resolvedProjectPath = projectPath !== undefined ? projectPath : context.currentProjectPath;
      if (!resolvedProjectId) throw new Error('No project is currently open');

      const { tasks, swimlanes, attachments } = getProjectRepos(context, resolvedProjectId);
      let task = tasks.getById(input.taskId);
      if (!task) throw new Error(`Task ${input.taskId} not found`);
      if (input.expectedSwimlaneId !== undefined && task.swimlane_id !== input.expectedSwimlaneId) {
        throw new Error('Task column changed before the guarded move');
      }
      if (input.expectedRevision !== undefined && task.revision !== input.expectedRevision) {
        throw new Error('Task revision changed before the guarded move');
      }

      let fromSwimlaneId = task.swimlane_id;
      let originalPosition = task.position;
      let fromLane = swimlanes.getById(fromSwimlaneId);
      // Board Profiles: fold the task's profile over the destination column
      // ONCE, here, so every read below (agent resolution, the injection plan's
      // model/effort delta, the effort restart check, auto_command) sees the
      // same profile-resolved strategy the cold spawn path uses.
      //
      // This path is the warm one - the destination already has a live session -
      // and it is where a half-wired profile does its quiet damage: the delta
      // check would compare the running session against the column's BASE model,
      // see no change, and leave the PTY on the previous column's rung while
      // spawnAgent would have switched it. Same task, different horsepower
      // depending on whether a session happened to be live.
      const rawToLane = swimlanes.getById(input.targetSwimlaneId);

      if (options?.route) {
        const routed = tasks.routeFromTodo(options.route);
        if (routed.status === 'duplicate') {
          let committed = tasks.getById(input.taskId);
          // A completed lifecycle cleared pending_dispatch_id when its session
          // row was inserted. A retry is then a true no-op. If it is still
          // pending, the atomic DB move landed but lifecycle/spawn did not;
          // resume it instead of stranding the card outside To Do forever.
          if (!committed || !routeLifecycleNeedsRecovery(committed, options.route.dispatchId)) return null;

          // A failed spawn rolls the row back to To Do but deliberately keeps
          // the pending dispatch. Restore the authorized destination before
          // continuing; otherwise Phase 3 sees To Do and skips the spawn.
          committed = restorePendingRouteDestination(tasks, swimlanes, committed, input);

          // A crash can occur after the PTY is born but before task/session rows
          // are durable. Retire any such in-memory orphan before re-spawning so
          // recovery never creates two agents for one dispatch.
          await retireOrphanTaskSessions(context.sessionManager, committed.id);
          if (committed.session_id) tasks.update({ id: committed.id, session_id: null });

          const todoLane = swimlanes.list().find((lane) => lane.role === 'todo');
          if (!todoLane) throw new Error('Cannot recover router lifecycle: To Do column is missing');
          fromSwimlaneId = todoLane.id;
          fromLane = todoLane;
          originalPosition = tasks.nextPositionInSwimlane(todoLane.id);
        }
        const refreshed = tasks.getById(input.taskId);
        if (!refreshed) throw new Error(`Task ${input.taskId} disappeared after route commit`);
        task = refreshed;
      } else {
        // Ordinary UI/MCP moves retain the established repository path.
        tasks.move(input);
        const approvedLabels = labelsAfterHumanDraftApproval(
          task.labels,
          fromLane?.name,
          rawToLane?.name,
          origin,
        );
        if (approvedLabels !== task.labels) {
          task = tasks.update({ id: task.id, labels: approvedLabels });
          console.log(`[TASK_MOVE] Recorded human approval for task ${task.id.slice(0, 8)} (Draft -> Approved)`);
        }
        // Leaving the quiet Draft is the human GO boundary. Detach the Trello
        // mirror in the same locked lifecycle before any worktree/session work,
        // so a scheduled sync can never reclaim or overwrite the active task.
        if (fromLane?.name === 'Draft' && task.external_source === 'trello_draft') {
          tasks.detachExternalDraft(task.id);
          task = tasks.getById(task.id) ?? task;
        }
      }

      const toLane = applyProfileToLane(rawToLane, loadTaskProfile(context, task, resolvedProjectPath)) ?? rawToLane;

      // Only send the full prompt template (title + description + attachments) when
      // starting from To Do. Non-To Do sources are resuming previously-started
      // work, so re-sending the original description would duplicate context.
      const skipPromptTemplate = fromLane?.role !== 'todo';

      // Recovery move: the first move OUT of Done (whatever the destination)
      // resumes the session idle without injecting the destination column's
      // auto_command. The user is restoring the task to inspect it; the next
      // move injects per column config. See spawnAgent's `suppressAutoCommand`.
      const suppressAutoCommand = fromLane?.role === 'done';

      // Atomic archive for Done-role target: run synchronously in the same tick
      // as tasks.move so no reader can observe the intermediate state
      // (swimlane_id=Done, archived_at=NULL). better-sqlite3 is synchronous, so
      // a concurrent IPC handler cannot interleave SQL between these two calls.
      // Without this, a failure or hang in the downstream suspend/worktree-delete
      // leaves the task stuck as an active Done-column card.
      const isCrossColumnToDone = toLane?.role === 'done' && fromSwimlaneId !== input.targetSwimlaneId;
      if (isCrossColumnToDone) {
        tasks.archive(input.taskId);
        console.log(`[TASK_MOVE] Auto-archived task ${input.taskId.slice(0, 8)} (moved to Done)`);
      }

      // The inverse, in the same tick and for the same reason. A move OUT of
      // Done must clear the flag this handler set on the way in, or the task
      // lands in a live column while still archived: absent from the board
      // (every list query filters `archived_at IS NULL`) yet holding a worktree
      // and, in an auto-spawn column, a running agent. That is the same
      // "live agent with no card" state the Done/archived resume guard exists
      // to prevent, reached through a different door.
      //
      // The UI never takes this path - dragging or restoring an archived card
      // routes to TASK_UNARCHIVE - so this is reached by MCP `move_task` and
      // any other main-process caller of handleTaskMove.
      //
      // Keyed on the task's own flag rather than the source lane's role, so a
      // legacy archived row parked outside Done is repaired too. Moving WITHIN
      // Done keeps its archive (toLane is still the done role).
      // Truthiness, not `!== null`: a Task assembled without the column carries
      // `undefined`, and `!== null` would try to unarchive every ordinary move.
      if (Boolean(task.archived_at) && toLane?.role !== 'done') {
        tasks.clearArchived(input.taskId);
        console.log(`[TASK_MOVE] Unarchived task ${input.taskId.slice(0, 8)} (moved out of Done)`);
      }

      // The board row has changed on disk from here on, so it must be announced
      // even if everything downstream fails. See the announce block after the
      // try/catch for why "the move threw" does not imply "nothing changed".
      moveCommitted = true;
      movedTaskTitle = task.title;

      // Commit-time announce. Everything slow in this handler comes AFTER this
      // line, and much of it still inside this lock: the Done branch suspends,
      // reaps leftovers and deletes the worktree before Phase 1 returns, and
      // an auto-spawn destination pays for worktree creation and spawn in
      // Phases 2/3. Announcing only from the settle-time `finally` meant a
      // paired phone saw nothing until the desktop was completely done, so a
      // phone that had moved a card optimistically had no board snapshot to
      // settle against until its own verb timed out.
      //
      // Bus only. The origin-keyed renderer push stays at settle time: the
      // `agent` and `auto-move` pushes each raise a toast per push, so pushing
      // here too would toast the same move twice. The second bus emit from the
      // `finally` is cheap: the Agent Monitor debounces it into the push it
      // already scheduled, and a paired phone gets one more small board event,
      // which it already tolerates (the session-lifecycle feed double-emits by
      // design). That second emit is what corrects a committed-then-rolled-back
      // move. Same row, same shape, two emits.
      emitBoardChanged();

      // Commit signal for a caller that answers on the row landing (the mobile
      // bridge verb). Bus first, so the board event is already queued on the
      // session before the verb response goes out. A caller's callback must
      // never turn a committed move into a rejection with the rest of this
      // branch (the Done cleanup) skipped, so it is fenced like the announce.
      if (options?.onCommitted) {
        try {
          options.onCommitted();
        } catch (callbackError) {
          console.error(`[TASK_MOVE] onCommitted callback threw for task ${input.taskId.slice(0, 8)}:`, callbackError);
        }
      }

      // Within-column reorder: no side effects needed
      if (fromSwimlaneId === input.targetSwimlaneId) return null;

      const db = getProjectDb(resolvedProjectId);
      const sessionRepo = new SessionRepository(db);
      const usageHistoryRepo = new UsageHistoryRepository(db);
      // Resolved once per move and threaded into every git-churn capture site
      // below so they all resolve the base branch identically.
      const effectiveDefaultBranch = resolveDefaultBaseBranch(context, resolvedProjectPath);

      // Analytics: track critical-path transitions only.
      // Read agent from task.agent (set at spawn) and model from the latest
      // session record (the most recent run's CLI model id). Cost/duration/
      // token/tool metrics come from the LIFETIME summary aggregated across
      // every session row for the task (getSummaryForTask), so a task worked
      // across resume/suspend legs reports cumulative totals rather than just
      // the final leg - getLatestForTask alone would silently drop every
      // earlier leg's metrics. Any field may be missing (legacy rows, never
      // spawned, exited before any usage was recorded) - omit absent props.
      // These are properties on an existing event (budget-neutral), not new
      // events.
      if (toLane?.role === 'done') {
        const completeProps: Record<string, string | number | boolean> = {};
        if (task.agent) completeProps.agent = task.agent;
        const latestSessionRecord = sessionRepo.getLatestForTask(task.id);
        if (latestSessionRecord?.model_id) {
          completeProps.model = parseModelId(latestSessionRecord.model_id).baseId;
        }
        // The resolved mode the last session actually ran under (the task's
        // own permission_mode is a raw override, null = inherit).
        if (latestSessionRecord?.permission_mode) {
          completeProps.permissionMode = latestSessionRecord.permission_mode;
        }
        const lifetimeSummary = sessionRepo.getSummaryForTask(task.id);
        if (lifetimeSummary) {
          completeProps.durationSeconds = Math.round(lifetimeSummary.durationMs / 1000);
          completeProps.costUsd = Math.round(lifetimeSummary.totalCostUsd * 10000) / 10000;
          completeProps.inputTokens = lifetimeSummary.totalInputTokens;
          completeProps.outputTokens = lifetimeSummary.totalOutputTokens;
          completeProps.toolCalls = lifetimeSummary.toolCallCount;
        }
        trackEvent('task_complete', completeProps);
        trackMilestone('first_task_complete');
      }

      // --- Priority 1: TARGET IS TO DO → full reset (kill session, remove worktree, delete branch) ---
      if (toLane?.role === 'todo') {
        context.terminalSubmitScheduler.cancel(task.id);
        // Clear any lingering spawn progress label from an in-flight spawn
        // that was aborted by this move. The aborted move's catch block also
        // calls clearSpawnProgress, but doing it here too guarantees the
        // renderer's "Initializing..." indicator vanishes regardless of
        // whether the prior move reached its catch path.
        clearSpawnProgress(context.mainWindow, task.id);
        // Kill (but don't remove from map) any in-flight PTY session spawned
        // by a concurrent move that hasn't written session_id to the task
        // record yet. Using killByTaskId instead of removeByTaskId so the
        // session stays in the map - cleanupTaskResources needs it there for
        // awaitExit to wait for the process to actually die before removing
        // the worktree (Windows file handles aren't released until exit).
        // kill() always tags the exit intentional, so this deliberate hard
        // reset's non-zero force-kill exit never surfaces a false "Session
        // crashed" toast.
        context.sessionManager.killByTaskId(task.id);
        await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
        // Re-read the task to check if worktree_path was actually cleared
        const updatedTask = tasks.getById(task.id);
        if (updatedTask?.worktree_path) {
          console.warn(`[TASK_MOVE] Partial cleanup for task ${task.id.slice(0, 8)} (moved to To Do, session removed but worktree directory could not be deleted - will retry on next startup)`);
        } else {
          console.log(`[TASK_MOVE] Full cleanup for task ${task.id.slice(0, 8)} (moved to To Do, session + worktree + branch removed)`);
        }
        // Schedule background prune to clean up stale git worktree metadata
        if (resolvedProjectPath) {
          WorktreeManager.scheduleBackgroundPrune(resolvedProjectPath);
        }
        return null;
      }

      // --- Priority 2: TARGET IS DONE → suspend + archive (resumable on unarchive) ---
      if (toLane?.role === 'done') {
        context.terminalSubmitScheduler.cancel(task.id);
        // A genuine park, not a respawn: retire any label a prior in-flight
        // spawn left behind (the same reasoning as Priority 1's clear above).
        // Without this, the renderer's suspended-row carve-out (added for the
        // handoff flash fix) would keep showing that stale label instead of
        // "Paused" through the whole archive below.
        clearSpawnProgress(context.mainWindow, task.id);
        // Taken before the suspend below: suspending kills the PTY, which
        // orphans whatever the agent backgrounded inside the worktree. On POSIX
        // those children reparent to init immediately, so the tree cannot be
        // walked afterwards. Reading it costs nothing - see
        // captureSessionLeftovers.
        const leftovers = captureSessionLeftovers(context, task.session_id);
        if (task.session_id) {
          const record = sessionRepo.getLatestForTask(task.id);
          // Accept 'running' AND 'exited' -- exited covers Claude natural exit.
          // Queued sessions never started Claude CLI, so mark exited (not suspended)
          // to avoid a failed --resume attempt when the task is later moved back.
          if (record && record.agent_session_id
              && (record.status === 'running' || record.status === 'exited')) {
            // Capture metrics before suspend (caches are still populated)
            captureSessionMetrics(
              context.sessionManager,
              sessionRepo,
              usageHistoryRepo,
              task.session_id,
              record.id,
              record.started_at,
              record.session_type,
            );
            refineTranscriptTokens(context.sessionManager, sessionRepo, task.session_id, record.id);
            refineTranscriptToolCounts(context.sessionManager, sessionRepo, task.session_id, record.id);
            markRecordSuspended(sessionRepo, record.id, 'system');
            console.log(`[TASK_MOVE] Suspended session record ${record.id.slice(0, 8)} for task ${task.id.slice(0, 8)}`);
          } else if (record && record.status === 'queued') {
            markRecordExited(sessionRepo, record.id);
            console.log(`[TASK_MOVE] Exited queued session record ${record.id.slice(0, 8)} for task ${task.id.slice(0, 8)}`);
          }
          await context.sessionManager.suspend(task.session_id);
          tasks.update({ id: task.id, session_id: null });
        } else {
          // No active PTY -- preserve latest exited session for future resume.
          // With the state machine, canResume() checks agent_session_id existence
          // regardless of status, so this marker is mainly for UI display.
          const record = sessionRepo.getLatestForTask(task.id);
          if (record && record.agent_session_id
              && record.session_type !== 'run_script'
              && record.status === 'exited') {
            markRecordSuspended(sessionRepo, record.id, 'system');
            console.log(`[TASK_MOVE] Preserved exited session ${record.id.slice(0, 8)} for future resume`);
          }
        }
        // Kill what the session left running in the worktree before anything
        // tries to delete it. A backgrounded dev server holds the directory as
        // its cwd, which on Windows makes the removal below fail and leaves a
        // husk with no git admin entry - the failure that later hangs a fresh
        // worktree creation. Must precede deleteTaskWorktree.
        await reapSessionLeftovers(task.id, leftovers);

        // Capture git churn (fire-and-forget, best-effort). In the PR flow the
        // branch is usually already merged by the time a task reaches Done, so
        // this mostly just re-confirms whatever an earlier suspend/move already
        // captured; the no-clobber guard means a now-empty diff here can never
        // wipe that earlier real capture.
        const latestRecord = sessionRepo.getLatestForTask(task.id);
        if (latestRecord) {
          captureGitChurn(task, sessionRepo, usageHistoryRepo, latestRecord.id, resolvedProjectPath, effectiveDefaultBranch);
        }

        // Delete the local worktree to reclaim disk. Preserve branch_name and
        // session records so moving back out of Done can restore both.
        if (task.worktree_path) {
          const worktreeDeleted = await deleteTaskWorktree(context, task, tasks, resolvedProjectPath);
          if (worktreeDeleted) {
            console.log(`[TASK_MOVE] Deleted worktree for task ${task.id.slice(0, 8)} (moved to Done; branch + session preserved)`);
          } else {
            console.warn(`[TASK_MOVE] Partial worktree delete for task ${task.id.slice(0, 8)} (moved to Done; directory could not be deleted - will retry on next startup)`);
          }
          if (resolvedProjectPath) {
            WorktreeManager.scheduleBackgroundPrune(resolvedProjectPath);
          }
        }
        // Done ends the spawn decision `worktree_skip_reason` describes; a task
        // unarchived later re-decides at its next spawn, so a stale "project
        // folder" claim must not ride along. Outside the worktree block on
        // purpose: the task carrying a reason is the one WITHOUT a worktree.
        if (tasks.getById(task.id)) {
          tasks.setWorktreeSkipReason(task.id, null);
        }

        // Archive already happened synchronously right after tasks.move above.
        return null;
      }

      // --- Priority 2.5: TARGET HAS auto_spawn=false (and not backlog/done which are handled above) ---
      // → Suspend session if one exists, do NOT spawn new agent
      if (toLane && !toLane.auto_spawn) {
        context.terminalSubmitScheduler.cancel(task.id);
        // A genuine park, not a respawn: same reasoning as Priority 2's clear
        // above. Retires any label an in-flight spawn left behind so the
        // renderer's suspended-row carve-out doesn't keep it alive.
        clearSpawnProgress(context.mainWindow, task.id);
        if (task.session_id) {
          const record = sessionRepo.getLatestForTask(task.id);
          if (record && record.agent_session_id
              && (record.status === 'running' || record.status === 'exited')) {
            captureSessionMetrics(
              context.sessionManager,
              sessionRepo,
              usageHistoryRepo,
              task.session_id,
              record.id,
              record.started_at,
              record.session_type,
            );
            refineTranscriptTokens(context.sessionManager, sessionRepo, task.session_id, record.id);
            refineTranscriptToolCounts(context.sessionManager, sessionRepo, task.session_id, record.id);
            captureGitChurn(task, sessionRepo, usageHistoryRepo, record.id, resolvedProjectPath, effectiveDefaultBranch);
            markRecordSuspended(sessionRepo, record.id, 'system');
          } else if (record && record.status === 'queued') {
            markRecordExited(sessionRepo, record.id);
          }
          await context.sessionManager.suspend(task.session_id);
          tasks.update({ id: task.id, session_id: null });
          console.log(`[TASK_MOVE] Suspended session for task ${task.id.slice(0, 8)} (target column has auto_spawn=false)`);
        }
        return null;
      }

      // --- Priority 3: TASK HAS ACTIVE SESSION ---
      // Five sub-cases (in evaluation order):
      //   a) Agent change (handoff): suspend + fall through to spawnAgent
      //   b) Same agent + permission-mode delta (destination's effective mode
      //      differs from the session record's spawn-time mode): suspend and
      //      respawn so --permission-mode / --model / --effort land as CLI
      //      flags (no adapter can switch permission mode on a live session)
      //   c) Same agent + adapter has live-swap plan: inject command(s)
      //      directly into running session (model/effort/auto_command)
      //   d) Same agent + no live-swap plan + model/effort delta: suspend
      //      and respawn so the new flags land via command-line args
      //   e) Same agent + no delta and no live-swap: keep session alive
      //      (no-op; preserves auto_command-less moves between custom columns)
      if (task.session_id) {
        context.terminalSubmitScheduler.cancel(task.id);

        // The session record for the currently-live PTY. Read once here and
        // reused by the agent-change / respawn suspend paths below (one read,
        // not three).
        const activeRecord = sessionRepo.getLatestForTask(task.id);

        // --- Session switch: suspend the live session and route to Phase 2/3,
        //     which resumes-or-spawns the TARGET session via spawnAgent(toLane)
        //     (the target track + fresh-vs-resume policy are derived from the
        //     column in resolveSpawnOverrides). Two conditions trigger it:
        //       1. The live session is on a DIFFERENT track than the target wants.
        //          A single inequality covers both transitions: entering an
        //          isolated column (active != that column's id) and leaving one
        //          back to main (active is a swimlane id, target is null). The
        //          leave case is the bug guard: without it, leaving an isolated
        //          column would mis-fire as Priority 3d keep-alive and strand the
        //          isolated session in a normal column.
        //       2. The target column forces a fresh session each entry
        //          ('always_spawn_new'), even when the track is the SAME. Phase 3
        //          carries forceFresh and spawns fresh, retiring the prior pass.
        //     Suspend preserves agent_session_id so the prior record stays
        //     retireable/resumable. The worktree is shared and already exists, so
        //     Phase 2 is a no-op; going through Phase 3 reuses the CAS + abort +
        //     rollback machinery (a PTY spawned here in Phase 1 would bypass that
        //     and could leak on a mid-spawn abort). Entering with NO live session
        //     is handled by Priority 4 below; this branch only fires for a live one.
        const targetIsolatedSwimlaneId = resolveIsolatedSwimlaneId(toLane);
        const activeIsolatedSwimlaneId = activeRecord?.isolated_swimlane_id ?? null;
        const targetForceFresh = resolveForceFresh(toLane);
        const needsSessionSwitch = toLane !== undefined
          && (activeIsolatedSwimlaneId !== targetIsolatedSwimlaneId || targetForceFresh);
        if (needsSessionSwitch && toLane) {
          await suspendLiveSessionForRespawn({
            context,
            tasks,
            sessionRepo,
            usageHistoryRepo,
            taskId: task.id,
            liveSessionId: task.session_id,
            record: activeRecord,
            task,
            projectPath: resolvedProjectPath,
            defaultBaseBranch: effectiveDefaultBranch,
            phase: 'new-session',
          });
          console.log(
            `[TASK_MOVE] Session switch for task ${task.id.slice(0, 8)}:`
            + ` ${activeIsolatedSwimlaneId ?? 'main'} -> ${targetIsolatedSwimlaneId ?? 'main'}`
            + ` (${targetForceFresh ? 'force-fresh' : 'resume-or-spawn'};`
            + ` suspended live session; Phase 3 will spawn/resume the target).`,
          );
          return {
            task,
            fromSwimlaneId,
            fromLane,
            originalPosition,
            toLane,
            skipPromptTemplate,
            resolvedProjectId,
            resolvedProjectPath,
            continuationPrompt: options?.continuationPrompt,
            suppressAutoCommand,
          };
        }

        const project = context.projectRepo.getById(resolvedProjectId);
        const { agent: effectiveTargetAgent, isHandoff: isAgentChange } = resolveTargetAgent({
          taskAgentOverride: task.agent_override,
          columnAgent: toLane?.agent_override ?? null,
          taskAgent: task.agent,
          projectDefaultAgent: project?.default_agent ?? null,
        });

        if (isAgentChange) {
          // (a) Cross-agent handoff: suspend and fall through to spawnAgent.
          // Cross-agent resume is impossible (agent_session_id is agent-specific).
          //
          // Clear per-task model/effort overrides on cross-agent handoff.
          // Override values are model-name-specific (e.g. "claude-sonnet-4-6")
          // and effort tiers are agent-specific (e.g. Claude's "xhigh" is
          // Opus-only and has no analogue on Codex). Carrying them into a
          // different agent's spawn would either crash the CLI or be silently
          // ignored. Cleanest contract: the lock applies for the duration of
          // a single agent's tenure on the task; an explicit handoff resets it
          // and the user can re-pick on the new agent if they want.
          //
          // Skipped when `task.agent_override` is set: the user locked the
          // agent at task creation and the model/effort were picked for that
          // exact agent. Normally `resolveTargetAgent` returns the override
          // and `isHandoff` is false in that case, so this branch shouldn't
          // even execute - this guard is defensive against state drift.
          await suspendLiveSessionForRespawn({
            context,
            tasks,
            sessionRepo,
            usageHistoryRepo,
            taskId: task.id,
            liveSessionId: task.session_id,
            record: activeRecord,
            task,
            projectPath: resolvedProjectPath,
            defaultBaseBranch: effectiveDefaultBranch,
            phase: 'switching-agent',
            additionalTaskUpdates: task.agent_override
              ? undefined
              : { model_override: null, effort_override: null },
          });
          console.log(
            `[TASK_MOVE] Suspending session for task ${task.id.slice(0, 8)}`
            + ` (agent change: ${task.agent} -> ${effectiveTargetAgent}).`
            + (task.agent_override
                ? ` Kept model/effort overrides (task has locked agent_override).`
                : ` Cleared model/effort overrides.`)
            + ` Will handoff to new agent.`,
          );
          // Fall through to Phase 2/3 (handoff spawn) by not returning null.
        } else {
          // Same agent, live session. For this column transition:
          //   1. MODEL change  -> the ONLY restart marker: suspend + `--resume`
          //      so the resumed spawn re-applies model + effort + permission as
          //      launch flags and re-delivers the column auto_command / plan-exit
          //      continuation. A live `/model` swap is deliberately NOT used: it
          //      left the agent paused after a Planning -> Executing handoff.
          //   2. EFFORT-only change (same model) -> live `/effort` injection (or a
          //      respawn for adapters with no live effort swap and a concrete target).
          //   3. PERMISSION-only change, or no change -> keep the live session
          //      running untouched. A permission delta NEVER restarts: in the
          //      canonical Planning -> Executing flow the user already approved the
          //      plan in the terminal and Claude left plan mode in-session, so the
          //      recorded spawn-time permission mode is a stale signal that must
          //      not churn the PTY.
          //
          // Translation of the model/effort/auto_command delta is delegated to
          // prepareInjectionPlan so adapters own their slash syntax and the
          // model-restart policy stays in one place (agent-agnostic here).
          const adapter = task.agent ? agentRegistry.get(task.agent) : undefined;
          // Resolve through the shared tier chain (task -> column) rather than
          // reading the lane directly. Reading `toLane.auto_command` alone
          // dropped a task's own auto_command on this path while the spawn path
          // honored it, so the same task behaved differently on a cold spawn
          // than on a warm move into a column with a live session.
          const effectiveAutoCommand = resolveEffectiveAutoCommand(task.auto_command, toLane?.auto_command);
          const interpolatedAuto = effectiveAutoCommand?.trim()
            ? interpolateTaskTemplate(effectiveAutoCommand, resolveTaskTemplateVars({
                task,
                defaultBaseBranch: effectiveDefaultBranch,
                attachmentPaths: attachments.getPathsForTask(task.id),
                devPort: getDevPortForTask(task.id),
                projectPath: resolvedProjectPath,
              }))
            : '';
          // Read ONCE and share with the 2b fallback below, so the plan and the
          // respawn decision cannot straddle a status update and disagree about
          // what the session is running at.
          const liveEffort = resolveLiveEffort(context.sessionManager, task.session_id);
          const plan = prepareInjectionPlan({
            adapter,
            sessionRepo,
            task,
            toLane: toLane ?? null,
            project,
            autoCommand: interpolatedAuto,
            liveEffort,
          });

          // 1. Model change -> suspend + respawn. Checked BEFORE live injection
          // so a model change never live-swaps. Phase 3 re-applies the flags and
          // delivers the auto_command / continuation via spawnAgent.
          if (plan?.needsRestartForModel) {
            await suspendLiveSessionForRespawn({
              context,
              tasks,
              sessionRepo,
              usageHistoryRepo,
              taskId: task.id,
              liveSessionId: task.session_id,
              record: activeRecord,
              task,
              projectPath: resolvedProjectPath,
              defaultBaseBranch: effectiveDefaultBranch,
              phase: 'switching-model',
            });
            console.log(
              `[TASK_MOVE] Suspending session for task ${task.id.slice(0, 8)}`
              + ` (model change requires respawn). Will respawn with destination column flags.`,
            );
            return {
              task,
              fromSwimlaneId,
              fromLane,
              originalPosition,
              toLane,
              skipPromptTemplate,
              resolvedProjectId,
              resolvedProjectPath,
              continuationPrompt: options?.continuationPrompt,
              suppressAutoCommand,
            };
          }

          // 2a. Effort-only change (and/or auto_command) with a live-swap plan ->
          // inject into the running PTY. With no model delta the sequence carries
          // at most `/effort` + the auto_command.
          if (plan) {
            const injectedSessionId = task.session_id;
            context.terminalSubmitScheduler.scheduleKeystrokes(task.id, injectedSessionId, plan.sequence, {
              verifier: plan.verifier,
              mode: toLane?.auto_command_mode ?? 'immediate',
              // Rung 3 of the delivery ladder. Routed through the allowlisted
              // in-place restart rather than a new spawn call, so this adds no
              // spawn entry point (see spawn-entry-point-parity.md).
              escalate: async (commands) => {
                if (!resolvedProjectPath) return false;
                // `restartSessionForSettingsChange` mutates per-task session
                // state and documents that its caller must hold the task lock.
                // Taking it here is safe and not reentrant: `scheduleKeystrokes`
                // is fire-and-forget, so this callback runs well after the
                // TASK_MOVE handler released the lock.
                return withTaskLock(task.id, async () => {
                  const restarted = await restartSessionForSettingsChange(
                    context,
                    resolvedProjectId,
                    resolvedProjectPath,
                    task.id,
                    { resumePrompt: commands.join('\n') },
                  );
                  return restarted.ok;
                });
              },
              onOutcome: (report) => reportAutoCommandOutcome(context, tasks, task, report, resolvedProjectId),
            });
            // Record what the burst applied so the NEXT move diffs against the
            // session's new running value instead of re-injecting it.
            if (plan.appliedSettings) {
              sessionRepo.updateAppliedSettings(task.session_id, plan.appliedSettings);
            }
            console.log(
              `[TASK_MOVE] Injecting ${plan.sequence.length} command(s) for task ${task.id.slice(0, 8)}`
              + ` into running session${plan.verifier ? ' (with command verification)' : ''}: `
              + `${plan.sequence.map((command) => command.text).join(' | ')}`,
            );
            return null;
          }

          // 2b. No live-swap plan, but an EFFORT delta to a concrete target on an
          // adapter with no live `/effort` swap -> suspend + respawn to apply the
          // new effort as a CLI flag. (Model deltas are handled in step 1 above; a
          // null target is the "Default" column, which `--resume` preserves, so no
          // respawn.) Source is the session's ACTUAL applied value (same ground
          // truth prepareInjectionPlan uses), NOT the leaving column's config - a
          // null/drifted `fromLane` would otherwise churn the PTY. Per-task
          // overrides win (no respawn when the task pinned the field). The
          // `!interpolatedAuto` guard is structurally redundant (an auto_command
          // would have produced a non-null plan above) but kept for safety.
          const sourceEffort = resolveSourceEffort({
            taskEffortOverride: task.effort_override,
            liveEffort,
            appliedEffort: activeRecord?.applied_effort,
          });
          const targetEffort = task.effort_override ?? toLane?.effort_override ?? project?.default_effort ?? null;
          const restartNeededForEffort = targetEffort !== sourceEffort && targetEffort !== null;

          if (restartNeededForEffort && !interpolatedAuto) {
            await suspendLiveSessionForRespawn({
              context,
              tasks,
              sessionRepo,
              usageHistoryRepo,
              taskId: task.id,
              liveSessionId: task.session_id,
              record: activeRecord,
              task,
              projectPath: resolvedProjectPath,
              defaultBaseBranch: effectiveDefaultBranch,
              phase: 'applying-settings',
            });
            console.log(
              `[TASK_MOVE] Suspending session for task ${task.id.slice(0, 8)}`
              + ` (effort changed, adapter has no live swap). Will respawn with new settings.`,
            );
            // Fall through to Phase 2/3 (spawn with new settings)
            return {
              task,
              fromSwimlaneId,
              fromLane,
              originalPosition,
              toLane,
              skipPromptTemplate,
              resolvedProjectId,
              resolvedProjectPath,
              continuationPrompt: options?.continuationPrompt,
              suppressAutoCommand,
            };
          }

          // 3. Permission-only delta, or no delta -> keep the live session alive.
          // A permission change never restarts (see header); there is no
          // model/effort delta to apply.
          console.log(
            `[TASK_MOVE] Task ${task.id.slice(0, 8)} keeping active session alive`
            + ` (no model change; permission-only or no delta, same agent).`,
          );
          return null;
        }
      }

      // --- Priority 4 (or 3a fall-through): TASK HAS NO ACTIVE SESSION ---
      // Return the plan; Phase 2 creates the worktree (unlocked, serialized
      // per-project by WorktreeManager.projectQueues), Phase 3 spawns.

      // Symmetric clear for cross-agent destinations on the no-session path.
      // Mirrors the live-handoff clear in Priority 3a (line ~336): model and
      // effort overrides are model-name-specific and don't carry across
      // agents. Without this, a task created in a Claude column with overrides
      // and dragged into a Codex column before its first spawn would pass
      // `claude-sonnet-4-6` into Codex's command builder. We do this here
      // (after the early returns above) so non-spawning destinations (Done,
      // auto_spawn=false) keep the user's overrides intact for when the task
      // moves back into a spawning column.
      //
      // Skipped when `task.agent_override` is set: the user locked the agent
      // at task creation, so the model/effort were picked for that exact
      // agent. Column moves cannot trigger an agent change in this case
      // (resolveTargetAgent returns task.agent_override regardless of column),
      // so the overrides remain valid.
      let planTask = task;
      if (!planTask.agent_override && (planTask.model_override || planTask.effort_override) && toLane) {
        const project = context.projectRepo.getById(resolvedProjectId);
        const projectDefault = project?.default_agent ?? null;
        const sourceAgent = planTask.agent ?? projectDefault;
        const targetAgent = toLane.agent_override ?? projectDefault;
        if (sourceAgent && targetAgent && sourceAgent !== targetAgent) {
          tasks.update({
            id: planTask.id,
            model_override: null,
            effort_override: null,
          });
          console.log(
            `[TASK_MOVE] Cleared model/effort overrides on task ${planTask.id.slice(0, 8)}`
            + ` (cross-agent move ${sourceAgent} -> ${targetAgent}, no live session).`,
          );
          // Refresh the snapshot so the downstream plan reflects the cleared
          // state (Phase 3 re-reads task from DB anyway, but the plan object
          // is a captured snapshot consumed by the caller).
          const refreshed = tasks.getById(planTask.id);
          if (refreshed) planTask = refreshed;
        }
      }

      return {
        task: planTask,
        fromSwimlaneId,
        fromLane,
        originalPosition,
        toLane,
        skipPromptTemplate,
        resolvedProjectId,
        resolvedProjectPath,
        continuationPrompt: options?.continuationPrompt,
        suppressAutoCommand,
      };
    });

    if (!plan) return; // Phase 1 fully handled the move

    const { task, fromSwimlaneId, fromLane, originalPosition, toLane, skipPromptTemplate, resolvedProjectId, resolvedProjectPath, continuationPrompt, suppressAutoCommand } = plan;

    // Shutdown started while Phase 1 ran. Skip Phase 2 git work and Phase 3
    // spawn so we don't write to a closed DB. autoSpawnTasks on next launch
    // will spawn for the destination column. A respawn branch (model change,
    // agent handoff, effort respawn, session switch) may have already emitted
    // a spawn-progress label before this point (see suspendLiveSessionForRespawn);
    // this return sits outside every try/finally below, so it must retire that
    // label itself or it strands until the 120s TTL.
    if (isShuttingDown()) {
      clearSpawnProgress(context.mainWindow, task.id);
      return;
    }

    // === Phase 2 (unlocked, slow) ===
    // All async operations below receive the abort signal so a newer move
    // cancels them via AbortError. Cleanup is centralized in the outer catch.
    // Git I/O is serialized per-project by WorktreeManager.projectQueues; DB
    // writes inside ensureTaskWorktree are sync better-sqlite3 calls.
    const onProgress = createProgressCallback(context.mainWindow, task.id);
    // Emitted only when the git op parks in the per-project queue behind
    // another op. The 'fetching' label is emitted by the git layer itself once
    // the op actually starts, so we no longer eagerly show "Fetching latest..."
    // here (which made a queue wait masquerade as an active fetch).
    const onWaitProgress = (info: GitWaitProgress) => emitSpawnWaiting(
      context.mainWindow,
      task.id,
      info.jobsAhead,
      info.runningLabel ? { label: info.runningLabel, elapsedMs: info.runningElapsedMs } : undefined,
    );
    try {
      // Create worktree if worktrees are enabled and task doesn't have one yet.
      // If worktree creation fails (e.g. duplicate branch), revert the task
      // back to its original column so it doesn't get stuck without a session.
      try {
        const { tasks: tasksPhase2 } = getProjectRepos(context, resolvedProjectId);
        await ensureTaskWorktree(context, task, tasksPhase2, resolvedProjectPath, { signal, onProgress, onWaitProgress, projectId: resolvedProjectId });
      } catch (error) {
        // Let AbortError propagate to the outer catch for centralized handling
        if (isAbortError(error)) throw error;

        // Best-effort cleanup of stale resources that may have caused the failure
        // (e.g. leftover directory or branch from a previous partial cleanup).
        // This makes the next drag attempt succeed without requiring an app restart.
        if (resolvedProjectPath) {
          try {
            const worktreeManager = new WorktreeManager(resolvedProjectPath);
            // Creation just failed, possibly before the DB write landed, so no
            // single field is trustworthy here. Probe every directory this task
            // could plausibly own: the stored path, the folder it is pinned to,
            // the numeric name a fresh creation would pick, and the legacy
            // title-derived name from before the numeric scheme.
            const candidateWorktreePaths = candidateWorktreePathsFor(task, resolvedProjectPath);
            // The BRANCH is derived independently of the folder. Folders are
            // numeric now, so falling back to the folder name here would try to
            // delete a branch literally called "460".
            const expectedBranch = task.branch_name || legacyAutoBranchNameFor(task);
            // Only an AUTO-GENERATED branch may be force-deleted here. This block
            // exists to clear leftovers from a partial cleanup, but `removeBranch`
            // is `git branch -D` with every error swallowed - so for a custom,
            // agent-supplied name it silently destroys the branch and its commits
            // on ANY worktree failure, whenever that branch is not checked out
            // somewhere. Task #538 would have lost commit 4261ff1e that way, and
            // the branch was never pushed, so origin would not have saved it.
            //
            // It was latent only because git refuses to delete a checked-out
            // branch - the very condition that caused #538 - and the main
            // checkout has since moved off it.
            //
            // `legacyAutoBranchNameFor` (the null case) is auto-generated by
            // construction, so the intended cleanup is preserved either way.
            const branchIsDeletable = !task.branch_name
              || isAutoGeneratedBranch(task.branch_name, task.id, task.title);

            await worktreeManager.withLock(async () => {
              for (const expectedPath of candidateWorktreePaths) {
                if (!fs.existsSync(expectedPath)) continue;
                // Per candidate, because removeWorktree THROWS for a path
                // outside this project's worktrees root (the raw stored
                // worktree_path is one candidate, and it is probed first). A
                // throw that escaped this loop would skip the remaining
                // candidates AND the prune / removeBranch below, leaving exactly
                // the stale state this block exists to clear.
                try {
                  // `moderate`, not the default `thorough`. Creation just failed
                  // on this same path, so a second full-budget grind re-proves
                  // what we already know while the user waits and the git queue
                  // stays held: measured, the two thorough passes put the
                  // failure toast ~62s out instead of ~34s. This block is
                  // explicitly best-effort ("will retry on next attempt"), and a
                  // still-pinned path is picked up by the husk-reuse and
                  // startup-retry net either way.
                  await worktreeManager.removeWorktree(expectedPath, { removalProfile: 'moderate' });
                } catch (removalError) {
                  console.warn(`[TASK_MOVE] Skipped stale worktree candidate ${expectedPath}:`, removalError);
                  continue;
                }
                // A removal that merely FAILS returns false rather than throwing,
                // so verify on disk.
                if (fs.existsSync(expectedPath)) {
                  console.warn(`[TASK_MOVE] Could not remove stale worktree directory (file handles may still be held): ${expectedPath}`);
                } else {
                  console.log(`[TASK_MOVE] Cleaned stale worktree directory: ${expectedPath}`);
                }
              }
              await worktreeManager.pruneWorktrees();
              if (branchIsDeletable) {
                await worktreeManager.removeBranch(expectedBranch);
              } else {
                console.log(`[TASK_MOVE] Kept custom branch "${expectedBranch}" (cleanup only removes auto-generated branches)`);
              }
            }, { label: `stale-cleanup:${task.id.slice(0, 8)}` });
          } catch (cleanupError) {
            console.warn('[TASK_MOVE] Stale resource cleanup failed (will retry on next attempt):', cleanupError);
          }
        }

        // Revert + session cleanup is handled by the outer catch below, which
        // runs on every non-abort failure (worktree setup, branch checkout,
        // or spawn). Wrap the error with a context message so the toast
        // surfaced to the renderer distinguishes worktree failures from
        // later spawn failures.
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(`Worktree setup failed: ${message}`);
      }

      // Checkout the task's branch in the main repo (non-worktree tasks only).
      // Intentionally unguarded: if checkout fails, the error propagates to
      // the outer catch which also handles AbortError cleanup. That includes
      // BranchCheckoutBlockedError, which reaches the user as a toast here, so
      // this is the one call site that needs no notifySpawnBlocked.
      await ensureTaskBranchCheckout(context, task, resolvedProjectPath, { signal, onProgress, onWaitProgress, projectId: resolvedProjectId });

      // === Phase 3 (locked, short) ===
      // CAS-check invariants before spawning. If a newer move ran during our
      // Phase 2 gap, task.swimlane_id / session_id will have changed and we
      // should bail out to avoid spawning for a stale target column. The
      // try/finally guarantees spawn-progress is cleared whether we spawn,
      // bail on CAS mismatch, or throw. The session-changed event would also
      // clear it via upsertSession, but fast-starting agents (Codex) race
      // with the renderer's state updates.
      await withTaskLock(input.taskId, async () => {
        try {
          // Shutdown started while we were waiting for the lock or Phase 2 ran.
          // The DB may already be closed; skip the spawn entirely. The
          // try/finally still calls clearSpawnProgress to clean the renderer UI.
          if (isShuttingDown()) return;
          signal.throwIfAborted();
          const { tasks: tasksPhase3, actions: actionsPhase3, attachments: attachmentsPhase3 } = getProjectRepos(context, resolvedProjectId);
          const current = tasksPhase3.getById(task.id);
          if (!current) {
            console.log(`[TASK_MOVE] Task ${task.id.slice(0, 8)} was deleted during Phase 2 - skipping spawn`);
            return;
          }
          if (current.swimlane_id !== input.targetSwimlaneId) {
            console.log(`[TASK_MOVE] Task ${task.id.slice(0, 8)} moved to a different column during Phase 2 - skipping spawn`);
            return;
          }
          if (current.session_id) {
            console.log(`[TASK_MOVE] Task ${task.id.slice(0, 8)} already has session ${current.session_id.slice(0, 8)} - skipping spawn`);
            return;
          }

          // Execute transition actions + ensure agent is running (handles resume/spawn/auto_command)
          emitSpawnProgress(context.mainWindow, task.id, 'starting-agent');
          const dbPhase3 = getProjectDb(resolvedProjectId);
          const sessionRepoPhase3 = new SessionRepository(dbPhase3);
          const engine = createTransitionEngine(context, actionsPhase3, tasksPhase3, sessionRepoPhase3, attachmentsPhase3, resolvedProjectId, resolvedProjectPath);
          if (toLane) {
            await spawnAgent({ context, engine, tasks: tasksPhase3, sessionRepo: sessionRepoPhase3, task: current, fromSwimlaneId, toLane, skipPromptTemplate, signal, projectId: resolvedProjectId, projectPath: resolvedProjectPath, continuationPrompt, suppressAutoCommand, settingsSourceLane: fromLane ?? null, attachments: attachmentsPhase3 });
          }
        } finally {
          clearSpawnProgress(context.mainWindow, task.id);
        }
      });
    } catch (error) {
      // clearSpawnProgress touches only in-memory maps and a guarded IPC
      // send, never the DB, so it is safe to call unconditionally here -
      // ahead of the shutdown bail below - rather than risk stranding a
      // respawn branch's label (see suspendLiveSessionForRespawn) until the
      // 120s TTL.
      clearSpawnProgress(context.mainWindow, task.id);

      // Shutdown closed the DB while a Phase 1 / 2 / 3 await was in flight.
      // Both the post-await DB write inside Phase 1 (e.g. line 226's
      // tasks.update after sessionManager.suspend) and the rollback below
      // would throw against the closed connection. Bail silently - shutdown
      // is already clearing session_id on running sessions and Phase 1's
      // earlier sync writes (tasks.move, tasks.archive, markRecordSuspended)
      // are committed. The IPC wrapper's swallow is a backstop; this guard
      // also keeps the rollback's "Rollback after move failure failed" log
      // from firing during shutdown.
      if (isShuttingDown()) return;

      const abort = isAbortError(error);

      // Unified rollback path for Phase 2/3 failures: clean up any partially
      // spawned session and revert the task move if the task is still in the
      // destination column. The CAS guard on swimlane_id means a concurrent
      // move that already relocated the task (e.g. user dragged again) keeps
      // its authoritative state - we only undo our own forward move.
      await withTaskLock(input.taskId, async () => {
        try {
          context.sessionManager.removeByTaskId(task.id);
          const { tasks: tasksRollback } = getProjectRepos(context, resolvedProjectId);
          const current = tasksRollback.getById(task.id);
          if (!current) return;
          if (current.session_id) {
            tasksRollback.update({ id: task.id, session_id: null });
          }
          if (!abort && current.swimlane_id === input.targetSwimlaneId) {
            tasksRollback.move({
              taskId: input.taskId,
              targetSwimlaneId: fromSwimlaneId,
              targetPosition: originalPosition,
            });
          }
        } catch (rollbackError) {
          console.error('[TASK_MOVE] Rollback after move failure failed:', rollbackError);
        }
      });

      if (abort) {
        console.log(`[TASK_MOVE] Aborted stale move for task ${task.id.slice(0, 8)}`);
        return;
      }
      throw error;
    }
  } finally {
    // Clean up controller if this is still the active one for this task
    if (taskMoveControllers.get(input.taskId) === moveController) {
      taskMoveControllers.delete(input.taskId);
    }
  }
  };

  let moveSucceeded = false;
  try {
    await (logProjectName ? runWithProjectLogContext(logProjectName, runMove) : runMove());
    moveSucceeded = true;
  } finally {
    // Announce iff the DB write committed - NOT merely "iff the move succeeded".
    //
    // A failed move can still leave a committed change. The rollback skips the
    // revert entirely on the abort path (`!abort &&` in its guard), skips it
    // again when its CAS sees a concurrent move already relocated the task, and
    // is itself best-effort inside its own try/catch. Announcing only on the
    // success path would therefore reproduce the exact bug this whole change
    // exists to fix: a real board change that nobody is told about.
    //
    // Erring toward announcing is cheap. A redundant push coalesces into the
    // renderer's 250ms debounced board reload, the Monitor debounces too, and
    // phones already tolerate duplicate board events (the session-lifecycle
    // feed deliberately double-emits). A missing one is the bug.
    //
    // A `finally` does not swallow the rethrow, and the shutdown gate is
    // load-bearing rather than defensive: on that path the DB is already closed
    // and the window is going away, but sendToRenderer would still record a push.
    if (moveCommitted && announceProjectId && !isShuttingDown()) {
      // Every origin, including `renderer`. The subscribers here (paired phones
      // via the mobile bridge, and the Agent Monitor) are external to whoever
      // made the move, so a desktop drag has to reach them just as an agent's
      // move does. Sent as 'task-updated' rather than a new 'task-moved' kind
      // because read-board forwards `change` straight onto the wire, making a
      // new member a phone-visible protocol change for no gain.
      //
      // This is the SECOND bus emit for the move (the first fired at the commit
      // point inside Phase 1). It is not redundant: this one runs after the
      // rollback, so it is what tells a phone that a committed-then-failed
      // move went back. The renderer push fires here ONLY, since two of the
      // origin channels toast per push.
      //
      // The push is wrapped because this runs in a `finally`: a throwing
      // sendToRenderer would REPLACE whatever error runMove was already
      // propagating (the rollback tests assert the original surfaces) or turn
      // a clean move into a rejection. The bus emit fences itself the same way.
      emitBoardChanged();
      try {
        MOVE_PUSH_BY_ORIGIN[origin]?.(context, announceProjectId, input, movedTaskTitle);
      } catch (announceError) {
        console.error(`[TASK_MOVE] Announce failed for task ${input.taskId.slice(0, 8)}:`, announceError);
      }

      // PR linking is deliberately SUCCESS-only, unlike the two announcements
      // above. It used to live at the call sites, where it ran only once
      // `await handleTaskMove` had resolved, so the TIMING is unchanged; folding
      // it into the committed-but-failed case would newly fire gh queries for
      // moves that blew up after writing. Gated on a branch + non-To Do lane
      // inside the helper, and fire-and-forget so a slow query never blocks.
      //
      // The COVERAGE is not unchanged, and that is the one deliberate behavior
      // change in this block: only the renderer and plan-exit call sites ever
      // called this, so an agent's `move_task` and a phone's move never linked
      // a PR for the lane they landed in. Both do now, which means both can
      // spawn a `gh` query they previously did not. The helper's own lane and
      // anchor gates plus `linkPR`'s 60s per-task throttle are what keep a
      // scripted loop of agent moves from turning into a subprocess per move.
      if (moveSucceeded) {
        autoLinkPRForTask(context, input.taskId, announceProjectId);
      }
    }
  }
  } catch (error) {
    routeSettlement.reject?.(error);
    throw error;
  } finally {
    routeSettlement.resolve?.();
    if (routeDispatchId && routeDispatchCompletions.get(routeDispatchId)) {
      routeDispatchCompletions.delete(routeDispatchId);
    }
  }
}

export function registerTaskMoveHandlers(context: IpcContext): void {
  ipcMain.handle(IPC.TASK_MOVE, async (_, input, projectId?: string | null) => {
    try {
      // Prefer the renderer-stamped projectId (captured at drop time) over the
      // ambient current project, which can change if the user switches projects
      // during the FlyingCard flight. Resolve the matching projectPath too so
      // Phase 2/3 worktree + spawn work also targets the right project, not the
      // ambient one. handleTaskMove keeps the ambient fallback for main-process
      // internal callers that pass undefined.
      const { projectId: resolvedProjectId, projectPath: resolvedProjectPath } = resolveProjectContext(context, projectId);
      // 'renderer': the board already moved the card optimistically, so this is
      // the one origin that sends no push. It still reaches paired phones and
      // the Monitor via the unconditional board-changed emit inside the handler.
      return await handleTaskMove(context, input, 'renderer', resolvedProjectId, resolvedProjectPath);
    } catch (error) {
      // Shutdown closes the DB synchronously; any handler that crossed an
      // await boundary will throw "database connection is not open" or an
      // AbortError when it resumes. Swallow these to keep the shutdown log
      // clean - the user already quit and Phase 1's DB writes are committed.
      if (isShuttingDown()) return;
      throw error;
    }
  });

  // Queryable snapshot of in-flight spawn-progress labels (keyed by taskId).
  // syncSessions() reconciles its spawnProgress map against this so an HMR
  // reload during the brief "Starting agent..." window cannot strand a card.
  ipcMain.handle(IPC.TASK_GET_SPAWN_PROGRESS, () => getInFlightSpawnProgress());

  // Cancel an in-flight spawn (e.g. from the "still preparing" stall toast).
  // Fire-and-forget abort, OUTSIDE any lock - the move's holder observes the
  // signal and runs the existing AbortError rollback.
  ipcMain.handle(IPC.TASK_CANCEL_SPAWN, (_event, taskId: string) => {
    abortTaskMove(taskId);
  });
}
