import * as fs from 'fs';
import * as path from 'path';
import { app, BrowserWindow, ipcMain } from 'electron';
import { autoUpdater } from 'electron-updater';
import { IPC } from '../shared/ipc-channels';
import { trackEvent, sanitizeErrorMessage } from './analytics/analytics';
import { reportHandledError } from './analytics/error-reporting';
import { normalizeReleaseNotes } from './updater-release-notes';

const CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000; // 4 hours
const INITIAL_DELAY_MS = 5000; // 5 seconds after launch
const RETRY_DELAY_MS = 30_000; // 30 seconds before retry

let checkTimeout: ReturnType<typeof setTimeout> | null = null;
let checkInterval: ReturnType<typeof setInterval> | null = null;
let updaterWindow: BrowserWindow | null = null;
let checkRetrying = false;
let downloadRetrying = false;

/**
 * Path to the auto-updater manifest, generated by electron-builder when
 * `--publish` is set. On packaged builds it lives in the platform's resources
 * directory. Exported for testing.
 * @internal
 */
export function manifestPath(): string {
  return path.join(process.resourcesPath, 'app-update.yml');
}

/**
 * True when the auto-updater manifest is present at its expected location.
 * Exported for testing.
 * @internal
 */
export function manifestExists(): boolean {
  return fs.existsSync(manifestPath());
}

/**
 * Returns true if the error is a known-transient download/network failure
 * that should not surface as `app_error` telemetry. Structural failures
 * (signature mismatch, bad manifest, disk full, permission denied, 4xx
 * client errors) still propagate so real bugs stay visible.
 */
export function isTransientUpdaterError(error: Error): boolean {
  const errorCode = (error as NodeJS.ErrnoException).code;
  const errorMessage = error.message ?? '';

  if (errorCode === 'ECONNRESET' || errorCode === 'ETIMEDOUT'
      || errorCode === 'EAI_AGAIN' || errorCode === 'ENOTFOUND'
      || errorCode === 'ENETUNREACH' || errorCode === 'EPIPE') {
    return true;
  }

  if (errorCode && /^HTTP_ERROR_(5\d\d|408|429|618)$/.test(errorCode)) {
    return true;
  }

  if (/net::ERR_/.test(errorMessage)) return true;
  if (/Request has been aborted by the server/i.test(errorMessage)) return true;
  if (/Cannot pipe ".*":/i.test(errorMessage)) return true;

  return false;
}

/**
 * The two electron-updater wrappers that swallow a releases-feed fetch failure.
 * GitHubProvider rewraps twice: getLatestTagName produces
 * ERR_UPDATER_LATEST_VERSION_NOT_FOUND, and parseUpdateInfo then wraps that in
 * ERR_UPDATER_INVALID_RELEASE_FEED.
 */
const FEED_WRAPPER_CODES = new Set([
  'ERR_UPDATER_INVALID_RELEASE_FEED',
  'ERR_UPDATER_LATEST_VERSION_NOT_FOUND',
]);

/** The literal sentences those same two wrappers write into their message. */
const FEED_WRAPPER_PHRASES =
  /Cannot parse releases feed|Unable to find latest version on GitHub/;

/** Transient network shapes as they appear in NESTED stack text, not as a code. */
const TRANSIENT_CAUSE_PATTERNS = [
  /HttpError: (408|429|50\d)\b/,
  /\b(ECONNRESET|ETIMEDOUT|ENOTFOUND|EAI_AGAIN|ENETUNREACH|ECONNREFUSED)\b/,
];

/**
 * True when a releases-feed failure is a transient network blip wearing a
 * structural error's clothes.
 *
 * builder-util-runtime's newError() constructs a BRAND NEW Error and assigns
 * its own `code`, so electron-updater's double rewrap destroys the original
 * code: an HTTP 504 from the feed request arrives as
 * ERR_UPDATER_INVALID_RELEASE_FEED. That is why isTransientUpdaterError misses
 * these entirely - all six of its code branches test a code that no longer
 * exists, while its message branches still fire. The original failure survives
 * only as nested `e.stack` text inside the wrapper's message, so this reads the
 * message.
 *
 * Both halves must hold: the error is one of the two feed wrappers AND its text
 * carries a transient shape. A genuinely malformed feed has no transient shape
 * and stays loud, and a signature or checksum failure is not a feed wrapper at
 * all, so the structural cases stay reportable.
 *
 * The wrapper test accepts EITHER the code or the phrase. Requiring the code
 * would make this no-op in production if `code` is ever dropped between the
 * throw and the 'error' emit, while every unit test kept passing, since a test
 * sets `code` by hand. The phrase is written by the same wrapper that sets the
 * code, so it cannot drift away from it.
 *
 * Patterns are unanchored on purpose: the wrapper embeds the nested stack in
 * the MIDDLE of its own sentence, the same hazard BENIGN_RENDERER_ERRORS
 * documents for monaco.
 */
export function hasTransientNetworkCause(error: Error): boolean {
  const errorCode = (error as NodeJS.ErrnoException).code;
  const errorMessage = error.message ?? '';

  const isFeedWrapper =
    (errorCode !== undefined && FEED_WRAPPER_CODES.has(errorCode))
    || FEED_WRAPPER_PHRASES.test(errorMessage);
  if (!isFeedWrapper) return false;

  return TRANSIENT_CAUSE_PATTERNS.some((pattern) => pattern.test(errorMessage));
}

/**
 * The five values electron-updater can pass as the command name when it
 * elevates: the four LinuxUpdater.determineSudoCommand probes for on PATH,
 * plus the sudo fallback it returns when none is found.
 */
const ELEVATION_DENIED_PATTERN =
  /\bCommand (?:pkexec|gksudo|kdesudo|beesu|sudo) exited with code 12[67]\b/;

/**
 * True when a Linux install failed because the elevation prompt was denied,
 * rather than because the package manager itself failed.
 *
 * DebUpdater and RpmUpdater shell out to the system package manager through a
 * sudo front-end, and BaseUpdater.spawnSyncLog turns any non-zero exit into a
 * bare `Command <cmd> exited with code <n>` Error. That object carries no
 * `code` and no `cause`, so its message is the only thing there is to test.
 * That is also why this is a message pattern rather than a
 * UserConfigurationError subclass, against that class's own advice to extend
 * it instead: the throw site is third-party, so there is nothing to extend.
 *
 * Only 126 and 127 count, and pkexec(1) is what makes those two safe. It exits
 * 126 when the user dismissed the authentication dialog, and 127 when the user
 * is not authorized or authentication failed. Both mean the elevated command
 * never ran. When it does run, pkexec returns that program's own value, and
 * dpkg exits 1 or 2 while rpm exits 1, so a genuine install failure never
 * wears either code and stays reportable.
 *
 * Deliberate gap: sudo exits 1 on an authentication failure, and gksudo and
 * kdesudo exit 1 when cancelled, which is indistinguishable from a command
 * that ran and failed. Those declines are not suppressed. determineSudoCommand
 * resolves to pkexec on any current GNOME or KDE desktop, which is the case
 * that actually ships and the one this was written for.
 *
 * The pattern is unanchored for the reason benign-renderer-errors.ts
 * documents. Nothing is appended to this message today, so anchoring would
 * work, but the word boundaries survive an upstream reword that adds a prefix
 * or a suffix while still refusing to match `code 1267`.
 */
export function isElevationDeniedError(error: Error): boolean {
  return ELEVATION_DENIED_PATTERN.test(error.message ?? '');
}

/** @internal Exported for testing. */
export async function checkWithRetry(): Promise<void> {
  try {
    await autoUpdater.checkForUpdates();
  } catch {
    console.log('[UPDATER] Check failed, retrying in 30s...');
    checkRetrying = true;
    await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
    try {
      await autoUpdater.checkForUpdates();
    } catch (retryError) {
      console.error('[UPDATER] Check failed after retry:', retryError);
    } finally {
      checkRetrying = false;
    }
  }
}

/** @internal Exported for testing. */
export async function downloadWithRetry(): Promise<void> {
  try {
    await autoUpdater.downloadUpdate();
  } catch (firstError) {
    console.log('[UPDATER] Download failed, retrying in 30s:', firstError);
    downloadRetrying = true;
    try {
      await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
      await autoUpdater.downloadUpdate();
    } catch (retryError) {
      console.error('[UPDATER] Download failed after retry:', retryError);
    } finally {
      downloadRetrying = false;
    }
  }
}

/**
 * Registered on every path that bails out of updater init (dev, and a
 * packaged build with no update manifest). The renderer's updater surfaces
 * still exist on those paths, so without these `ipcRenderer.invoke` rejects
 * with `No handler registered` and surfaces as an unhandled rejection.
 */
function registerNoOpUpdaterHandlers(): void {
  ipcMain.handle(IPC.UPDATE_CHECK, () => {});
  ipcMain.handle(IPC.UPDATE_INSTALL, () => {});
}

/**
 * Initialize the auto-updater for packaged builds on every platform.
 *
 * Linux included: electron-updater ships DebUpdater / RpmUpdater alongside
 * AppImageUpdater, and its `autoUpdater` export selects between them by
 * reading the `package-type` marker electron-builder writes into
 * resourcesPath. Our fpm targets (deb, rpm) are both in electron-builder's
 * supportsAutoUpdate list, so each packaged Linux build already carries that
 * marker AND an app-update.yml, exactly like the NSIS and DMG builds.
 */
export function initUpdater(mainWindow: BrowserWindow): void {
  // Local Luuk builds are reviewed by the weekly upstream audit and must not
  // replace themselves with an unsigned/different upstream artifact. They also
  // use a prerelease version that GitHub's published-release feed cannot
  // resolve, which would otherwise emit an error on every launch.
  if (app.getVersion().includes('-luuk.')) {
    console.log(`[UPDATER] Disabled for local build ${app.getVersion()}.`);
    registerNoOpUpdaterHandlers();
    return;
  }
  if (!app.isPackaged) {
    // The renderer's release-notes modal reaches `installUpdate()` from its
    // primary button, and the Developer tab can open that modal with fixture
    // notes in dev. Register no-ops so the invoke resolves instead of
    // rejecting with `No handler registered` (an unhandled rejection).
    // Dev only now - a packaged Linux build takes the real path below.
    registerNoOpUpdaterHandlers();
    return;
  }

  updaterWindow = mainWindow;

  // electron-builder generates app-update.yml only when `--publish` is set,
  // so a misbuilt release (or a locally-packaged DMG/EXE without --publish)
  // can ship without it. Without this guard, electron-updater raises
  // ENOENT on every scheduled check and pollutes telemetry. Register
  // no-op IPC handlers so the renderer's "check for updates" UI does not
  // throw `No handler registered`, fire one telemetry event so we can
  // catch a recurrence in production, and bail before scheduling.
  if (!manifestExists()) {
    console.warn(`[UPDATER] Skipping init: ${manifestPath()} not found.`);
    registerNoOpUpdaterHandlers();
    trackEvent('app_error', {
      source: 'updater',
      message: 'missing_manifest',
    });
    return;
  }

  // We control the download -- don't auto-download on check
  autoUpdater.autoDownload = false;
  // Install pending updates silently when the user quits normally
  autoUpdater.autoInstallOnAppQuit = true;

  // Except on Linux, where "silently" is not available: DebUpdater and
  // RpmUpdater shell out to the system package manager, which always
  // elevates (LinuxUpdater.determineSudoCommand picks pkexec / gksudo /
  // kdesudo, falling back to sudo). On the quit path that surfaces a
  // password prompt as the window is disappearing, and the install races
  // the session teardown that is killing the process. Leave the update
  // staged instead: the release-notes modal's "Restart to update" is an
  // explicit, foreground moment where an auth prompt makes sense.
  // Upstream reached the same conclusion and made deferral the default for
  // these targets in a later major.
  if (process.platform === 'linux') {
    autoUpdater.autoInstallOnAppQuit = false;
  }

  // macOS differential download reads a cached update.zip from
  // ~/Library/Caches/<appId>-updater/pending/, which macOS evicts under
  // disk pressure. That race produces a bare `ENOENT: no such file or
  // directory, open '<path>'` error, historically our dominant updater
  // failure. Full redownload is an acceptable tradeoff for eliminating
  // the flakiness. See MacUpdater.js:88-103 for the cached-zip read
  // path we are bypassing.
  if (process.platform === 'darwin') {
    autoUpdater.disableDifferentialDownload = true;
  }

  // IPC handlers for renderer
  ipcMain.handle(IPC.UPDATE_CHECK, () => checkWithRetry());

  ipcMain.handle(IPC.UPDATE_INSTALL, () => {
    autoUpdater.quitAndInstall(true, true);
  });

  // When an update is available, start downloading immediately (with retry).
  autoUpdater.on('update-available', () => {
    console.log('[UPDATER] Update available, downloading...');
    void downloadWithRetry();
  });

  // When download completes, notify the renderer
  autoUpdater.on('update-downloaded', (info) => {
    console.log('[UPDATER] Update downloaded:', info.version);
    if (updaterWindow && !updaterWindow.isDestroyed()) {
      updaterWindow.webContents.send(IPC.UPDATE_DOWNLOADED, {
        version: info.version,
        releaseNotes: normalizeReleaseNotes(info.releaseNotes),
      });
    }
  });

  // Log errors but never surface to user. Skip analytics during retry to
  // avoid double-counting transient failures that resolve on second attempt.
  // Also filter known-transient failure classes so network blips and presigned
  // URL expiries do not pollute the app_error signal.
  autoUpdater.on('error', (error) => {
    console.error('[UPDATER] Error:', error);
    if (checkRetrying || downloadRetrying) return;
    if (isTransientUpdaterError(error)) {
      const errorCode = (error as NodeJS.ErrnoException).code;
      console.log('[UPDATER] Suppressing transient error telemetry:',
        errorCode ?? error.message.slice(0, 80));
      return;
    }
    trackEvent('app_error', {
      source: 'updater',
      message: sanitizeErrorMessage(error.message),
    });
    // A feed failure that is transient underneath its structural wrapper is
    // counted above but never filed as an issue: GitHub returned a 504 on a
    // routine check and the next check succeeds, so there is nothing to ship.
    //
    // This line's POSITION is load-bearing. Above trackEvent it would delete a
    // volume count that works today ("how often do update checks fail"), which
    // is the same split the missing-CLI exclusion makes inside
    // reportHandledError. Below the call it would do nothing at all.
    if (hasTransientNetworkCause(error)) {
      console.log('[UPDATER] Counting but not reporting a transient feed failure:',
        error.message.slice(0, 80));
      return;
    }
    // Same split, same reason, for the Linux install path: the user hit
    // "Restart to update" and then dismissed the polkit prompt. Counted, so
    // "how often is an update declined" stays answerable, but never filed,
    // because the user's own choice is not a defect we can ship a fix for.
    // This gate's position matters for exactly the reason above.
    if (isElevationDeniedError(error)) {
      console.log('[UPDATER] Counting but not reporting a denied elevation prompt:',
        error.message.slice(0, 80));
      return;
    }
    // Handled, so Sentry's global handlers never see it; forward the real
    // error so structural updater failures are diagnosable, not just counted.
    reportHandledError(error, { source: 'updater' });
  });

  // Schedule checks
  checkTimeout = setTimeout(() => {
    console.log('[UPDATER] Checking for updates...');
    checkWithRetry();

    checkInterval = setInterval(() => {
      console.log('[UPDATER] Checking for updates...');
      checkWithRetry();
    }, CHECK_INTERVAL_MS);
  }, INITIAL_DELAY_MS);
}

/**
 * Update the window reference used by the auto-updater. Called when macOS
 * recreates the window after all windows were closed (dock icon click).
 */
export function updateUpdaterWindow(mainWindow: BrowserWindow): void {
  updaterWindow = mainWindow;
}

/**
 * Synchronously clear updater timers. Called from syncShutdownCleanup().
 */
export function stopUpdaterTimers(): void {
  if (checkTimeout) {
    clearTimeout(checkTimeout);
    checkTimeout = null;
  }
  if (checkInterval) {
    clearInterval(checkInterval);
    checkInterval = null;
  }
}
