import path from 'node:path';
import simpleGit from 'simple-git';
import { IPC } from '../../../shared/ipc-channels';
import { TaskRepository } from '../../db/repositories/task-repository';
import { WorktreeManager, GitQueuePriority, type GitWaitProgress } from '../../git/worktree-manager';
import { prepareWorktreeFolder } from '../../git/task-worktree-folder';
import { isGitRepo, isAutoGeneratedBranch, hasCommits } from '../../git/git-checks';
import { fetchIfStale, type FetchFailureReason, type FetchIfStaleOutcome } from '../../git/fetch-throttle';
import { refResolvesLocally } from '../../git/base-branch';
import { runGitWithTimeout } from '../../git/git-spawn';
import { setSpawnStaleNote, beginSpawnStaleProbe, touchSpawnStaleProbe } from '../../transition-engine/spawn-progress';
import { isShuttingDown } from '../../shutdown-state';
import { AgentCliNotFoundError } from '../../agent/shared/agent-cli-not-found';
import { DEFAULT_AGENT, type Task, type WorktreeSkipReason } from '../../../shared/types';
import { getProjectRepos } from './project-repos';
import { resolveProjectDefaultBaseBranch } from './default-base-branch';
import { applyProfileToLane } from '../../transition-engine/column-strategy';
import { loadTaskProfile } from './task-profile';
import type { IpcContext } from '../ipc-context';

/**
 * Resolution of the agent that will run this task, for the worktree-skip
 * check. This MUST mirror `resolveTargetAgent`'s chain (task override ->
 * COLUMN PROFILE's rung for this column -> column override -> project default
 * -> global fallback), because skipping the worktree commits us to remote
 * execution: if this function and the spawn-time resolution disagree, a LOCAL
 * agent spawns with `cwd = projectPath` (transition-engine's
 * `task.worktree_path || projectPath` fallback) and runs unisolated in the
 * user's main checkout.
 *
 * The profile tier is why this is not just "read the lane": a task riding a
 * profile that re-points this column at a remote-execution agent must skip the
 * worktree here, exactly as the spawn will.
 *
 * The column layer is read from the task's CURRENT swimlane, which is the
 * destination lane at every call site (the move/create/promote/unarchive
 * flows all commit the row to the destination before the worktree phase).
 */
function resolveWorktreeCheckAgentName(task: Task, context: IpcContext, projectPath: string): string {
  if (task.agent_override) return task.agent_override;
  const project = context.projectRepo.list().find((candidate) => candidate.path === projectPath);
  if (project?.id && task.swimlane_id) {
    const { swimlanes } = getProjectRepos(context, project.id);
    const lane = applyProfileToLane(
      swimlanes.getById(task.swimlane_id),
      loadTaskProfile(context, task, projectPath),
    );
    if (lane?.agent_override) return lane.agent_override;
  }
  return project?.default_agent ?? DEFAULT_AGENT;
}

/**
 * Thrown when a branch checkout would change the working tree under another
 * task's live agent. Typed so the callers that deliberately do not fail the
 * whole operation (create, unarchive, promote) can still tell the user why no
 * agent started, instead of logging to a console nobody is reading.
 */
export class BranchCheckoutBlockedError extends Error {
  constructor(
    readonly directory: string,
    readonly blockingTaskId: string,
    readonly blockingTaskTitle: string | null,
    readonly blockerKind: 'task' | 'command-terminal' = 'task',
  ) {
    const blocker = blockerKind === 'command-terminal'
      ? 'a Command Terminal'
      : (blockingTaskTitle ? `"${blockingTaskTitle}"` : `task ${blockingTaskId.slice(0, 8)}`);
    const remedy = blockerKind === 'command-terminal'
      ? 'Close that terminal, or enable worktree mode so each task gets its own checkout.'
      : 'Stop that task, or enable worktree mode so each task gets its own checkout.';
    super(`Cannot switch branches in ${directory}: ${blocker} is already running an agent there. ${remedy}`);
    this.name = 'BranchCheckoutBlockedError';
  }
}

/** True when two paths denote the same directory, comparing the way the platform does. */
function isSameDirectory(first: string, second: string): boolean {
  try {
    return path.relative(path.resolve(first), path.resolve(second)) === '';
  } catch {
    return false;
  }
}

/**
 * The live (running or queued) session whose cwd is `directory`, if any.
 * Cwd-keyed, never task-row-keyed: the cwd is where an agent actually is, and
 * sessions that no task row points at (a `run_script` action's `<id>-script`
 * session, a recovery spawn whose `task.session_id` write has not landed yet,
 * a Command Terminal) are exactly the occupants a row-keyed check misses.
 * `excludeTaskId` is for the checkout guard, which must not be blocked by the
 * task's own session; occupancy checks that protect a mutation of the task's
 * OWN tree pass no exclusion so any live occupant blocks.
 */
export function findLiveSessionInDirectory(
  context: IpcContext,
  directory: string,
  options?: { excludeTaskId?: string },
): { taskId: string; transient?: boolean } | undefined {
  return context.sessionManager.listSessions().find((session) =>
    (options?.excludeTaskId === undefined || session.taskId !== options.excludeTaskId)
    && (session.status === 'running' || session.status === 'queued')
    && Boolean(session.cwd)
    && isSameDirectory(session.cwd, directory));
}

/**
 * Refuse to touch a working directory that another task's agent is live in.
 *
 * Keyed on `Session.cwd`, not on `task.worktree_path`: the cwd is where the
 * agent actually is, whereas re-reading the task row is an indirection that can
 * disagree with reality. Queued sessions count, because the session manager
 * stamps `cwd` on the queued placeholder before the PTY exists.
 *
 * A Command Terminal counts too, deliberately. It spawns a real agent with
 * `cwd = projectRoot` (`handlers/transient-sessions.ts`), so checking out under
 * it changes files under a live agent exactly as a task would. The previous
 * guard missed this because it resolved each session's `taskId` to a task row
 * and a transient id resolves to nothing, so it silently skipped them.
 */
function assertNoOtherAgentInDirectory(
  context: IpcContext,
  taskId: string,
  directory: string,
): void {
  const occupant = findLiveSessionInDirectory(context, directory, { excludeTaskId: taskId });
  if (!occupant) return;

  if (occupant.transient) {
    throw new BranchCheckoutBlockedError(directory, occupant.taskId, null, 'command-terminal');
  }

  let blockingTitle: string | null = null;
  try {
    blockingTitle = getProjectRepos(context).tasks.getById(occupant.taskId)?.title ?? null;
  } catch {
    // Naming the blocker is a nicety; never let it turn into the failure.
  }
  throw new BranchCheckoutBlockedError(directory, occupant.taskId, blockingTitle);
}

/**
 * The step that failed before a born-into-a-column task could spawn. The first
 * two are git; `agent` is the spawn step itself (the CLI was missing, or the
 * engine threw), which used to only log.
 */
export type SpawnFailureStep = 'worktree' | 'checkout' | 'agent';

/**
 * Deliberately the same wording the drag path already toasts
 * (`Worktree setup failed: ...` in handlers/task-move.ts), so the same
 * underlying git failure reads identically whether the task was dragged in or
 * born into the column.
 */
const SPAWN_FAILURE_STEP_LABEL: Record<SpawnFailureStep, string> = {
  worktree: 'Worktree setup failed',
  checkout: 'Branch checkout failed',
  agent: 'Agent did not start',
};

/**
 * Shorten to at most `limit` characters, preferring to end on a complete
 * SENTENCE and falling back to a word boundary.
 *
 * A blind slice mangles the two shapes git errors actually take here.
 * `describeUnresolvableBase` ends in a branch LIST, so the cut lands inside it:
 * a hard slice half-prints a branch name (reads as a corrupt name), and a
 * word-boundary cut leaves the dangling label "Branches found:..." which
 * promises a list and then shows nothing. Ending at the previous sentence drops
 * the list cleanly and keeps the remediation sentence whole, which is the part
 * the user acts on. An opaque one-sentence error has no period to fall back to,
 * so that keeps the word-boundary cut plus an ellipsis.
 */
function shortenForNotice(text: string, limit: number): string {
  if (text.length <= limit) return text;
  const hardCut = text.slice(0, limit);

  // A sentence end late enough to still carry the substance.
  const lastSentenceEnd = Math.max(hardCut.lastIndexOf('. '), hardCut.lastIndexOf('? '), hardCut.lastIndexOf('! '));
  if (lastSentenceEnd > limit * 0.5) return hardCut.slice(0, lastSentenceEnd + 1);

  const lastSpace = hardCut.lastIndexOf(' ');
  const cut = lastSpace > limit * 0.6 ? hardCut.slice(0, lastSpace) : hardCut;
  return `${cut.trimEnd()}...`;
}

/**
 * User-facing summary of why a spawn did not happen.
 *
 * `BranchCheckoutBlockedError` keeps its own message verbatim - it is written
 * for a user and names both the blocker and the remedy. Anything else is the
 * step that failed plus the error's FIRST line, capped: raw git errors run to
 * several lines and would swamp a toast.
 *
 * The step label is dropped when the error already opens by naming that step
 * (`describeUnresolvableBase` starts "Cannot create worktree: ..."), which would
 * otherwise read "Worktree setup failed: Cannot create worktree: ...". Prefixing
 * is for the OPAQUE errors - a bare `EBUSY` or `fatal: ...` says nothing about
 * which step produced it.
 */
function describeSpawnFailure(step: SpawnFailureStep, error: unknown): string {
  if (error instanceof BranchCheckoutBlockedError) return error.message;
  // Same contract: a typed spawn failure already words itself for the user and
  // carries its own remedy (here, the pointer to the CLI path override), so the
  // step label would only prefix a sentence that reads fine on its own.
  if (error instanceof AgentCliNotFoundError) return error.message;

  const maxDetailLength = 200;
  const rawMessage = error instanceof Error ? error.message : String(error);
  const firstLine = (rawMessage.split('\n')[0] ?? '').trim();
  if (!firstLine) return `${SPAWN_FAILURE_STEP_LABEL[step]}.`;
  const detail = shortenForNotice(firstLine, maxDetailLength);
  if (/^cannot (create|check ?out)\b/i.test(detail)) return detail;
  return `${SPAWN_FAILURE_STEP_LABEL[step]}: ${detail}`;
}

/**
 * Tell the user their task was created but its agent did not start.
 *
 * The create / promote / unarchive / MCP-auto-spawn paths deliberately do not
 * fail the whole operation when a git step fails: the task really was created.
 * But "created and silently not spawned" is indistinguishable from "created and
 * spawned", so a console line is not good enough.
 *
 * Every worktree and checkout failure notifies, not only the actionable ones.
 * This used to narrow to `BranchCheckoutBlockedError`, reasoning that an
 * arbitrary git failure has no user-actionable message. What that actually did
 * was leave the WORKTREE stage silent at all five call sites - which is how
 * task #538 left a healthy-looking card (null session, null worktree) after
 * `git worktree add` refused a branch already checked out elsewhere. A vague
 * notice beats a card that lies, and raw git text reaching a user is already
 * precedent: the drag path's toast says `Worktree setup failed: <raw git error>`.
 *
 * Scope is those two git steps PLUS the spawn step itself (`'agent'`). The
 * spawn step used to only log, which kept the #538 symptom for the case that
 * causes it most often in practice: an agent CLI that is not installed or not
 * on PATH. It is notified unconditionally rather than only for
 * AgentCliNotFoundError - describeSpawnFailure already words an opaque error
 * sensibly, so narrowing would mean adding a condition whose only effect is to
 * keep a known defect for every other spawn failure.
 *
 * For the two GIT steps, a task MOVE deliberately does not call this - it
 * rejects the in-flight invoke instead, which the renderer already toasts (see
 * handlers/task-move.ts). The `'agent'` step is different: a move reaches the
 * spawn through the shared `spawnAgent` helper, whose catch swallows the error
 * and returns rather than rethrowing, so the move's invoke RESOLVES and no
 * rejection toast fires. That notify is therefore the only user-visible notice
 * on a drag-move spawn failure, and it is already uniform across every
 * `spawnAgent` entry point. Do not add a second one in handlers/task-move.ts.
 */
export function notifySpawnBlocked(
  context: IpcContext,
  task: Task,
  step: SpawnFailureStep,
  error: unknown,
  projectId?: string | null,
): void {
  // A quit that closes the DB or kills git mid-step surfaces here as an ordinary
  // failure. While this only forwarded `BranchCheckoutBlockedError` that could
  // never happen; now that every error notifies, shutdown artifacts would toast
  // on the way out ("Worktree setup failed: The database connection is not
  // open"). `handleTaskMove` already bails this way on its own failure paths,
  // and the window is not reliably destroyed before the DB closes.
  if (isShuttingDown()) return;
  if (!context.mainWindow || context.mainWindow.isDestroyed()) return;
  context.mainWindow.webContents.send(
    IPC.TASK_SPAWN_BLOCKED,
    task.id,
    task.title,
    describeSpawnFailure(step, error),
    projectId ?? context.currentProjectId ?? undefined,
  );
}

/**
 * One warning toast per project per reason class per minute. The sticky
 * spawn-progress note is per-task (every affected card carries its own), so
 * the toast is only the attention-getter - a bulk unarchive while offline must
 * not stack N copies of the same news.
 */
const spawnWarningCooldowns = new Map<string, number>();
const SPAWN_WARNING_COOLDOWN_MS = 60_000;

/** Test-only: reset the warning cooldown map between unit test cases. */
export function __resetSpawnWarningCooldownsForTest(): void {
  spawnWarningCooldowns.clear();
}

/**
 * Tell the user a spawn is proceeding from a possibly-stale base. Unlike
 * notifySpawnBlocked, the agent DID (or will) start; the renderer toasts
 * `message` verbatim, with no "did not start its agent" framing of its own.
 */
export function notifySpawnWarning(
  context: IpcContext,
  task: Task,
  message: string,
  projectId: string | null | undefined,
  cooldownKey: string,
): void {
  if (isShuttingDown()) return;
  if (!context.mainWindow || context.mainWindow.isDestroyed()) return;
  const resolvedProjectId = projectId ?? context.currentProjectId ?? undefined;
  const key = `${resolvedProjectId ?? 'ambient'}:${cooldownKey}`;
  const lastSent = spawnWarningCooldowns.get(key);
  // Explicit undefined check: a truthiness test would treat a cooldown
  // stamped at epoch 0 (mocked clocks in tests) as absent.
  if (lastSent !== undefined && Date.now() - lastSent < SPAWN_WARNING_COOLDOWN_MS) return;
  spawnWarningCooldowns.set(key, Date.now());
  context.mainWindow.webContents.send(
    IPC.TASK_SPAWN_WARNING,
    task.id,
    message,
    resolvedProjectId,
  );
}

/** User-facing phrase per toast-worthy failure class. */
const FETCH_FAILURE_PHRASES: Partial<Record<FetchFailureReason, string>> = {
  timeout: 'fetch timed out',
  auth: 'authentication failed',
  network: 'network unreachable',
};

/**
 * Build the fetchIfStale outcome observer for a spawn path fetching
 * `baseBranch`. A surfaced failure (timeout / auth / network / other) pins a
 * sticky note on the task's remaining spawn-progress labels; the
 * network/credential classes additionally toast, cooldown-guarded. The silent
 * classes are deliberate: a throttle skip is not a failure, an abort is the
 * user cancelling, and a repo with no remote (or a base that exists only
 * locally) was always going to start from the local ref. 'other' notes but
 * never toasts - unknown git stderr is not necessarily network or credentials.
 */
function makeBaseFetchOutcomeHandler(
  context: IpcContext,
  task: Task,
  baseBranch: string,
  projectId: string | null | undefined,
  probeGeneration?: number,
): (outcome: FetchIfStaleOutcome) => void {
  return (outcome) => {
    if (outcome.kind !== 'failed') return;
    const { reason } = outcome;
    if (reason === 'abort' || reason === 'no-remote' || reason === 'branch-missing') return;
    setSpawnStaleNote(context.mainWindow, task.id, 'base fetch failed', probeGeneration);
    const phrase = FETCH_FAILURE_PHRASES[reason];
    if (!phrase) return;
    notifySpawnWarning(
      context,
      task,
      `"${task.title}": could not fetch latest '${baseBranch}' from origin (${phrase}). Starting from the last fetched state.`,
      projectId,
      reason,
    );
  };
}

/**
 * The task's effective base branch - both the branch a spawn measures
 * freshness against AND the actual ref git mutations act on (the start point
 * a custom-branch cut is created from, and the ref TASK_UPDATE_FROM_BASE
 * fetches and fast-forwards the worktree to). Resolution: the task's own
 * base, else the project default chain in `resolveProjectDefaultBaseBranch`
 * (board default for THIS project's path, effective config default, 'main').
 */
export function resolveEffectiveBaseBranch(context: IpcContext, task: Task, projectPath: string): string {
  return task.base_branch || resolveProjectDefaultBaseBranch(context, projectPath);
}

/**
 * Persist why this spawn runs without a worktree, and mirror it onto the
 * in-memory task the caller keeps using. The setter does not bump
 * `updated_at`: the decision is spawn telemetry, not a user edit.
 */
function recordWorktreeSkip(task: Task, tasks: TaskRepository, reason: WorktreeSkipReason | null): void {
  if ((task.worktree_skip_reason ?? null) === reason) return;
  tasks.setWorktreeSkipReason(task.id, reason);
  task.worktree_skip_reason = reason;
}

/**
 * Create a worktree for a task if needed and update the DB + task object in place.
 * Creates nothing when worktrees are disabled, the project isn't a git repo, the repo has no
 * commits yet (unborn HEAD), or the resolved agent's execution mode for this project is 'remote'
 * (the agent runs against a server-side directory instead - see `agent.execution` in AppConfig
 * and `ResolvedExecutionTarget`). In every one of those cases `task.worktree_path` stays null so
 * `cwd` falls back to the project path (per transition-engine.ts), and the REASON is written to
 * `task.worktree_skip_reason` so the board can say the agent is in the shared checkout, and why.
 * Throws on worktree creation failure (e.g. duplicate branch, or an unresolvable base branch).
 */
export async function ensureTaskWorktree(
  context: IpcContext,
  task: Task,
  tasks: TaskRepository,
  projectPath?: string | null,
  options?: { signal?: AbortSignal; onProgress?: (phase: string) => void; onWaitProgress?: (info: GitWaitProgress) => void; projectId?: string | null },
): Promise<void> {
  options?.signal?.throwIfAborted();
  const resolvedProjectPath = projectPath ?? context.currentProjectPath;
  if (!resolvedProjectPath) return;
  const config = context.configManager.getEffectiveConfig(resolvedProjectPath);
  const agentName = resolveWorktreeCheckAgentName(task, context, resolvedProjectPath);
  if (config.agent.execution[agentName]?.mode === 'remote') {
    recordWorktreeSkip(task, tasks, 'remote-agent');
    return;
  }
  // No-commits and base-branch-resolution guards live inside
  // WorktreeManager.ensureWorktree (via resolveWorktreeBase) so every caller - this one, MCP
  // auto-spawn, the branch-switch handler - gets identical behavior.
  // A task that predates the numeric folder scheme and has already been through
  // Done has no worktree_path left to remember where it lived. Recover that from
  // its session history BEFORE creating, so it returns to its original path
  // instead of being relocated. See TaskRepository.recoverLegacyWorktreeFolder.
  prepareWorktreeFolder(task, tasks, resolvedProjectPath);
  const effectiveBaseBranch = resolveEffectiveBaseBranch(context, task, resolvedProjectPath);
  const worktreeManager = new WorktreeManager(resolvedProjectPath);
  const result = await worktreeManager.withLock(
    () => worktreeManager.ensureWorktree(task, config.git, {
      onProgress: options?.onProgress,
      signal: options?.signal,
      onFetchOutcome: makeBaseFetchOutcomeHandler(context, task, effectiveBaseBranch, options?.projectId),
    }),
    { label: `create-worktree:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress },
  );
  // A mocked manager can resolve nothing at all; the real one always returns a
  // create result or a skip.
  if (!result) return;
  if ('skipped' in result) {
    if (result.reason !== 'reused') {
      recordWorktreeSkip(task, tasks, result.reason);
      return;
    }
    // The spawn is REUSING a pre-existing worktree. That tree was cut from
    // whatever the base was at its creation and nothing may silently rebase it,
    // so surface drift instead: fire-and-forget, throttled fetch, one rev-list,
    // never blocking or failing the spawn. The probe token is captured
    // SYNCHRONOUSLY, while this spawn is provably the live one, so a note
    // resolving during the reuse path's label-less window can pend onto the
    // upcoming 'starting-agent' push instead of being dropped. A stale skip
    // reason cannot survive here either: the task demonstrably has a worktree.
    recordWorktreeSkip(task, tasks, null);
    const probeGeneration = beginSpawnStaleProbe(task.id);
    void surfaceWorktreeBaseDrift(context, task, resolvedProjectPath, options?.signal, options?.projectId, probeGeneration);
    return;
  }
  tasks.recordWorktree(task.id, result.worktreePath, result.branchName, result.worktreeFolder, result.baseBranch);
  Object.assign(task, tasks.getById(task.id));
}

/**
 * Best-effort "your base moved on without this tree" signal for a spawn that
 * reused an existing worktree. Fetches the effective base (throttled), then
 * counts how far the worktree's HEAD is behind `origin/<base>`; a nonzero
 * count pins a note on the task's remaining spawn-progress labels (e.g.
 * "Starting agent... (base 3 behind)"). Deliberately async off the spawn path:
 * the caller never awaits it, so the spawn is not delayed, while a note
 * landing mid-spawn still reaches the card, and one that resolves after the
 * spawn cleared no-ops in setSpawnStaleNote. The git work itself still runs
 * INSIDE the per-project git queue (background priority, so it never delays a
 * user-initiated op): its fetch writes refs/remotes and FETCH_HEAD in the
 * shared `.git`, and its rev-list child holds the worktree directory as its
 * cwd, so running it unqueued would race a concurrent locked fetch/checkout
 * and could pin the worktree directory against a Windows delete.
 * Never throws - surfacing must not affect the spawn.
 */
async function surfaceWorktreeBaseDrift(
  context: IpcContext,
  task: Task,
  projectPath: string,
  signal: AbortSignal | undefined,
  projectId: string | null | undefined,
  probeGeneration: number,
): Promise<void> {
  try {
    await WorktreeManager.withGitLock(projectPath, async () => {
      // The queue wait can outlast the probe horizon; re-touch the generation
      // baseline now that the probe is actually running (see spawn-progress).
      touchSpawnStaleProbe(task.id);
      const baseBranch = resolveEffectiveBaseBranch(context, task, projectPath);
      await fetchIfStale(simpleGit(projectPath), projectPath, baseBranch, {
        signal,
        onOutcome: makeBaseFetchOutcomeHandler(context, task, baseBranch, projectId, probeGeneration),
      });
      // Compare against the tracking ref whenever it resolves - whether this
      // call fetched, a fetch landed within the throttle window, or the fetch
      // failed but an older ref exists (still evidence of drift, if stale).
      const baseRef = `origin/${baseBranch}`;
      if (!(await refResolvesLocally(projectPath, baseRef))) return;
      const { stdout } = await runGitWithTimeout(
        task.worktree_path!,
        ['rev-list', '--left-right', '--count', `${baseRef}...HEAD`],
        { timeoutMs: 5_000, signal },
      );
      const [behindRaw] = stdout.trim().split(/\s+/);
      const behind = Number.parseInt(behindRaw, 10) || 0;
      if (behind > 0) {
        setSpawnStaleNote(context.mainWindow, task.id, `base ${behind} behind`, probeGeneration);
      }
    }, { priority: GitQueuePriority.BACKGROUND, label: `drift-probe:${task.id.slice(0, 8)}` });
  } catch {
    // Best-effort surfacing; a probe failure must never surface as a spawn failure.
  }
}

/**
 * Checkout the task's branch in the main repo for non-worktree tasks.
 *
 * Custom branch names (not matching the auto-generated pattern) are fetched
 * from origin, created from the fetched effective base or remote if needed,
 * then checked out and fast-forwarded from origin when strictly behind.
 * Auto-generated branches fall through to the base_branch checkout path, which
 * fetches the base and fast-forwards it the same way (the non-worktree
 * counterpart of createWorktree cutting from origin/<base>). Both
 * fast-forwards are non-fatal: local-only commits and divergence keep local
 * state, and a genuine fetch failure surfaces via the spawn-progress note and
 * the cooldown-guarded spawn warning instead of silently starting stale.
 *
 * No-ops when: no project path, task uses a worktree, not a git repo,
 * or task has neither a custom branch_name nor a base_branch.
 * Throws on dirty repo or checkout failure so the caller can block agent spawn.
 *
 * Also throws `BranchCheckoutBlockedError` when another task already has a live
 * agent in the directory about to be checked out. That check lives HERE, beside
 * the checkout it protects, rather than in a caller: it used to sit in
 * `task-move.ts` keyed on `task.base_branch`, while the decision to check out is
 * keyed on `usesCustomBranch || base_branch`. A task with a custom branch and no
 * base branch therefore checked out with the guard never running, changing the
 * working tree under someone else's agent. Co-locating them makes that class of
 * drift impossible.
 */
export async function ensureTaskBranchCheckout(
  context: IpcContext,
  task: Task,
  projectPath?: string | null,
  options?: { signal?: AbortSignal; onProgress?: (phase: string) => void; onWaitProgress?: (info: GitWaitProgress) => void; projectId?: string | null },
): Promise<void> {
  options?.signal?.throwIfAborted();
  if (!projectPath) return;
  if (task.worktree_path) return;
  if (!isGitRepo(projectPath)) return;

  const usesCustomBranch = Boolean(
    task.branch_name && !isAutoGeneratedBranch(task.branch_name, task.id, task.title),
  );
  // Nothing to check out either way, so stop before touching git at all.
  if (!usesCustomBranch && !task.base_branch) return;
  // Same unborn-HEAD case WorktreeManager.ensureWorktree guards for the worktree path: with no
  // commits there is no branch to fetch, create, or check out, and every git call below would
  // fail on the ref. Deliberately AFTER the cheap guards - it shells out, and the common move
  // has no branch work to do.
  if (!(await hasCommits(projectPath))) return;

  // Custom branch name: fetch latest, create if needed, then checkout
  if (usesCustomBranch) {
    await WorktreeManager.withGitLock(projectPath, async () => {
      // Inside the per-project git queue, so the probe and the checkout are
      // atomic against every other checkout on this project. That is why no new
      // directory-scoped lock is needed: a third lock ordering alongside
      // withTaskLock (per-task, deliberately parallel across tasks) and
      // projectQueues would be a deadlock surface.
      assertNoOtherAgentInDirectory(context, task.id, projectPath);
      const git = simpleGit(projectPath);

      // Emit 'fetching' once the job actually starts (after any queue wait) so
      // the card flips from the "Waiting..." label to "Fetching latest...".
      options?.onProgress?.('fetching');
      // Fetch latest from origin (throttled to avoid redundant network I/O)
      const fetchedBranch = await fetchIfStale(git, projectPath, task.branch_name!, {
        signal: options?.signal,
        onOutcome: makeBaseFetchOutcomeHandler(context, task, task.branch_name!, options?.projectId),
      });
      options?.onProgress?.('switching-branch');
      options?.signal?.throwIfAborted();
      // Re-assert after the fetch: the assert above is point-in-time, and a
      // session that never enters the git queue (a resume, a base-less task's
      // spawn, a Command Terminal) can have started here during the fetch's
      // timeout budget. The scan is synchronous and in-memory, so re-running
      // it right before the mutation closes the window for free.
      assertNoOtherAgentInDirectory(context, task.id, projectPath);

      // Check if branch exists locally (user's local may be ahead of remote, that's fine)
      let branchExists = false;
      try {
        await git.raw(['rev-parse', '--verify', task.branch_name!]);
        branchExists = true;
      } catch {
        // Branch does not exist locally
      }

      if (!branchExists) {
        // Check if it exists on remote (we already fetched above)
        let existsOnRemote = false;
        try {
          await git.raw(['rev-parse', '--verify', `origin/${task.branch_name}`]);
          existsOnRemote = true;
        } catch {
          // Not on remote either
        }

        if (existsOnRemote) {
          // Create local branch tracking the remote
          await git.raw(['branch', task.branch_name!, `origin/${task.branch_name}`]);
        } else {
          // Branch doesn't exist anywhere. Create from the effective base -
          // fetched first, so the cut starts from origin's tip rather than a
          // stale local ref, matching createWorktree. The re-verify mirrors
          // createWorktree's: fetchIfStale's return is not proof the tracking
          // ref landed (a throttle hit skips the fetch entirely, and a fetch
          // can exit 0 without populating refs/remotes/origin/).
          const baseBranch = resolveEffectiveBaseBranch(context, task, projectPath);
          const fetchedBase = baseBranch === task.branch_name
            ? fetchedBranch
            : await fetchIfStale(git, projectPath, baseBranch, {
                signal: options?.signal,
                onOutcome: makeBaseFetchOutcomeHandler(context, task, baseBranch, options?.projectId),
              });
          const startPoint = fetchedBase === `origin/${baseBranch}` && await refResolvesLocally(projectPath, fetchedBase)
            ? fetchedBase
            : baseBranch;
          await git.raw(['branch', task.branch_name!, startPoint]);
        }
      }

      const worktreeManager = new WorktreeManager(projectPath);
      await worktreeManager.checkoutBranch(task.branch_name!);

      // A pre-existing local branch may be strictly behind its remote (a
      // teammate pushed to the shared feature branch). Fast-forward it from the
      // ref the fetch above landed, exactly as the Command Terminal spawn does
      // for its target branch. Non-fatal: a local-ahead or diverged branch
      // legitimately stays where it is. A just-created branch needs no ff - it
      // was cut from origin's tip a moment ago.
      if (branchExists && fetchedBranch === `origin/${task.branch_name}` && await refResolvesLocally(projectPath, fetchedBranch)) {
        try {
          await git.raw(['merge', '--ff-only', fetchedBranch]);
        } catch {
          // Local ahead or diverged: keep local state.
        }
      }
    }, { label: `checkout-branch:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress });
    return;
  }

  // Fall through to existing base_branch checkout logic. `usesCustomBranch` being false
  // already guarantees a base_branch above; this narrows it for TypeScript.
  if (!task.base_branch) return;

  const worktreeManager = new WorktreeManager(projectPath);
  await worktreeManager.withLock(async () => {
    assertNoOtherAgentInDirectory(context, task.id, projectPath);
    const git = simpleGit(projectPath);
    // Emit 'fetching' once the job actually starts (after any queue wait) so
    // the card flips from the "Waiting..." label to "Fetching latest...".
    options?.onProgress?.('fetching');
    const fetched = await fetchIfStale(git, projectPath, task.base_branch!, {
      signal: options?.signal,
      onOutcome: makeBaseFetchOutcomeHandler(context, task, task.base_branch!, options?.projectId),
    });
    options?.onProgress?.('switching-branch');
    options?.signal?.throwIfAborted();
    // Same point-in-time re-assert as the custom-branch path above: the new
    // ff-merge below rewrites files even when the checkout itself is a no-op
    // (already on the base), so the pre-fetch assert alone no longer covers
    // every mutating outcome of this block.
    assertNoOtherAgentInDirectory(context, task.id, projectPath);
    await worktreeManager.checkoutBranch(task.base_branch!);
    // Fast-forward only when the fetch verifiably landed the tracking ref
    // (fetchIfStale's return is not proof: a throttle hit skips the fetch, and
    // a fetch can exit 0 without populating refs/remotes/origin/). Non-fatal:
    // local-only commits on the base are legitimate (an admin who just ran
    // /merge-back), and a dirty tree already threw inside checkoutBranch.
    if (fetched === `origin/${task.base_branch}` && await refResolvesLocally(projectPath, fetched)) {
      try {
        await git.raw(['merge', '--ff-only', fetched]);
      } catch {
        // Local ahead or diverged: keep local state.
      }
    }
  }, { label: `checkout-branch:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress });
}
