/**
 * Unit tests for command-builder logic, slugify, shell adaptation,
 * status-bridge script, merged settings, and shell detection.
 *
 * Migrated from tests/e2e/command-builder.spec.ts -- pure logic, no Electron needed.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { execFileSync, execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {
  quoteArg,
  isCmdShell,
  isPowerShellShell,
  adaptCommandForShell,
  convertWindowsExePath,
  sanitizeForPty,
  isUncPath,
  toGitBashPath,
  toWslPath,
} from '../../src/shared/paths';
import { interpolateTemplate } from '../../src/main/agent/shared';
import { CommandBuilder } from '../../src/main/agent/adapters/claude';
import { slugify } from '../../src/shared/slugify';
import { isAutoGeneratedBranch } from '../../src/main/git/git-checks';

// ── Inline test-only helper (deliberately simplified, omits merged settings / hooks) ──

function buildClaudeCommand(options: {
  cliPath: string;
  prompt?: string;
  sessionId?: string;
  resume?: boolean;
  permissionMode?: string;
}): string {
  const parts = [quoteArg(options.cliPath)];

  // Permission mode (e.g., 'plan')
  if (options.permissionMode && options.permissionMode !== 'default') {
    parts.push('--permission-mode', options.permissionMode);
  }

  if (options.sessionId) {
    const flag = options.resume ? '--resume' : '--session-id';
    parts.push(flag, quoteArg(options.sessionId));
  }

  if (options.prompt) {
    const safePrompt = options.prompt.replace(/"/g, "'");
    parts.push('--', quoteArg(safePrompt));
  }

  return parts.join(' ');
}

// ── Shell detection (test infrastructure -- not a production duplicate) ──────

interface ShellInfo {
  name: string;
  path: string;
}

function detectAvailableShells(): ShellInfo[] {
  const shells: ShellInfo[] = [];
  const isWin = process.platform === 'win32';
  const isMac = process.platform === 'darwin';

  const candidates: Array<{ name: string; cmd: string }> = [];

  if (isWin) {
    candidates.push(
      { name: 'PowerShell 7', cmd: 'pwsh' },
      { name: 'PowerShell 5', cmd: 'powershell' },
      { name: 'Git Bash', cmd: 'bash' },
      { name: 'Command Prompt', cmd: 'cmd' },
    );
    try {
      const wslOutput = execSync('wsl --list --quiet', { encoding: 'utf-8', timeout: 5000 });
      const distros = wslOutput
        .split('\n')
        .map((l) => l.replace(/\0/g, '').trim())
        .filter((d) => d && !d.toLowerCase().startsWith('docker-'));
      for (const distro of distros) {
        shells.push({ name: `WSL: ${distro}`, path: `wsl -d ${distro}` });
      }
    } catch {
      // WSL not available
    }
  } else if (isMac) {
    candidates.push(
      { name: 'zsh', cmd: 'zsh' },
      { name: 'bash', cmd: 'bash' },
      { name: 'fish', cmd: 'fish' },
      { name: 'sh', cmd: 'sh' },
      { name: 'nushell', cmd: 'nu' },
    );
  } else {
    candidates.push(
      { name: 'bash', cmd: 'bash' },
      { name: 'zsh', cmd: 'zsh' },
      { name: 'fish', cmd: 'fish' },
      { name: 'sh', cmd: 'sh' },
      { name: 'dash', cmd: 'dash' },
      { name: 'nushell', cmd: 'nu' },
      { name: 'ksh', cmd: 'ksh' },
    );
  }

  for (const c of candidates) {
    try {
      const resolved = execSync(
        isWin ? `where ${c.cmd}` : `which ${c.cmd}`,
        { encoding: 'utf-8', timeout: 5000, stdio: ['pipe', 'pipe', 'ignore'] },
      ).trim().split('\n')[0].trim();
      if (resolved) {
        shells.push({ name: c.name, path: resolved });
      }
    } catch {
      // Not found
    }
  }

  return shells;
}

// ── Tests ───────────────────────────────────────────────────────────────────

describe('sanitizeForPty', () => {
  it('strips newlines', () => {
    expect(sanitizeForPty('hello\nworld')).toBe('hello world');
  });

  it('strips \\r\\n (Windows line endings)', () => {
    expect(sanitizeForPty('line1\r\nline2')).toBe('line1 line2');
  });

  it('strips standalone \\r', () => {
    expect(sanitizeForPty('old\rmac')).toBe('old mac');
  });

  it('strips tabs', () => {
    expect(sanitizeForPty('col1\tcol2')).toBe('col1 col2');
  });

  it('collapses multiple newlines into single space', () => {
    expect(sanitizeForPty('a\n\n\nb')).toBe('a b');
  });

  it('collapses mixed whitespace', () => {
    expect(sanitizeForPty('a\n\t\r\n  b')).toBe('a b');
  });

  it('trims leading/trailing whitespace', () => {
    expect(sanitizeForPty('\n  hello  \n')).toBe('hello');
  });

  it('returns empty string for whitespace-only input', () => {
    expect(sanitizeForPty('\n\r\n\t  ')).toBe('');
  });

  it('passes through clean text unchanged', () => {
    expect(sanitizeForPty('simple text')).toBe('simple text');
  });
});

describe('Command Builder Logic', () => {
  it('quoteArg skips quoting simple paths', () => {
    expect(quoteArg('claude')).toBe('claude');
    expect(quoteArg('C:/Users/dev/.local/bin/claude')).toBe('C:/Users/dev/.local/bin/claude');

    const backslashPath = 'C:\\Users\\dev\\.local\\bin\\claude.EXE';
    const quotedBackslash = quoteArg(backslashPath);
    // Backslashes need quoting; quote character depends on platform (" on Windows, ' on POSIX)
    expect(quotedBackslash).toMatch(/^["'].*["']$/);

    const pathWithSpaces = 'C:/Program Files/claude/claude.exe';
    const quoted = quoteArg(pathWithSpaces);
    expect(quoted).toMatch(/^["'].*["']$/);
  });

  it('quoteArg sanitises multiline input by default (regression guard)', () => {
    const multiline = 'line1\nline2\nline3';
    const result = quoteArg(multiline);
    expect(result).not.toContain('\n');
    expect(result).toContain('line1 line2 line3');
  });

  it('quoteArg with multiline: true preserves newlines under bash', () => {
    const xml = '<task>\n  <title>Test</title>\n</task>';
    const result = quoteArg(xml, 'bash', { multiline: true });
    expect(result).toContain('\n  <title>Test</title>\n');
    expect(result.startsWith("'<task>")).toBe(true);
    expect(result.endsWith("</task>'")).toBe(true);
  });

  it('quoteArg with multiline: true converts newlines to PowerShell `n escape', () => {
    // PowerShell continuation via PTY is unreliable - pin the input to one
    // physical line and let PowerShell's escape parser produce the newlines.
    const xml = '<task>\n  <title>Test</title>\n</task>';
    const result = quoteArg(xml, 'pwsh', { multiline: true });
    // Final string is one physical line (no embedded newlines)
    expect(result).not.toContain('\n');
    // Newlines are encoded as the PowerShell escape `n
    expect(result).toBe('"<task>`n  <title>Test</title>`n</task>"');
  });

  it('quoteArg with multiline: true escapes tabs as PowerShell `t', () => {
    const result = quoteArg('col1\tcol2', 'powershell', { multiline: true });
    expect(result).not.toContain('\t');
    expect(result).toBe('"col1`tcol2"');
  });

  it('quoteArg with multiline: true preserves literal backticks via doubling under PowerShell', () => {
    // A literal backtick in the prompt content must NOT collide with the
    // newline escape we add - existing backticks get doubled first.
    const result = quoteArg('use `code` here\nline2', 'pwsh', { multiline: true });
    // ``code`` keeps the literal backticks; `n is the newline escape we add
    expect(result).toBe('"use ``code`` here`nline2"');
  });

  it('quoteArg doubles a trailing backslash run for cmd, so the CRT keeps the closing quote', () => {
    // Measured by round-tripping through node's process.argv: cmd hands the raw
    // line to the target's C runtime, which reads the `\"` of `"C:\dir\"` as an
    // escaped quote and delivers `C:\dir"`. Doubling the run fixes it.
    expect(quoteArg('C:\\dir\\', 'cmd')).toBe('"C:\\dir\\\\"');
    expect(quoteArg('finish the path C:\\dir\\', 'cmd.exe')).toBe('"finish the path C:\\dir\\\\"');
  });

  it('quoteArg leaves a trailing backslash alone for PowerShell, where it is not an escape', () => {
    // The opposite rule to cmd, and the reason the two branches cannot share a
    // chain: `"C:\dir\"` already reaches a native command as `C:\dir\` on both
    // pwsh 7.6 and Windows PowerShell 5.1. Escaping the backslash here would
    // deliver `C:\dir\\` and break every Windows path a spawn carries.
    expect(quoteArg('C:\\dir\\', 'pwsh')).toBe('"C:\\dir\\"');
    expect(quoteArg('C:\\Program Files\\bin\\claude.exe', 'powershell'))
      .toBe('"C:\\Program Files\\bin\\claude.exe"');
  });

  it('quoteArg leaves backticks and $ literal under cmd, which does not collapse them', () => {
    // cmd shared PowerShell's backtick doubling until this was measured: the
    // agent received `use ``code`` here`, two backticks per one written.
    expect(quoteArg('use `code` here', 'cmd')).toBe('"use `code` here"');
    expect(quoteArg('cost $5 total', 'cmd')).toBe('"cost $5 total"');
  });

  it('quoteArg escapes a quote for cmd by the C-runtime rule', () => {
    // `\"` is an escaped quote to the target's CRT, and a backslash run before
    // one has to be doubled or it eats the escape. Round-tripped through cmd:
    // both inputs below arrive at the agent byte-identical.
    expect(quoteArg('say "hi"', 'cmd')).toBe('"say \\"hi\\""');
    expect(quoteArg('path\\"x', 'cmd')).toBe('"path\\\\\\"x"');
  });

  it('quoteArg emits a quote PowerShell cannot parse, which is unreachable and stays', () => {
    // Named for what it is rather than pinned as correct. `"say \"hi\""` is a
    // parse error on BOTH pwsh 7.6 and Windows PowerShell 5.1 (the string ends
    // at the backslash-quote), and there is no form that works on both: pwsh
    // 7.3+ native argument passing wants a backtick-quote, while 5.1's legacy
    // passing drops that quote and wants backslash-backtick-quote. It is also
    // unreachable - every prompt-carrying builder pre-replaces `"` with `'`
    // for double-quote shells (claude/command-builder.ts and siblings), and no
    // other quoteArg input can hold a quote on Windows, where `"` is illegal in
    // a filename. Changing it would pick a losing host silently.
    expect(quoteArg('say "hi"', 'pwsh')).toBe('"say \\"hi\\""');
    // The backslash is NOT doubled here, unlike the cmd case above. That is the
    // whole difference between the two branches, on the one input that shows it.
    expect(quoteArg('path\\"x', 'powershell')).toBe('"path\\\\"x"');
  });

  it('quoteArg with multiline: true falls back to sanitisation under cmd', () => {
    // cmd.exe terminates the command on a literal newline mid-quote, so we
    // accept readability loss to keep the command parseable.
    const xml = '<task>\n  <title>Test</title>\n</task>';
    const result = quoteArg(xml, 'cmd', { multiline: true });
    expect(result).not.toContain('\n');
    expect(result).toContain('<task>');
    expect(result).toContain('<title>Test</title>');
  });

  it('quoteArg with multiline: true falls back to sanitisation when shell is omitted', () => {
    // Without a shell hint we can't tell PowerShell from cmd, and only the
    // unix branch tolerates raw newlines. Conservative fallback: sanitise.
    const xml = '<task>\n  <title>Test</title>\n</task>';
    const result = quoteArg(xml, undefined, { multiline: true });
    expect(result).not.toContain('\n');
    expect(result).toContain('<task>');
    expect(result).toContain('<title>Test</title>');
  });

  it('isCmdShell matches cmd basename only, not random paths containing "cmd"', () => {
    // Anchored basename match so unrelated paths don't trigger the cmd
    // fallback in quoteArg.
    expect(isCmdShell('cmd')).toBe(true);
    expect(isCmdShell('cmd.exe')).toBe(true);
    expect(isCmdShell('CMD.EXE')).toBe(true);
    expect(isCmdShell('C:\\Windows\\System32\\cmd.exe')).toBe(true);
    expect(isCmdShell('/c/windows/system32/cmd.exe')).toBe(true);

    expect(isCmdShell('/usr/local/cmd-tool/sh')).toBe(false);
    expect(isCmdShell('command.com')).toBe(false);
    expect(isCmdShell('bash')).toBe(false);
    expect(isCmdShell('powershell')).toBe(false);
    expect(isCmdShell('pwsh')).toBe(false);
  });

  it('isPowerShellShell matches the PowerShell family as a bare name, an .exe, or a full path', () => {
    expect(isPowerShellShell('powershell')).toBe(true);
    expect(isPowerShellShell('pwsh')).toBe(true);
    expect(isPowerShellShell('PowerShell')).toBe(true);
    expect(isPowerShellShell('PWSH')).toBe(true);
    expect(isPowerShellShell('powershell.exe')).toBe(true);
    expect(isPowerShellShell('pwsh.exe')).toBe(true);
    expect(isPowerShellShell('C:\\Program Files\\PowerShell\\7\\pwsh.exe')).toBe(true);
    expect(isPowerShellShell('C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe')).toBe(true);
    expect(isPowerShellShell('C:/Program Files/PowerShell/7/pwsh.exe')).toBe(true);

    expect(isPowerShellShell('cmd.exe')).toBe(false);
    expect(isPowerShellShell('C:\\Windows\\System32\\cmd.exe')).toBe(false);
    expect(isPowerShellShell('bash')).toBe(false);
    expect(isPowerShellShell('C:\\Program Files\\Git\\bin\\bash.exe')).toBe(false);
    expect(isPowerShellShell('zsh')).toBe(false);
    expect(isPowerShellShell('fish')).toBe(false);
    expect(isPowerShellShell('nu')).toBe(false);
    expect(isPowerShellShell('/bin/sh')).toBe(false);
    expect(isPowerShellShell('wsl -d Ubuntu')).toBe(false);
  });

  it('isPowerShellShell agrees with the inline substring test it replaced for every real shell form', () => {
    // buildSpawnClearPrelude, adaptCommandForShell, resolveShellArgs, and
    // resolveSpawnCwd each carried their own copy of this test. The predicate
    // must stay behavior-identical for what the Windows picker stores, and it
    // must be the exact negation isUnixLikeShell applies, so a spec can never
    // be neither unix-like nor PowerShell.
    const pickerForms = [
      'C:\\Program Files\\PowerShell\\7\\pwsh.exe',
      'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
      'C:\\Program Files\\Git\\bin\\bash.exe',
      'C:\\Windows\\System32\\cmd.exe',
      'wsl -d Ubuntu',
      'powershell',
      'pwsh',
      '/bin/zsh',
    ];
    for (const form of pickerForms) {
      const lower = form.toLowerCase();
      expect(isPowerShellShell(form)).toBe(lower.includes('powershell') || lower.includes('pwsh'));
    }
  });

  it('quoteArg quotes a bare -- for PowerShell hosts only', () => {
    // PowerShell's parameter binder consumes an unquoted -- before a .ps1
    // script (the npm shim resolveShimLaunch prefers) sees $args, so the
    // end-of-options guard the Claude/Grok/Ollama/Warp builders emit would
    // vanish on that route. The quoted form reaches every launcher as `--`.
    expect(quoteArg('--', 'pwsh')).toBe('"--"');
    expect(quoteArg('--', 'powershell')).toBe('"--"');
    expect(quoteArg('--', 'C:\\Program Files\\PowerShell\\7\\pwsh.exe')).toBe('"--"');

    expect(quoteArg('--', 'bash')).toBe('--');
    expect(quoteArg('--', 'cmd')).toBe('--');
    expect(quoteArg('--', 'wsl -d Ubuntu')).toBe('--');
    expect(quoteArg('--')).toBe('--');
    // Only the exact marker: a flag that starts with -- is an ordinary token.
    expect(quoteArg('--prompt', 'pwsh')).toBe('--prompt');
  });

  it('PowerShell call operator prefix', () => {
    function prefixForShell(command: string, shellName: string): string {
      if (shellName.includes('powershell') || shellName.includes('pwsh')) {
        return '& ' + command;
      }
      return command;
    }

    const cmd = '"C:\\Users\\dev\\.local\\bin\\claude.EXE" --dangerously-skip-permissions';

    expect(prefixForShell(cmd, 'powershell')).toBe('& ' + cmd);
    expect(prefixForShell(cmd, 'pwsh')).toBe('& ' + cmd);
    expect(prefixForShell(cmd, 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe')).toBe('& ' + cmd);

    expect(prefixForShell(cmd, 'bash')).toBe(cmd);
    expect(prefixForShell(cmd, 'cmd')).toBe(cmd);
    expect(prefixForShell(cmd, '/bin/zsh')).toBe(cmd);
  });

  it('interpolateTemplate replaces variables', () => {
    const template = '{{title}}{{description}}';
    const vars = { title: 'My Task', description: ': Build the feature' };
    const result = interpolateTemplate(template, vars);

    expect(result).toBe('My Task: Build the feature');
  });

  it('interpolateTemplate with empty description omits separator', () => {
    const template = '{{title}}{{description}}';
    const vars = { title: 'My Task', description: '' };
    const result = interpolateTemplate(template, vars);

    expect(result).toBe('My Task');
  });

  it('interpolateTemplate handles missing variables', () => {
    const template = '{{title}} in {{worktreePath}}';
    const vars = { title: 'Fix bug', worktreePath: '' };
    const result = interpolateTemplate(template, vars);

    expect(result).toBe('Fix bug in ');
  });

  it('quoteArg uses single quotes when shell is bash (prevents $var expansion)', () => {
    const result = quoteArg('fix $count bug', 'bash');
    expect(result).toBe("'fix $count bug'");
  });

  it('quoteArg uses single quotes when shell is WSL', () => {
    const result = quoteArg('deploy to $HOME/app', 'wsl -d Ubuntu');
    expect(result).toBe("'deploy to $HOME/app'");
  });

  it('quoteArg uses double quotes when shell is PowerShell', () => {
    const result = quoteArg('fix the bug', 'powershell');
    expect(result).toBe('"fix the bug"');
  });

  it('quoteArg uses double quotes when shell is cmd', () => {
    const result = quoteArg('fix the bug', 'cmd');
    expect(result).toBe('"fix the bug"');
  });

  it('quoteArg escapes single quotes inside single-quoted strings for bash', () => {
    const result = quoteArg("it's a bug", 'bash');
    expect(result).toBe("'it'\\''s a bug'");
  });

  it('quoteArg preserves backtick commands in single-quoted mode', () => {
    const result = quoteArg('check `whoami` output', '/usr/bin/bash');
    expect(result).toBe("'check `whoami` output'");
  });

  it('quoteArg escapes backticks for PowerShell', () => {
    const result = quoteArg('use `code` block', 'powershell');
    // Each backtick should be doubled for PowerShell (` → ``)
    expect(result).toBe('"use ``code`` block"');
  });

  it('quoteArg escapes $ for PowerShell to prevent variable expansion', () => {
    const result = quoteArg('fix $HOME and $(whoami) issue', 'powershell');
    // $ should be escaped as `$ for PowerShell
    expect(result).toContain('`$HOME');
    expect(result).toContain('`$(whoami)');
    // Should not contain unescaped $ (every $ should be preceded by `)
    expect(result).not.toMatch(/[^`]\$|^"\$/);
  });

  it('quoteArg escapes both backticks and $ in PowerShell prompt with code blocks', () => {
    const prompt = 'Refactor: ```typescript\nconst $count = items.length;\n```';
    const result = quoteArg(prompt, 'pwsh');
    // Backticks doubled, $ escaped - should not hang PowerShell
    expect(result).toContain('````');
    expect(result).toContain('`$count');
  });

  it('quoteArg leaves $ and backticks literal in bash single quotes', () => {
    const result = quoteArg('use $HOME and `whoami`', 'bash');
    // Single quotes protect everything - no escaping needed
    expect(result).toBe("'use $HOME and `whoami`'");
  });

  it('quoteArg with shell omitted falls back to platform detection', () => {
    const result = quoteArg('hello world');
    // Should produce either single or double quotes depending on platform
    expect(result).toMatch(/^["']hello world["']$/);
  });

  it('full pipeline: interpolateTemplate + quoteArg with multiline description (pre-cleaned)', () => {
    // In the real pipeline, description is cleaned before interpolation
    const template = '{{title}}{{description}}';
    const vars = {
      title: 'Fix bug',
      description: ': Step 1: do X Step 2: do Y Step 3: do Z',
    };
    const interpolated = interpolateTemplate(template, vars);
    const quoted = quoteArg(interpolated);

    expect(quoted).not.toContain('\n');
    expect(quoted).toContain('Fix bug');
    expect(quoted).toContain('Step 1: do X Step 2: do Y Step 3: do Z');
  });
});

describe('Prompt Delivery (Claude Agent)', () => {
  it('fresh session includes task title and description in prompt', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      prompt: 'Task: Fix login bug\n\nUsers cannot log in with OAuth',
    });

    expect(cmd).toContain('Fix login bug');
    expect(cmd).toContain('Users cannot log in with OAuth');
  });

  it('new session with session-id uses --session-id flag', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'abc-123-def',
      prompt: 'Task: My Task\n\nDescription',
    });

    expect(cmd).toContain('--session-id');
    expect(cmd).not.toContain('--resume');
    expect(cmd).toContain('abc-123-def');
  });

  it('resumed session uses --resume flag and omits prompt', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'abc-123-def',
      resume: true,
    });

    expect(cmd).toContain('--resume');
    expect(cmd).not.toContain('--session-id');
    expect(cmd).toContain('abc-123-def');
    const parts = cmd.split(' ');
    const lastPart = parts[parts.length - 1];
    expect(lastPart).toContain('abc-123-def');
  });

  it('resumed session with --resume has no prompt text', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'session-xyz',
      resume: true,
    });

    expect(cmd).toContain('--resume');
    expect(cmd).not.toContain('--session-id');
    expect(cmd).not.toContain('Task:');
    expect(cmd).not.toContain('Continue working');
  });

  it('resumed session delivers an explicit unattended continuation prompt', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'session-xyz',
      resume: true,
      permissionMode: 'auto',
      prompt: 'Continue the Verify stage and advance once it passes',
    });

    expect(cmd).toContain('--resume');
    expect(cmd).toContain('--permission-mode auto');
    expect(cmd).toContain('Continue the Verify stage and advance once it passes');
  });

  it('plan permission mode adds --permission-mode plan', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      permissionMode: 'plan',
      prompt: 'Task: Design auth\n\nPlan the architecture',
    });

    expect(cmd).toContain('--permission-mode');
    expect(cmd).toContain('plan');
    expect(cmd).toContain('Design auth');
  });

  it('default permission mode omits --permission-mode flag', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      permissionMode: 'default',
      prompt: 'Task: Build feature',
    });

    expect(cmd).not.toContain('--permission-mode');
  });

  it('no permission mode omits --permission-mode flag', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      prompt: 'Task: Build feature',
    });

    expect(cmd).not.toContain('--permission-mode');
  });

  it('acceptEdits permission mode adds --permission-mode acceptEdits', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      permissionMode: 'acceptEdits',
      prompt: 'Task: Refactor module',
    });

    expect(cmd).toContain('--permission-mode');
    expect(cmd).toContain('acceptEdits');
    expect(cmd).toContain('Refactor module');
  });

  it('adds -- separator before prompt to prevent option parsing', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      prompt: 'Simple task description',
    });
    expect(cmd).toMatch(/sess-123 -- /);
  });

  it('prompt with -> arrow does not cause unknown option error', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      prompt: 'Fix the Backlog -> Planning transition',
    });
    expect(cmd).toContain(' -- ');
    expect(cmd).toContain('Backlog -> Planning');
  });

  it('prompt with -- double-dash does not cause option parsing', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      prompt: 'Check the --verbose flag behavior',
    });
    expect(cmd).toContain(' -- ');
    expect(cmd).toContain('--verbose flag');
  });

  it('prompt with double quotes are replaced with single quotes', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      prompt: 'While it becomes "active" update the view',
    });
    expect(cmd).not.toContain('"active"');
    expect(cmd).toContain("'active'");
  });

  it('prompt starting with - is not treated as option', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      prompt: '- Fix this bug immediately',
    });
    expect(cmd).toContain(' -- ');
  });

  it('prompt with mixed special characters is safely quoted', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      prompt: 'Fix "error" in path C:\\Users\\dev -> deploy & test (urgent)',
    });
    expect(cmd).toContain(' -- ');
    expect(cmd).not.toContain('"error"');
    expect(cmd).toContain("'error'");
  });

  it('resumed session has no -- separator (no prompt)', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      resume: true,
    });
    expect(cmd).not.toContain(' -- ');
  });

  it('prompt with bare attachment paths is handled', () => {
    const cmd = buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      sessionId: 'sess-123',
      prompt: 'Fix bug\nC:\\Users\\dev\\image-1.png\nC:\\Users\\dev\\image-2.png',
    });
    expect(cmd).toContain(' -- ');
    expect(cmd).toContain('image-1.png');
  });
});

describe('Slugify Logic', () => {
  it('converts titles to filesystem-safe slugs', () => {
    expect(slugify('Fix login bug')).toBe('fix-login-bug');
    expect(slugify('Add feature (urgent!)')).toBe('add-feature-urgent');
    expect(slugify('---hello---')).toBe('hello');
    expect(slugify('ALL CAPS TITLE')).toBe('all-caps-title');
    expect(slugify('Special @#$% chars!')).toBe('special-chars');
    expect(slugify('')).toBe('');

    const longTitle = 'a'.repeat(100);
    expect(slugify(longTitle).length).toBeLessThanOrEqual(20);
  });

  // The slug now names only the BRANCH. Worktree directories are the task's
  // display_id, which is why there is no longer a path-length budget to test:
  // the folder is a handful of characters regardless of the title.
  it('branch name includes the task ID suffix', () => {
    const taskId = 'abc12345-6789-0000-1111-222233334444';
    const slug = slugify('Fix login bug') || 'task';
    const shortId = taskId.slice(0, 8);

    expect(`${slug}-${shortId}`).toBe('fix-login-bug-abc12345');
  });

  it('truncates long titles to keep branch names readable', () => {
    const slug = slugify('update preview to copy local settings json for azure deploy');
    expect(slug.length).toBeLessThanOrEqual(20);
    expect(`${slug}-abc12345`.length).toBeLessThanOrEqual(29);
  });
});

describe('isAutoGeneratedBranch', () => {
  const taskId = 'abc12345-6789-0000-1111-222233334444';

  it('matches branch with full slug (default budget)', () => {
    expect(isAutoGeneratedBranch('fix-login-bug-abc12345', taskId, 'Fix login bug')).toBe(true);
  });

  it('matches branch with truncated slug (reduced budget)', () => {
    // Branch created with budget=3 produces "fix" slug
    expect(isAutoGeneratedBranch('fix-abc12345', taskId, 'Fix login bug')).toBe(true);
  });

  it('matches branch with fallback "task" slug (zero budget)', () => {
    expect(isAutoGeneratedBranch('task-abc12345', taskId, 'Fix login bug')).toBe(true);
  });

  it('rejects custom branch names', () => {
    expect(isAutoGeneratedBranch('feature/my-branch', taskId, 'Fix login bug')).toBe(false);
    expect(isAutoGeneratedBranch('custom-name-abc12345', taskId, 'Fix login bug')).toBe(false);
  });

  it('rejects branch with wrong task ID', () => {
    expect(isAutoGeneratedBranch('fix-login-bug-99999999', taskId, 'Fix login bug')).toBe(false);
  });
});

// adaptCommandForShell guards on win32 via an injectable `platform` param
// (production callers omit it), so these tests pass 'win32' explicitly and
// run on every platform, including Linux CI.
describe('Windows Path Conversion for Shells (adaptCommandForShell)', () => {
  it('converts Windows paths to Git Bash POSIX format', () => {
    const cmd = 'C:\\Users\\dev\\.local\\bin\\claude.EXE --dangerously-skip-permissions "Task: test"';
    const result = adaptCommandForShell(cmd, 'c:\\program files\\git\\usr\\bin\\bash.exe', 'win32');
    expect(result).toBe('/c/Users/dev/.local/bin/claude.EXE --dangerously-skip-permissions "Task: test"');
  });

  it('converts Windows paths to WSL /mnt/ format', () => {
    const cmd = 'C:\\Users\\dev\\.local\\bin\\claude.EXE --print "hello"';
    const result = adaptCommandForShell(cmd, 'wsl -d ubuntu', 'win32');
    expect(result).toBe('/mnt/c/Users/dev/.local/bin/claude.EXE --print "hello"');
  });

  it('handles quoted Windows paths with spaces', () => {
    const cmd = '"C:\\Program Files\\claude\\claude.exe" --dangerously-skip-permissions "prompt"';
    const result = adaptCommandForShell(cmd, 'bash', 'win32');
    expect(result).toBe('"/c/Program Files/claude/claude.exe" --dangerously-skip-permissions "prompt"');
  });

  it('converts a single-quoted Windows path for Git Bash, staying single-quoted', () => {
    const cmd = "'C:\\Users\\dev\\.local\\bin\\claude.EXE' --dangerously-skip-permissions 'Task: test'";
    const result = adaptCommandForShell(cmd, 'c:\\program files\\git\\usr\\bin\\bash.exe', 'win32');
    expect(result).toBe("'/c/Users/dev/.local/bin/claude.EXE' --dangerously-skip-permissions 'Task: test'");
  });

  it('converts a single-quoted Windows path for WSL, staying single-quoted', () => {
    const cmd = "'C:\\Users\\dev\\.local\\bin\\claude.EXE' --print 'hello'";
    const result = adaptCommandForShell(cmd, 'wsl -d ubuntu', 'win32');
    expect(result).toBe("'/mnt/c/Users/dev/.local/bin/claude.EXE' --print 'hello'");
  });

  it('re-quotes a converted single-quoted path with spaces in single quotes', () => {
    const cmd = "'C:\\Program Files\\claude\\claude.exe' --print 'prompt'";
    const result = adaptCommandForShell(cmd, 'bash', 'win32');
    expect(result).toBe("'/c/Program Files/claude/claude.exe' --print 'prompt'");
  });

  it('handles different drive letters', () => {
    const cmd = 'D:\\tools\\claude.exe --print "hello"';
    const result = adaptCommandForShell(cmd, 'bash', 'win32');
    expect(result).toBe('/d/tools/claude.exe --print "hello"');
  });

  it('no conversion for cmd.exe', () => {
    const cmd = 'C:\\Users\\dev\\.local\\bin\\claude.EXE --dangerously-skip-permissions "prompt"';
    const result = adaptCommandForShell(cmd, 'c:\\windows\\system32\\cmd.exe', 'win32');
    expect(result).toBe(cmd);
  });

  it('PowerShell gets & prefix, no path conversion', () => {
    const cmd = 'C:\\Users\\dev\\.local\\bin\\claude.EXE --print "test"';
    const result = adaptCommandForShell(cmd, 'pwsh', 'win32');
    expect(result).toBe('& ' + cmd);
  });

  it('does not corrupt prompt text with backslashes', () => {
    const cmd = 'C:\\Users\\dev\\bin\\claude.EXE --print "path is C:\\some\\path"';
    const result = adaptCommandForShell(cmd, 'bash', 'win32');
    expect(result.startsWith('/c/Users/dev/bin/claude.EXE')).toBe(true);
    expect(result).toContain('C:\\some\\path');
  });

  it('returns the command unchanged on non-win32 platforms even for unix-like shells', () => {
    const cmd = "'C:\\Users\\dev\\.local\\bin\\claude.EXE' --print 'hello'";
    expect(adaptCommandForShell(cmd, 'bash', 'linux')).toBe(cmd);
    expect(adaptCommandForShell(cmd, 'wsl -d ubuntu', 'darwin')).toBe(cmd);
  });

  it('treats a wsl.exe-prefixed shell spec (hand-edited config) as WSL, converting to /mnt/c/...', () => {
    // resolveShellArgs now accepts a hand-edited "wsl.exe -d <distro>" config
    // value in addition to the picker's "wsl -d <distro>". The same shell
    // string also reaches adaptCommandForShell at the spawn seam (via
    // session-spawn-flow.ts's `shellName = shell.toLowerCase()`), whose
    // isWsl gate is `lower.startsWith('wsl')` - already broad enough to
    // match the .exe form, but that was never pinned. Guards against a
    // future "tighten the gate to match resolveShellArgs" edit that adds a
    // trailing space and silently sends /c/... (Git Bash form) instead of
    // /mnt/c/... for a WSL shell.
    const cmd = 'C:\\Users\\dev\\.local\\bin\\claude.EXE --print "hello"';
    const result = adaptCommandForShell(cmd, 'wsl.exe -d ubuntu', 'win32');
    expect(result).toBe('/mnt/c/Users/dev/.local/bin/claude.EXE --print "hello"');
  });
});

// convertWindowsExePath has no platform guard - runs on all platforms
describe('Windows Path Conversion (convertWindowsExePath)', () => {
  it('no-op for Unix paths (macOS/Linux)', () => {
    const cmd = '/usr/local/bin/claude --print "hello"';
    const result = convertWindowsExePath(cmd, false);
    expect(result).toBe(cmd);
  });

  it('no-op for simple commands', () => {
    const cmd = 'echo hello world';
    const result = convertWindowsExePath(cmd, false);
    expect(result).toBe(cmd);
  });

  // The full leading-token matrix: every quote form quoteArg can emit
  // (bare, double-quoted, single-quoted) for both unix-like targets.
  describe('leading-token matrix', () => {
    it('converts a bare drive-letter path for Git Bash', () => {
      expect(convertWindowsExePath('C:\\Users\\dev\\bin\\claude.exe --print', false))
        .toBe('/c/Users/dev/bin/claude.exe --print');
    });

    it('converts a bare drive-letter path for WSL', () => {
      expect(convertWindowsExePath('C:\\Users\\dev\\bin\\claude.exe --print', true))
        .toBe('/mnt/c/Users/dev/bin/claude.exe --print');
    });

    it('converts a double-quoted drive-letter path for Git Bash, staying double-quoted', () => {
      expect(convertWindowsExePath('"C:\\Users\\dev\\bin\\claude.exe" --print', false))
        .toBe('"/c/Users/dev/bin/claude.exe" --print');
    });

    it('converts a double-quoted drive-letter path for WSL', () => {
      expect(convertWindowsExePath('"C:\\Program Files\\claude\\claude.exe" --print', true))
        .toBe('"/mnt/c/Program Files/claude/claude.exe" --print');
    });

    it('converts a single-quoted drive-letter path for Git Bash, staying single-quoted', () => {
      expect(convertWindowsExePath("'C:\\Users\\dev\\bin\\agy.EXE' --mode accept-edits", false))
        .toBe("'/c/Users/dev/bin/agy.EXE' --mode accept-edits");
    });

    it('converts a single-quoted drive-letter path for WSL, staying single-quoted', () => {
      expect(convertWindowsExePath("'C:\\Users\\dev\\bin\\agy.EXE' --mode accept-edits", true))
        .toBe("'/mnt/c/Users/dev/bin/agy.EXE' --mode accept-edits");
    });

    it('keeps shell-active characters in a spaceless path inert by staying quoted', () => {
      // & and $ are legal Windows path characters; unquoted they are live
      // bash syntax (& backgrounds the truncated command).
      expect(convertWindowsExePath("'C:\\Tools\\R&D\\claude.exe' --print", false))
        .toBe("'/c/Tools/R&D/claude.exe' --print");
    });

    it('keeps shell-active characters inert for the double-quoted form too', () => {
      // The same hazard through quoteArg's win32 fallback (no shell hint,
      // e.g. a transient session), which double-quotes the cliPath: the
      // converted spaceless path must stay quoted, or & backgrounds the
      // truncated command in bash.
      expect(convertWindowsExePath('"C:\\Tools\\R&D\\claude.exe" --print', false))
        .toBe('"/c/Tools/R&D/claude.exe" --print');
    });

    it('re-quotes a single-quoted spaces path in single quotes for Git Bash', () => {
      expect(convertWindowsExePath("'C:\\Program Files\\claude\\claude.exe' --print", false))
        .toBe("'/c/Program Files/claude/claude.exe' --print");
    });

    it('re-quotes a single-quoted spaces path in single quotes for WSL', () => {
      expect(convertWindowsExePath("'C:\\Program Files\\claude\\claude.exe' --print", true))
        .toBe("'/mnt/c/Program Files/claude/claude.exe' --print");
    });

    it('converts a single-quoted UNC exe path, staying single-quoted', () => {
      expect(convertWindowsExePath("'\\\\server\\share\\bin\\exe' --flag", false))
        .toBe("'//server/share/bin/exe' --flag");
    });

    it('re-quotes a single-quoted UNC exe path containing spaces', () => {
      expect(convertWindowsExePath("'\\\\server\\share\\my exe' --flag", false))
        .toBe("'//server/share/my exe' --flag");
    });

    it('leaves single-quoted trailing arguments untouched', () => {
      const result = convertWindowsExePath(
        "'C:\\Users\\dev\\bin\\claude.exe' --print 'path is C:\\some\\path'",
        false,
      );
      expect(result.startsWith("'/c/Users/dev/bin/claude.exe'")).toBe(true);
      expect(result).toContain("'path is C:\\some\\path'");
    });
  });

  // The double-quoted and single-quoted branches used to repeat a group
  // shaped `(?:\\[^"]+)+` (backslash NOT excluded from the inner class),
  // the classic catastrophic-backtracking shape, equivalent to `(a+)+`. An
  // unterminated quoted path with a long run of backslashes has no valid
  // parse, so the engine explored every way to partition the run among
  // repetitions before giving up. A cliPath value (project-configurable
  // via `agent.cliPaths.<agent>`) reaches this regex synchronously on the
  // main-process spawn path, so this was a real hang vector, not a
  // theoretical one. Measured against the reverted pre-fix regex with 44
  // backslashes (the size below): ~2.7s in isolated node, ~8s inside this
  // vitest run on this machine. Growth is roughly 2.5x per +2 backslashes,
  // so a 48-char run already costs ~1 CPU-minute under vitest. The hardened
  // regex excludes `\` from the repeated character class, so each backslash
  // has exactly one parse and matching stays linear (sub-millisecond even at
  // thousands of backslashes). The unquoted (bare) branch was never
  // vulnerable (nothing follows its repeated group, so the first greedy
  // match always succeeds with no backtracking) and is intentionally not
  // covered here.
  describe('adversarial input does not cause catastrophic backtracking (ReDoS guard)', () => {
    it('returns quickly for an unterminated double-quoted path with a long backslash run', () => {
      const cmd = '"C:' + '\\'.repeat(44); // deliberately missing the closing quote
      const start = Date.now();
      const result = convertWindowsExePath(cmd, false);
      const elapsedMs = Date.now() - start;
      expect(elapsedMs).toBeLessThan(1000);
      // No closing quote means the regex never matches: no-op passthrough.
      expect(result).toBe(cmd);
    });

    it('returns quickly for an unterminated single-quoted path with a long backslash run', () => {
      const cmd = "'C:" + '\\'.repeat(44); // deliberately missing the closing quote
      const start = Date.now();
      const result = convertWindowsExePath(cmd, false);
      const elapsedMs = Date.now() - start;
      expect(elapsedMs).toBeLessThan(1000);
      expect(result).toBe(cmd);
    });
  });
});

// The composed seam that shipped the Git Bash / WSL spawn bug: a real adapter
// builds its command with quoteArg(cliPath, shell) (single quotes for
// unix-like shells), and adaptCommandForShell must still convert the leading
// token into a form the shell can resolve.
describe('adapter command composed through adaptCommandForShell', () => {
  it('claude buildCommand for a Git Bash shell converts its leading token to a quoted /c/... path', () => {
    const shell = 'C:\\Program Files\\Git\\usr\\bin\\bash.exe';
    const cmd = new CommandBuilder().buildClaudeCommand({
      cliPath: 'C:\\Users\\dev\\.local\\bin\\claude.EXE',
      taskId: 'shell-compose',
      cwd: 'C:\\Users\\dev\\project',
      permissionMode: 'default',
      shell,
    });
    const adapted = adaptCommandForShell(cmd, shell.toLowerCase(), 'win32');
    expect(adapted.startsWith("'/c/Users/dev/.local/bin/claude.EXE'")).toBe(true);
  });

  it('claude buildCommand for WSL converts its leading token to a quoted /mnt/c/... path', () => {
    const shell = 'wsl -d Ubuntu';
    const cmd = new CommandBuilder().buildClaudeCommand({
      cliPath: 'C:\\Users\\dev\\.local\\bin\\claude.EXE',
      taskId: 'shell-compose',
      cwd: 'C:\\Users\\dev\\project',
      permissionMode: 'default',
      shell,
    });
    const adapted = adaptCommandForShell(cmd, shell.toLowerCase(), 'win32');
    expect(adapted.startsWith("'/mnt/c/Users/dev/.local/bin/claude.EXE'")).toBe(true);
  });

  it('a cliPath with spaces survives as one single-quoted token', () => {
    const shell = 'C:\\Program Files\\Git\\usr\\bin\\bash.exe';
    const cmd = new CommandBuilder().buildClaudeCommand({
      cliPath: 'C:\\Program Files\\Claude\\claude.exe',
      taskId: 'shell-compose',
      cwd: 'C:\\Users\\dev\\project',
      permissionMode: 'default',
      shell,
    });
    const adapted = adaptCommandForShell(cmd, shell.toLowerCase(), 'win32');
    expect(adapted.startsWith("'/c/Program Files/Claude/claude.exe'")).toBe(true);
  });

  it('undefined shell (transient session) falls back to double quotes on win32 and still converts', () => {
    // Transient / Command Terminal sessions pass no shell to the builder, so
    // quoteArg falls back to platform detection: double quotes on win32. That
    // form is converted by the double-quote branch and stays double-quoted
    // (shell-active characters in the path must remain inert). Pin it so a
    // fix to the single-quote path can never silently regress the Command
    // Terminal flow.
    const originalPlatformDescriptor = Object.getOwnPropertyDescriptor(process, 'platform')!;
    Object.defineProperty(process, 'platform', { value: 'win32' });
    try {
      const quoted = quoteArg('C:\\Users\\dev\\.local\\bin\\claude.EXE');
      expect(quoted).toBe('"C:\\Users\\dev\\.local\\bin\\claude.EXE"');
      const adapted = adaptCommandForShell(`${quoted} --print`, 'bash', 'win32');
      expect(adapted).toBe('"/c/Users/dev/.local/bin/claude.EXE" --print');
    } finally {
      Object.defineProperty(process, 'platform', originalPlatformDescriptor);
    }
  });
});

// The real CommandBuilder.buildClaudeCommand's "--" end-of-options guard
// (as opposed to the deliberately simplified inline buildClaudeCommand()
// helper above, which never went through quoteArg for the marker) was never
// exercised under a PowerShell-family shell, so a revert of the
// `quoteArg('--', shell)` call back to a bare '--' literal passed every test
// in this file until this one was added.
describe('CommandBuilder buildClaudeCommand: quoted "--" end-of-options guard under PowerShell', () => {
  it('quotes the -- marker before the prompt when the shell is PowerShell', () => {
    const cmd = new CommandBuilder().buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'task-1',
      cwd: '/project',
      permissionMode: 'default',
      sessionId: 'sess-123',
      shell: 'powershell',
      prompt: 'Simple task description',
    });

    expect(cmd).toContain('"--"');
    expect(cmd).toContain('Simple task description');
  });
});

describe('Status Bridge Script', () => {
  const bridgePath = path.resolve(__dirname, '../../src/main/agent/status-bridge.js');

  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'statusbridge-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('bridge writes JSON to output file', () => {
    const tmpFile = path.join(tmpDir, 'bridge-test.json');

    const input = JSON.stringify({
      context_window: { used_percentage: 42, total_input_tokens: 1000, total_output_tokens: 500, context_window_size: 200000 },
      cost: { total_cost_usd: 0.15, total_duration_ms: 5000 },
      model: { id: 'claude-opus-4-6', display_name: 'Opus 4.6' },
    });

    execFileSync(process.execPath, [bridgePath, tmpFile], {
      input,
      encoding: 'utf-8',
      timeout: 5000,
    });

    const written = JSON.parse(fs.readFileSync(tmpFile, 'utf-8'));
    expect(written.context_window.used_percentage).toBe(42);
    expect(written.cost.total_cost_usd).toBe(0.15);
    expect(written.model.display_name).toBe('Opus 4.6');
  });

  it('bridge outputs empty string to stdout (no TUI status line)', () => {
    const input = JSON.stringify({
      context_window: { used_percentage: 67.5 },
      cost: { total_cost_usd: 1.234 },
      model: { display_name: 'Sonnet 4.6' },
    });

    const stdout = execFileSync(process.execPath, [bridgePath], {
      input,
      encoding: 'utf-8',
      timeout: 5000,
    });

    expect(stdout).toBe('');
  });

  it('bridge handles malformed JSON gracefully', () => {
    const stdout = execFileSync(process.execPath, [bridgePath], {
      input: 'not-json{{{',
      encoding: 'utf-8',
      timeout: 5000,
    });

    expect(stdout).toBe('');
  });

  it('bridge handles missing fields gracefully', () => {
    const input = JSON.stringify({});

    const stdout = execFileSync(process.execPath, [bridgePath], {
      input,
      encoding: 'utf-8',
      timeout: 5000,
    });

    expect(stdout).toBe('');
  });
});

describe('Merged Settings (statusLine)', () => {
  it('statusLine is an object with type and command fields', () => {
    const existingSettings = { permissions: { allow: ['Read'] } };
    const bridgePath = '/path/to/status-bridge.js';
    const statusPath = '/project/.kangentic/status/session-123.json';

    const merged = {
      ...existingSettings,
      statusLine: {
        type: 'command',
        command: `node "${bridgePath}" "${statusPath}"`,
      },
    };

    expect(merged.statusLine).toHaveProperty('type', 'command');
    expect(merged.statusLine).toHaveProperty('command');
    expect(typeof merged.statusLine.command).toBe('string');
    expect(merged.statusLine.command).toContain('node');
    expect(merged.statusLine.command).toContain('status-bridge.js');
    expect(merged.statusLine.command).toContain('session-123.json');
  });

  it('merged settings preserve existing project settings', () => {
    const existingSettings = {
      permissions: { allow: ['Read', 'Edit'] },
      env: { CUSTOM_VAR: 'hello' },
    };

    const merged = {
      ...existingSettings,
      statusLine: {
        type: 'command',
        command: 'node /bridge.js /output.json',
      },
    };

    expect(merged.permissions).toEqual({ allow: ['Read', 'Edit'] });
    expect(merged.env).toEqual({ CUSTOM_VAR: 'hello' });
    expect(merged.statusLine.type).toBe('command');
  });

  it('statusLine is not a plain string (regression check)', () => {
    const merged = {
      statusLine: {
        type: 'command',
        command: 'node /bridge.js /output.json',
      },
    };

    expect(typeof merged.statusLine).toBe('object');
    expect(typeof merged.statusLine).not.toBe('string');
  });
});

describe('Merged Settings -- Local Settings Merge', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kangentic-cmd-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('writes a coarse statusLine refreshInterval so background sessions keep writing status.json', () => {
    // Claude only runs the statusLine command on event-driven triggers (never
    // at session start), so a background/idle session can stall without ever
    // writing status.json -- the board card then never learns the live model +
    // context %. refreshInterval re-runs the command on a fixed timer. Kept
    // coarse (not the 1s minimum) because the card already shows a placeholder
    // instantly; this only backfills the slow-moving live numbers.
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'refresh-sess', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'refresh-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'refresh-sess',
      statusOutputPath: statusOutput,
    });

    const mergedPath = path.join(tmpDir, '.kangentic', 'sessions', 'refresh-sess', 'settings.json');
    const merged = JSON.parse(fs.readFileSync(mergedPath, 'utf-8'));

    expect(merged.statusLine.type).toBe('command');
    expect(merged.statusLine.command).toContain('status-bridge');
    // Present, valid (docs: seconds, min 1), and coarse (not a 1s hot loop).
    expect(typeof merged.statusLine.refreshInterval).toBe('number');
    expect(merged.statusLine.refreshInterval).toBeGreaterThanOrEqual(1);
    expect(merged.statusLine.refreshInterval).toBeLessThanOrEqual(60);
  });

  it('merges user hooks from .claude/settings.local.json into session settings', () => {
    // Set up project with both settings.json and settings.local.json
    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });

    // Project settings with a user hook
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({
      permissions: { allow: ['Read'] },
      hooks: {
        PreToolUse: [
          { matcher: '', hooks: [{ type: 'command', command: 'echo project-hook' }] },
        ],
      },
    }));

    // Local settings with a different user hook
    fs.writeFileSync(path.join(claudeDir, 'settings.local.json'), JSON.stringify({
      hooks: {
        PreToolUse: [
          { matcher: 'Bash', hooks: [{ type: 'command', command: 'echo local-hook' }] },
        ],
        Stop: [
          { matcher: '', hooks: [{ type: 'command', command: 'echo local-stop' }] },
        ],
      },
    }));

    const builder = new CommandBuilder();

    // Create a status output path so createMergedSettings runs
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'test-sess', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'test-task-id',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'test-sess',
      statusOutputPath: statusOutput,
      eventsOutputPath: path.join(tmpDir, '.kangentic', 'sessions', 'test-sess', 'events.jsonl'),
    });

    // Read the merged settings file
    const mergedPath = path.join(tmpDir, '.kangentic', 'sessions', 'test-sess', 'settings.json');
    const merged = JSON.parse(fs.readFileSync(mergedPath, 'utf-8'));

    // Project hook should be present
    const preToolUseCommands = merged.hooks.PreToolUse
      .flatMap((e: { hooks: Array<{ command: string }> }) => e.hooks.map((h: { command: string }) => h.command));
    expect(preToolUseCommands).toContain('echo project-hook');

    // Local hook should also be present
    expect(preToolUseCommands).toContain('echo local-hook');

    // Local Stop hook should be present
    const stopCommands = merged.hooks.Stop
      .flatMap((e: { hooks: Array<{ command: string }> }) => e.hooks.map((h: { command: string }) => h.command));
    expect(stopCommands).toContain('echo local-stop');

    // Project permissions should be preserved (local had no permissions key)
    expect(merged.permissions).toEqual({ allow: ['Read'], deny: [] });
  });

  it('recreates a missing session directory and re-wires event-bridge hooks (resume self-heal)', () => {
    // A resume after the prior session directory was deleted: the .claude
    // project settings exist but the session dir does NOT. buildClaudeCommand
    // -> createMergedSettings must idempotently recreate the dir and write a
    // settings.json whose hooks point the event bridge at this session's
    // eventsOutputPath, so the resumed session always has a working feed.
    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({}));

    const sessionDir = path.join(tmpDir, '.kangentic', 'sessions', 'resumed-sess');
    const statusOutput = path.join(sessionDir, 'status.json');
    const eventsOutput = path.join(sessionDir, 'events.jsonl');

    // Deliberately do NOT pre-create sessionDir - simulate the wiped prior dir.
    expect(fs.existsSync(sessionDir)).toBe(false);

    const builder = new CommandBuilder();
    const cmd = builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'resumed-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'agent-sess-uuid',
      resume: true,
      statusOutputPath: statusOutput,
      eventsOutputPath: eventsOutput,
    });

    // Directory + settings.json recreated idempotently.
    expect(fs.existsSync(sessionDir)).toBe(true);
    const mergedPath = path.join(sessionDir, 'settings.json');
    expect(fs.existsSync(mergedPath)).toBe(true);

    // Hooks re-wired to the event bridge + this session's events path.
    const merged = JSON.parse(fs.readFileSync(mergedPath, 'utf-8'));
    const hooksJson = JSON.stringify(merged.hooks);
    expect(hooksJson).toContain('event-bridge');
    expect(hooksJson).toContain('resumed-sess');
    expect(hooksJson).toContain('events.jsonl');

    // The command consumes the recreated settings file and resumes the session.
    expect(cmd).toContain('--settings');
    expect(cmd).toContain('--resume');
  });

  it('deep-merges permissions.allow from project and local settings', () => {
    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });

    // Project settings with core permissions
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({
      permissions: { allow: ['Read', 'Edit', 'Write', 'Glob', 'Grep'], deny: [] },
    }));

    // Local settings with extra permissions
    fs.writeFileSync(path.join(claudeDir, 'settings.local.json'), JSON.stringify({
      permissions: { allow: ['WebFetch(domain:deepwiki.com)', 'Bash(test:*)'] },
    }));

    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'perms-test', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'perms-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'perms-test',
      statusOutputPath: statusOutput,
    });

    const mergedPath = path.join(tmpDir, '.kangentic', 'sessions', 'perms-test', 'settings.json');
    const merged = JSON.parse(fs.readFileSync(mergedPath, 'utf-8'));

    // Both project and local permissions should be present
    expect(merged.permissions.allow).toContain('Read');
    expect(merged.permissions.allow).toContain('Edit');
    expect(merged.permissions.allow).toContain('Write');
    expect(merged.permissions.allow).toContain('Glob');
    expect(merged.permissions.allow).toContain('Grep');
    expect(merged.permissions.allow).toContain('WebFetch(domain:deepwiki.com)');
    expect(merged.permissions.allow).toContain('Bash(test:*)');
    expect(merged.permissions.allow).toHaveLength(7); // no duplicates
  });

  it('writes merged settings to session directory for worktree sessions (not to worktree .claude/)', () => {
    // Set up a "worktree" cwd separate from projectRoot
    const worktreeDir = path.join(tmpDir, 'worktree');
    fs.mkdirSync(worktreeDir, { recursive: true });

    // Project root has settings
    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({
      permissions: { allow: ['Read'] },
    }));

    // Project root has local settings with extra permissions
    fs.writeFileSync(path.join(claudeDir, 'settings.local.json'), JSON.stringify({
      permissions: { allow: ['Bash(test:*)'] },
    }));

    const builder = new CommandBuilder();

    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'test-sess', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    const cmd = builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'test-task-id',
      cwd: worktreeDir,
      projectRoot: tmpDir,
      permissionMode: 'default',
      sessionId: 'test-sess',
      statusOutputPath: statusOutput,
      eventsOutputPath: path.join(tmpDir, '.kangentic', 'sessions', 'test-sess', 'events.jsonl'),
    });

    // --settings flag SHOULD be present for worktree sessions
    expect(cmd).toContain('--settings');

    // Session settings file should exist
    const mergedPath = path.join(tmpDir, '.kangentic', 'sessions', 'test-sess', 'settings.json');
    expect(fs.existsSync(mergedPath)).toBe(true);

    // Merged file should include project root's settings.json + settings.local.json permissions
    const merged = JSON.parse(fs.readFileSync(mergedPath, 'utf-8'));
    expect(merged.permissions.allow).toContain('Read');
    expect(merged.permissions.allow).toContain('Bash(test:*)');
    expect(merged.statusLine).toBeDefined();
    expect(merged.statusLine.type).toBe('command');

    // .claude/settings.local.json should NOT be created in the worktree
    const wtLocalPath = path.join(worktreeDir, '.claude', 'settings.local.json');
    expect(fs.existsSync(wtLocalPath)).toBe(false);
  });

  it('includes --settings flag for worktree scenarios', () => {
    const worktreeDir = path.join(tmpDir, 'worktree');
    fs.mkdirSync(worktreeDir, { recursive: true });

    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({}));

    const builder = new CommandBuilder();

    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'wt-sess', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    const cmd = builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'test-task-id',
      cwd: worktreeDir,
      projectRoot: tmpDir,
      permissionMode: 'default',
      sessionId: 'wt-sess',
      statusOutputPath: statusOutput,
    });

    // --settings flag should be present for all sessions (including worktrees)
    expect(cmd).toContain('--settings');
  });

  it('still writes to session directory and uses --settings for main repo', () => {
    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({}));

    const builder = new CommandBuilder();

    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'main-sess', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    const cmd = builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'test-task-id',
      cwd: tmpDir,
      // no projectRoot -- cwd IS the project root
      permissionMode: 'default',
      sessionId: 'main-sess',
      statusOutputPath: statusOutput,
    });

    // --settings flag should be present for main repo
    expect(cmd).toContain('--settings');

    // Session settings file should exist
    const mergedPath = path.join(tmpDir, '.kangentic', 'sessions', 'main-sess', 'settings.json');
    expect(fs.existsSync(mergedPath)).toBe(true);

    // No settings.local.json in the project root's .claude/ (not a worktree)
    expect(fs.existsSync(path.join(tmpDir, '.claude', 'settings.local.json'))).toBe(false);
  });

  it('does not create .claude/ directory in worktree (hooks delivered via --settings)', () => {
    const worktreeDir = path.join(tmpDir, 'worktree-no-claude');
    fs.mkdirSync(worktreeDir, { recursive: true });
    // No .claude/ dir in worktree

    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({}));

    const builder = new CommandBuilder();

    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'mkdir-sess', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'test-task-id',
      cwd: worktreeDir,
      projectRoot: tmpDir,
      permissionMode: 'default',
      sessionId: 'mkdir-sess',
      statusOutputPath: statusOutput,
    });

    // .claude/ directory should NOT be created -- hooks are delivered via --settings
    expect(fs.existsSync(path.join(worktreeDir, '.claude'))).toBe(false);
  });

  it('merges "always allow" permission grants from worktree settings.local.json on resume', () => {
    // Set up project root with settings
    const claudeDir = path.join(tmpDir, '.claude');
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify({
      permissions: { allow: ['Read', 'Glob'] },
    }));

    // Set up worktree with "always allow" grants written by Claude during a previous session
    const worktreeDir = path.join(tmpDir, 'worktree-with-grants');
    fs.mkdirSync(worktreeDir, { recursive: true });
    const wtClaudeDir = path.join(worktreeDir, '.claude');
    fs.mkdirSync(wtClaudeDir, { recursive: true });
    fs.writeFileSync(path.join(wtClaudeDir, 'settings.local.json'), JSON.stringify({
      permissions: { allow: ['Bash(npm test:*)', 'Edit'] },
    }));

    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'grant-sess', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'grant-task',
      cwd: worktreeDir,
      projectRoot: tmpDir,
      permissionMode: 'default',
      sessionId: 'grant-sess',
      statusOutputPath: statusOutput,
    });

    // Read the merged settings file
    const mergedPath = path.join(tmpDir, '.kangentic', 'sessions', 'grant-sess', 'settings.json');
    const merged = JSON.parse(fs.readFileSync(mergedPath, 'utf-8'));

    // Project root permissions should be present
    expect(merged.permissions.allow).toContain('Read');
    expect(merged.permissions.allow).toContain('Glob');

    // Worktree "always allow" grants should be merged in
    expect(merged.permissions.allow).toContain('Bash(npm test:*)');
    expect(merged.permissions.allow).toContain('Edit');
  });
});

// ---------------------------------------------------------------------------
// TUI Fullscreen Default
// Tests for the `merged.tui = 'fullscreen'` injection in createMergedSettings.
// userHasGlobalTuiPreference() reads os.homedir()/.claude/settings.json, so
// we spy on os.homedir() to redirect reads to a controlled temp directory that
// we populate per-case. This makes all four cases hermetic regardless of what
// any developer's real ~/.claude/settings.json contains.
// ---------------------------------------------------------------------------

describe('Merged Settings -- TUI Fullscreen Default', () => {
  let tmpDir: string;
  let tempHome: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kangentic-tui-'));
    tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'kangentic-home-'));
    // Project .claude/settings.json starts empty so there is no tui key.
    fs.mkdirSync(path.join(tmpDir, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, '.claude', 'settings.json'), JSON.stringify({}));
  });

  afterEach(() => {
    vi.restoreAllMocks();
    fs.rmSync(tmpDir, { recursive: true, force: true });
    fs.rmSync(tempHome, { recursive: true, force: true });
  });

  /**
   * Spy on os.homedir() to return tempHome, then build and return the written
   * merged settings. Callers set up project settings and/or tempHome/.claude/
   * before invoking this helper.
   */
  function buildAndReadMerged(): Record<string, unknown> {
    vi.spyOn(os, 'homedir').mockReturnValue(tempHome);
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'tui-test', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });
    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'tui-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'tui-test',
      statusOutputPath: statusOutput,
    });
    const mergedPath = path.join(tmpDir, '.kangentic', 'sessions', 'tui-test', 'settings.json');
    return JSON.parse(fs.readFileSync(mergedPath, 'utf-8'));
  }

  it('A: injects tui=fullscreen when no global preference and project settings has no tui key', () => {
    // tempHome has no .claude/ directory -> userHasGlobalTuiPreference() returns false.
    // project settings.json is {} -> no tui key.
    // Expected: Kangentic injects fullscreen default.
    // RED: removing `merged.tui = 'fullscreen'` makes merged.tui undefined, failing this.
    const merged = buildAndReadMerged();
    expect(merged.tui).toBe('fullscreen');
  });

  it('B: preserves project-level tui when project settings.json already specifies tui=auto', () => {
    // A project with { tui: 'auto' } in .claude/settings.json wins: merged.tui starts
    // as 'auto' from baseSettings, the guard sees merged.tui !== undefined, and skips
    // the fullscreen injection.
    // RED: removing the `merged.tui === undefined` guard would overwrite 'auto' to 'fullscreen'.
    fs.writeFileSync(
      path.join(tmpDir, '.claude', 'settings.json'),
      JSON.stringify({ tui: 'auto' }),
    );
    // tempHome has no .claude/ -> global preference absent.
    const merged = buildAndReadMerged();
    expect(merged.tui).toBe('auto');
  });

  it('C: suppresses the fullscreen default when global ~/.claude/settings.json sets tui=auto', () => {
    // userHasGlobalTuiPreference() reads tempHome/.claude/settings.json and finds
    // tui: 'auto', so it returns true. The injection condition is false and tui is
    // NOT set to 'fullscreen' (it stays undefined in the merged output).
    // RED: removing the `!this.userHasGlobalTuiPreference()` guard makes merged.tui
    //      'fullscreen' even though the user explicitly chose 'auto'.
    fs.mkdirSync(path.join(tempHome, '.claude'), { recursive: true });
    fs.writeFileSync(
      path.join(tempHome, '.claude', 'settings.json'),
      JSON.stringify({ tui: 'auto' }),
    );
    const merged = buildAndReadMerged();
    expect(merged.tui).not.toBe('fullscreen');
  });

  it('D: treats global tui=null as no preference and injects the fullscreen default', () => {
    // `tui: null` is the reset sentinel (e.g. a hand-edited file). The code gates
    // on `parsedGlobalSettings.tui !== null`, so null -> userHasGlobalTuiPreference()
    // returns false -> Kangentic still injects its fullscreen default.
    // RED: removing the null check makes null treated as a real preference, returning
    //      true from userHasGlobalTuiPreference(), and merged.tui stays undefined.
    fs.mkdirSync(path.join(tempHome, '.claude'), { recursive: true });
    fs.writeFileSync(
      path.join(tempHome, '.claude', 'settings.json'),
      JSON.stringify({ tui: null }),
    );
    const merged = buildAndReadMerged();
    expect(merged.tui).toBe('fullscreen');
  });
});

describe('Shell Detection', () => {
  it('at least one shell is available', () => {
    const shells = detectAvailableShells();
    expect(shells.length).toBeGreaterThan(0);
  });

  it('all detected shells have valid paths or commands', () => {
    const shells = detectAvailableShells();

    // fs.existsSync uses fs.statSync under the hood, which fails with EACCES
    // on Windows App Execution Alias reparse points (the zero-byte .exe
    // stubs under %LOCALAPPDATA%\Microsoft\WindowsApps that forward to the
    // Microsoft Store). fs.accessSync(..., F_OK) traverses the reparse point
    // and correctly reports the alias as existing, which matches what
    // `where` surfaces and what node-pty can spawn.
    function pathExists(candidate: string): boolean {
      try {
        fs.accessSync(candidate, fs.constants.F_OK);
        return true;
      } catch {
        return false;
      }
    }

    for (const shell of shells) {
      expect(shell.name).toBeTruthy();
      expect(shell.path).toBeTruthy();
      if (shell.name.startsWith('WSL:')) {
        expect(shell.path).toMatch(/^wsl /);
      } else if (process.platform === 'win32' && shell.path.includes('WindowsApps')) {
        // Windows app execution aliases (reparse points) are valid
        // executables resolved by `where`, but fs.existsSync returns
        // false because Node can't stat the reparse point. The `where`
        // check in detectAvailableShells already confirmed executability.
        expect(shell.path).toMatch(/\.exe$/i);
      } else {
        expect(pathExists(shell.path)).toBeTruthy();
      }
    }
  });
});

describe('Merged Settings -- MCP Server via --mcp-config', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mcp-inject-'));
    // Create .claude directory with empty settings
    fs.mkdirSync(path.join(tmpDir, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, '.claude', 'settings.json'), '{}');
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('writes kangentic MCP config to session directory and adds --mcp-config flag', () => {
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'mcp-test', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    const cmd = builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'mcp-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'mcp-test',
      statusOutputPath: statusOutput,
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });

    // Session mcp.json should exist with the in-process HTTP server URL
    const sessionMcpPath = path.join(tmpDir, '.kangentic', 'sessions', 'mcp-test', 'mcp.json');
    expect(fs.existsSync(sessionMcpPath)).toBe(true);
    const mcpConfig = JSON.parse(fs.readFileSync(sessionMcpPath, 'utf-8'));

    expect(mcpConfig.mcpServers.kangentic).toBeDefined();
    expect(mcpConfig.mcpServers.kangentic.type).toBe('http');
    expect(mcpConfig.mcpServers.kangentic.url).toBe('http://127.0.0.1:54321/mcp/test-project');
    expect(mcpConfig.mcpServers.kangentic.headers['X-Kangentic-Token']).toBe('deadbeef-test-token');

    // --mcp-config flag should be in the command
    expect(cmd).toContain('--mcp-config');
    expect(cmd).toContain('mcp.json');

    // .mcp.json in CWD should NOT be created or modified
    expect(fs.existsSync(path.join(tmpDir, '.mcp.json'))).toBe(false);
  });

  it('omits session mcp.json when mcpServerUrl/Token are missing', () => {
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'no-url', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'no-url-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'no-url',
      statusOutputPath: statusOutput,
      // mcpServerUrl/mcpServerToken intentionally omitted -- main process
      // hasn't published the HTTP server URL yet, so the session should
      // spawn without an MCP config and the agent should see no kangentic
      // tools rather than trying to hit a dead URL.
    });

    const sessionMcpPath = path.join(tmpDir, '.kangentic', 'sessions', 'no-url', 'mcp.json');
    expect(fs.existsSync(sessionMcpPath)).toBe(false);
  });

  it('omits --mcp-config flag and session mcp.json when mcpServerEnabled is false', () => {
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'no-mcp', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    const cmd = builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'no-mcp-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'no-mcp',
      statusOutputPath: statusOutput,
      mcpServerEnabled: false,
    });

    // No --mcp-config in the command
    expect(cmd).not.toContain('--mcp-config');

    // No session mcp.json
    const sessionMcpPath = path.join(tmpDir, '.kangentic', 'sessions', 'no-mcp', 'mcp.json');
    expect(fs.existsSync(sessionMcpPath)).toBe(false);
  });

  it('does not modify .mcp.json in CWD even when it exists', () => {
    // User has their own MCP server in .mcp.json (tracked in git)
    const originalContent = JSON.stringify({
      mcpServers: {
        'context7': {
          command: 'npx',
          args: ['-y', '@upstash/context7-mcp'],
        },
      },
    }, null, 2);
    fs.writeFileSync(path.join(tmpDir, '.mcp.json'), originalContent);

    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'preserve-mcp', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });

    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'preserve-mcp-task',
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId: 'preserve-mcp',
      statusOutputPath: statusOutput,
    });

    // .mcp.json should be completely untouched
    expect(fs.readFileSync(path.join(tmpDir, '.mcp.json'), 'utf-8')).toBe(originalContent);
  });

});

describe('Merged Settings - kangentic MCP allow-rule injection', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mcp-allow-'));
    fs.mkdirSync(path.join(tmpDir, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, '.claude', 'settings.json'), '{}');
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  /** Build a session and return its written merged settings.json object. */
  function buildAndReadSettings(
    sessionId: string,
    options: Record<string, unknown>,
  ): { allow?: string[]; deny?: string[] } | undefined {
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', sessionId, 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });
    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: `${sessionId}-task`,
      cwd: tmpDir,
      permissionMode: 'default',
      sessionId,
      statusOutputPath: statusOutput,
      ...options,
    });
    const settingsPath = path.join(tmpDir, '.kangentic', 'sessions', sessionId, 'settings.json');
    const merged = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    return merged.permissions;
  }

  it('injects mcp__kangentic into permissions.allow when the MCP server is attached', () => {
    const permissions = buildAndReadSettings('inject-basic', {
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });
    expect(permissions?.allow).toContain('mcp__kangentic');
  });

  it('does not duplicate the rule when project settings already carry it', () => {
    fs.writeFileSync(
      path.join(tmpDir, '.claude', 'settings.json'),
      JSON.stringify({ permissions: { allow: ['mcp__kangentic', 'Read'] } }),
    );
    const permissions = buildAndReadSettings('inject-dedup', {
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });
    const occurrences = (permissions?.allow ?? []).filter((rule) => rule === 'mcp__kangentic');
    expect(occurrences).toHaveLength(1);
    // The pre-existing user entry is preserved alongside the (deduped) rule.
    expect(permissions?.allow).toContain('Read');
    expect(permissions?.allow).toHaveLength(2);
  });

  it('does not inject when the MCP server is disabled, even with url and token set', () => {
    const permissions = buildAndReadSettings('inject-disabled', {
      mcpServerEnabled: false,
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });
    // Base settings had no permissions, and the gate did not fire, so no key.
    expect(permissions).toBeUndefined();
    // The gate is shared with the mcp.json write, so that is absent too.
    const sessionMcpPath = path.join(tmpDir, '.kangentic', 'sessions', 'inject-disabled', 'mcp.json');
    expect(fs.existsSync(sessionMcpPath)).toBe(false);
  });

  it('does not inject when mcpServerUrl/Token are missing', () => {
    const permissions = buildAndReadSettings('inject-nourl', {});
    expect(permissions?.allow ?? []).not.toContain('mcp__kangentic');
  });

  it('preserves user allow entries (project + local) and deny alongside the injection', () => {
    fs.writeFileSync(
      path.join(tmpDir, '.claude', 'settings.json'),
      JSON.stringify({ permissions: { allow: ['Read'], deny: ['WebFetch'] } }),
    );
    fs.writeFileSync(
      path.join(tmpDir, '.claude', 'settings.local.json'),
      JSON.stringify({ permissions: { allow: ['Bash(test:*)'] } }),
    );
    const permissions = buildAndReadSettings('inject-preserve', {
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });
    expect(permissions?.allow).toEqual(
      expect.arrayContaining(['Read', 'Bash(test:*)', 'mcp__kangentic']),
    );
    expect(permissions?.allow).toHaveLength(3);
    expect(permissions?.deny).toEqual(['WebFetch']);
  });

  it('stays idempotent across a resume (exactly one rule)', () => {
    const first = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'inject-resume', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });
    const spawnOptions = {
      cliPath: '/usr/bin/claude',
      taskId: 'inject-resume-task',
      cwd: tmpDir,
      permissionMode: 'default' as const,
      sessionId: 'inject-resume',
      statusOutputPath: statusOutput,
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    };
    first.buildClaudeCommand(spawnOptions);
    // Resume against the same session dir: settings are regenerated from base.
    new CommandBuilder().buildClaudeCommand({ ...spawnOptions, resume: true });

    const settingsPath = path.join(tmpDir, '.kangentic', 'sessions', 'inject-resume', 'settings.json');
    const merged = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    const occurrences = (merged.permissions?.allow ?? []).filter((rule: string) => rule === 'mcp__kangentic');
    expect(occurrences).toHaveLength(1);
  });

  it('also injects an autoMode.allow classifier rule for kangentic tools, since --permission-mode auto does not honor permissions.allow', () => {
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'inject-automode', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });
    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'inject-automode-task',
      cwd: tmpDir,
      permissionMode: 'auto',
      sessionId: 'inject-automode',
      statusOutputPath: statusOutput,
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });
    const settingsPath = path.join(tmpDir, '.kangentic', 'sessions', 'inject-automode', 'settings.json');
    const merged = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    expect(merged.autoMode?.allow).toEqual(
      expect.arrayContaining(['$defaults', "Kangentic's own board and session tools (mcp__kangentic__*) are always allowed: they only read or mutate this local Kanban board's own state (tasks, columns, sessions) inside a project the user has already opened in Kangentic, never external systems or files outside the project."]),
    );
  });

  it('does not duplicate the autoMode.allow rule, and preserves a project-authored autoMode config without adding $defaults', () => {
    fs.writeFileSync(
      path.join(tmpDir, '.claude', 'settings.json'),
      JSON.stringify({ autoMode: { allow: ['Deploying to staging is allowed'] } }),
    );
    const builder = new CommandBuilder();
    const statusOutput = path.join(tmpDir, '.kangentic', 'sessions', 'inject-automode-dedup', 'status.json');
    fs.mkdirSync(path.dirname(statusOutput), { recursive: true });
    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'inject-automode-dedup-task',
      cwd: tmpDir,
      permissionMode: 'auto',
      sessionId: 'inject-automode-dedup',
      statusOutputPath: statusOutput,
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });
    builder.buildClaudeCommand({
      cliPath: '/usr/bin/claude',
      taskId: 'inject-automode-dedup-task',
      cwd: tmpDir,
      permissionMode: 'auto',
      sessionId: 'inject-automode-dedup',
      resume: true,
      statusOutputPath: statusOutput,
      mcpServerUrl: 'http://127.0.0.1:54321/mcp/test-project',
      mcpServerToken: 'deadbeef-test-token',
    });
    const settingsPath = path.join(tmpDir, '.kangentic', 'sessions', 'inject-automode-dedup', 'settings.json');
    const merged = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    // The project's own list is preserved as-is (no injected '$defaults'),
    // the kangentic rule is appended exactly once even across a resume.
    expect(merged.autoMode?.allow).toEqual([
      'Deploying to staging is allowed',
      "Kangentic's own board and session tools (mcp__kangentic__*) are always allowed: they only read or mutate this local Kanban board's own state (tasks, columns, sessions) inside a project the user has already opened in Kangentic, never external systems or files outside the project.",
    ]);
  });
});

// ---------------------------------------------------------------------------
// UNC Path Support (Windows network shares like \\server\share)
// Pure string transforms - run on all platforms, no platform guard needed.
// ---------------------------------------------------------------------------

describe('UNC Path Support', () => {
  describe('isUncPath', () => {
    it('detects backslash UNC paths', () => {
      expect(isUncPath('\\\\server\\share')).toBe(true);
      expect(isUncPath('\\\\192.168.0.1\\project')).toBe(true);
    });

    it('detects forward-slash UNC paths', () => {
      expect(isUncPath('//server/share')).toBe(true);
    });

    it('rejects drive-letter paths', () => {
      expect(isUncPath('C:\\Users')).toBe(false);
      expect(isUncPath('D:\\project')).toBe(false);
    });

    it('rejects Unix absolute paths', () => {
      expect(isUncPath('/usr/local/bin')).toBe(false);
      expect(isUncPath('/home/user/project')).toBe(false);
    });

    it('rejects relative paths', () => {
      expect(isUncPath('relative/path')).toBe(false);
      expect(isUncPath('./local')).toBe(false);
    });

    it('rejects paths with only slashes', () => {
      expect(isUncPath('//')).toBe(false);
      expect(isUncPath('\\\\')).toBe(false);
    });
  });

  describe('toGitBashPath with UNC', () => {
    it('converts UNC backslashes to forward slashes', () => {
      expect(toGitBashPath('\\\\192.168.0.1\\project\\sub'))
        .toBe('//192.168.0.1/project/sub');
    });

    it('converts UNC server name only', () => {
      expect(toGitBashPath('\\\\server\\share'))
        .toBe('//server/share');
    });

    it('preserves existing drive-letter behavior', () => {
      expect(toGitBashPath('C:\\Users\\dev')).toBe('/c/Users/dev');
    });
  });

  describe('toWslPath with UNC', () => {
    it('converts UNC backslashes to forward slashes (best-effort)', () => {
      expect(toWslPath('\\\\server\\share\\path'))
        .toBe('//server/share/path');
    });

    it('preserves existing drive-letter behavior', () => {
      expect(toWslPath('C:\\Users\\dev')).toBe('/mnt/c/Users/dev');
    });
  });

  describe('convertWindowsExePath with UNC', () => {
    it('normalizes unquoted UNC exe path', () => {
      expect(convertWindowsExePath('\\\\server\\share\\bin\\exe --flag', false))
        .toBe('//server/share/bin/exe --flag');
    });

    it('normalizes quoted UNC exe path, staying quoted', () => {
      expect(convertWindowsExePath('"\\\\server\\share\\bin\\exe" --flag', false))
        .toBe('"//server/share/bin/exe" --flag');
    });

    it('scopes replacement to exe path only, preserving backslash args', () => {
      expect(convertWindowsExePath('\\\\server\\share\\exe --dir C:\\other\\path', false))
        .toBe('//server/share/exe --dir C:\\other\\path');
    });

    it('scopes quoted replacement to exe path only', () => {
      expect(convertWindowsExePath('"\\\\server\\share\\my exe" --dir C:\\other', false))
        .toBe('"//server/share/my exe" --dir C:\\other');
    });

    it('preserves existing drive-letter behavior', () => {
      expect(convertWindowsExePath('C:\\Users\\dev\\bin\\claude.exe --print', false))
        .toBe('/c/Users/dev/bin/claude.exe --print');
    });

    it('preserves existing Unix path behavior (no-op)', () => {
      const cmd = '/usr/local/bin/claude --print "hello"';
      expect(convertWindowsExePath(cmd, false)).toBe(cmd);
    });
  });
});
