/**
 * Unit tests for `drainAutoNameAskedIds` in
 * src/main/ipc/handlers/task-crud.ts.
 *
 * The function is @internal-exported so it can be tested without going through
 * the full IPC handler. All dependencies (electron, DB modules, etc.) are
 * mocked to keep this test self-contained and fast.
 *
 * Covers:
 *   - removes matching IDs and saves the filtered array
 *   - no-op when autoNameAskedTaskIds field is absent from the config
 *   - no-op when no IDs in the input match the stored list
 *   - no-op when the input list is empty
 *
 * configManager.save() itself is guaranteed never to throw (see
 * src/main/config/write-failure-notice.ts): a write failure degrades to a
 * source-keyed report and a one-time toast instead. So there is no
 * "swallows a save() throw" case to cover here - the real contract makes it
 * unreachable, and mocking a throwing save() would test behavior no real
 * ConfigManager can produce.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ---------------------------------------------------------------------------
// Hoist mocks before any imports of the module under test
// ---------------------------------------------------------------------------

const capturedHandlers = new Map<string, (...args: unknown[]) => unknown>();

vi.mock('electron', () => ({
  ipcMain: {
    handle: vi.fn((channel: string, handler: (...args: unknown[]) => unknown) => {
      capturedHandlers.set(channel, handler);
    }),
  },
}));

// Stub out all heavy dependencies so task-crud.ts can be imported without
// needing a real DB, PTY, git, etc.
vi.mock('p-queue', () => ({
  default: class {
    size = 0;
    pending = 0;
    async add(fn: () => Promise<unknown>): Promise<unknown> { return fn(); }
    async addAll(tasks: Array<() => Promise<unknown>>): Promise<void> {
      for (const task of tasks) await task();
    }
  },
}));

vi.mock('node:fs', () => ({
  default: { existsSync: vi.fn(() => false) },
}));

vi.mock('../../src/main/db/database', () => ({ getProjectDb: vi.fn() }));
vi.mock('../../src/main/git/worktree-manager', () => ({ WorktreeManager: class {} }));
vi.mock('../../src/main/git/git-checks', () => ({
  isAutoGeneratedBranch: vi.fn(() => false),
  isGitRepo: vi.fn(() => false),
}));
vi.mock('../../src/main/ipc/helpers', () => ({
  getProjectRepos: vi.fn(() => ({
    tasks: { list: vi.fn(() => []), getById: vi.fn(), create: vi.fn(), delete: vi.fn() },
    swimlanes: { list: vi.fn(() => []) },
    actions: { list: vi.fn(() => []) },
    attachments: {
      add: vi.fn(),
      deleteByTaskId: vi.fn(),
      listByTaskId: vi.fn(() => []),
    },
  })),
  ensureTaskWorktree: vi.fn(async () => ({ worktreePath: '/tmp', checkoutError: undefined })),
  ensureTaskBranchCheckout: vi.fn(),
  notifySpawnBlocked: vi.fn(),
  createTransitionEngine: vi.fn(() => ({ run: vi.fn(async () => ({})) })),
  cleanupTaskResources: vi.fn(async () => {}),
}));
vi.mock('../../src/main/ipc/handlers/task-move', () => ({
}));
vi.mock('../../src/main/agent/shared', () => ({
  interpolateTemplate: vi.fn((tpl: string) => tpl),
}));
vi.mock('../../src/main/ipc/task-lifecycle-lock', () => ({
  withTaskLock: vi.fn(async (_id: string, fn: () => Promise<unknown>) => fn()),
}));

// ---------------------------------------------------------------------------
// Import the function under test
// ---------------------------------------------------------------------------

import { drainAutoNameAskedIds } from '../../src/main/ipc/handlers/task-crud';
import type { IpcContext } from '../../src/main/ipc/ipc-context';

// ---------------------------------------------------------------------------
// Helper: build a minimal IpcContext with a configurable configManager
// ---------------------------------------------------------------------------

function makeConfigManager(opts: {
  loadResult?: { autoNameAskedTaskIds?: string[] } | (() => { autoNameAskedTaskIds?: string[] });
}) {
  const loadFn = typeof opts.loadResult === 'function'
    ? opts.loadResult
    : vi.fn(() => opts.loadResult ?? {});

  const saveFn = vi.fn(() => true);

  return {
    load: typeof opts.loadResult === 'function' ? opts.loadResult : loadFn,
    save: saveFn,
    getEffectiveConfig: vi.fn(() => ({})),
    saveProjectOverrides: vi.fn(),
    loadProjectOverrides: vi.fn(() => null),
  };
}

function makeContext(configManager: ReturnType<typeof makeConfigManager>): IpcContext {
  return {
    configManager,
    boardConfigManager: { getDefaultBaseBranch: vi.fn(() => null) },
    sessionManager: { setMaxConcurrent: vi.fn(), setShell: vi.fn(), setIdleTimeout: vi.fn() },
    projectRepo: { list: vi.fn(() => []) },
    shellResolver: { getAvailableShells: vi.fn(() => []), getDefaultShell: vi.fn(() => 'bash') },
    gitDetector: { detect: vi.fn(() => ({ found: false })) },
    mainWindow: {
      isDestroyed: vi.fn(() => false),
      webContents: { send: vi.fn() },
      minimize: vi.fn(), maximize: vi.fn(), unmaximize: vi.fn(),
      isMaximized: vi.fn(() => false), close: vi.fn(), isFocused: vi.fn(() => true),
      flashFrame: vi.fn(), isMinimized: vi.fn(() => false), restore: vi.fn(),
      show: vi.fn(), focus: vi.fn(), once: vi.fn(),
    },
    currentProjectPath: null,
    currentProjectId: null,
  } as unknown as IpcContext;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('drainAutoNameAskedIds', () => {
  beforeEach(() => {
    capturedHandlers.clear();
  });

  it('removes matching IDs from autoNameAskedTaskIds and calls save with the filtered array', () => {
    const configManager = makeConfigManager({
      loadResult: { autoNameAskedTaskIds: ['task-1', 'task-2', 'task-3'] },
    });
    const context = makeContext(configManager);

    drainAutoNameAskedIds(context, ['task-1', 'task-3']);

    expect(configManager.save).toHaveBeenCalledTimes(1);
    const savedConfig = (configManager.save as ReturnType<typeof vi.fn>).mock.calls[0][0];
    expect(savedConfig.autoNameAskedTaskIds).toEqual(['task-2']);
  });

  it('is a no-op when autoNameAskedTaskIds field is absent from the config', () => {
    const configManager = makeConfigManager({ loadResult: {} });
    const context = makeContext(configManager);

    drainAutoNameAskedIds(context, ['task-1']);

    // save should NOT have been called - nothing to drain
    expect(configManager.save).not.toHaveBeenCalled();
  });

  it('is a no-op when autoNameAskedTaskIds is an empty array', () => {
    const configManager = makeConfigManager({
      loadResult: { autoNameAskedTaskIds: [] },
    });
    const context = makeContext(configManager);

    drainAutoNameAskedIds(context, ['task-1']);

    expect(configManager.save).not.toHaveBeenCalled();
  });

  it('is a no-op when no IDs in the input list match the stored entries', () => {
    const configManager = makeConfigManager({
      loadResult: { autoNameAskedTaskIds: ['task-a', 'task-b'] },
    });
    const context = makeContext(configManager);

    drainAutoNameAskedIds(context, ['task-x', 'task-y']);

    // next.length === current.length, so no save
    expect(configManager.save).not.toHaveBeenCalled();
  });

  it('is a no-op when the input list is empty', () => {
    const configManager = makeConfigManager({
      loadResult: { autoNameAskedTaskIds: ['task-1', 'task-2'] },
    });
    const context = makeContext(configManager);

    drainAutoNameAskedIds(context, []);

    // Early return before any load/save
    expect(configManager.save).not.toHaveBeenCalled();
  });

  it('swallows errors thrown by configManager.load() without propagating', () => {
    const configManager = makeConfigManager({
      loadResult: () => { throw new Error('config corrupted'); },
    });
    const context = makeContext(configManager);

    expect(() => drainAutoNameAskedIds(context, ['task-1'])).not.toThrow();
    expect(configManager.save).not.toHaveBeenCalled();
  });

  it('removes all matching IDs when the entire list is in the input', () => {
    const configManager = makeConfigManager({
      loadResult: { autoNameAskedTaskIds: ['task-1', 'task-2'] },
    });
    const context = makeContext(configManager);

    drainAutoNameAskedIds(context, ['task-1', 'task-2']);

    expect(configManager.save).toHaveBeenCalledTimes(1);
    const savedConfig = (configManager.save as ReturnType<typeof vi.fn>).mock.calls[0][0];
    expect(savedConfig.autoNameAskedTaskIds).toEqual([]);
  });
});
