/**
 * `handleTaskMove`'s stale-resource cleanup must never force-delete a CUSTOM
 * branch.
 *
 * When worktree creation fails, task-move.ts runs a best-effort cleanup that
 * clears leftovers from a previous partial cleanup, ending in
 * `worktreeManager.removeBranch(expectedBranch)` - which is `git branch -D` with
 * every error swallowed. That is correct for the auto-generated branch it was
 * written for, and data loss for an agent-supplied one: ANY worktree failure,
 * while the branch is not checked out anywhere, silently destroys the branch and
 * its commits.
 *
 * Task #538 is the concrete case. Its branch carried commit 4261ff1e and had
 * never been pushed, so origin would not have saved it either. The only reason
 * this had not already bitten is that git refuses to delete a CHECKED-OUT
 * branch - the very condition that caused the failure - and the main checkout
 * has since moved off it.
 *
 * Both directions are pinned, because an over-correcting fix would strand stale
 * branches instead of deleting work.
 *
 * Red-green: the custom-branch test reds against the pre-fix handler, which
 * called removeBranch unconditionally.
 *
 * Mocks mirror abort-task-move.test.ts, with one change: WorktreeManager's
 * methods are HOISTED `vi.fn()`s rather than per-instance fields, because
 * task-move constructs `new WorktreeManager(...)` inside the catch block, so
 * per-instance spies are unreachable from the test.
 *
 * `isAutoGeneratedBranch` and `legacyAutoBranchNameFor` are deliberately left
 * UNMOCKED - the predicate is the thing under test, so stubbing it would make
 * this vacuous.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import fs from 'node:fs';
import type { Task, Swimlane } from '../../src/shared/types';

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------

const {
  mockWithLock,
  mockRemoveWorktree,
  mockPruneWorktrees,
  mockRemoveBranch,
} = vi.hoisted(() => ({
  mockWithLock: vi.fn(async (fn: () => Promise<unknown>) => fn()),
  mockRemoveWorktree: vi.fn(async () => true),
  mockPruneWorktrees: vi.fn(async () => {}),
  mockRemoveBranch: vi.fn(async () => {}),
}));

vi.mock('electron', () => ({
  ipcMain: { handle: vi.fn() },
}));

vi.mock('simple-git', () => ({
  simpleGit: vi.fn(() => ({
    diffSummary: vi.fn(async () => ({ insertions: 0, deletions: 0, changed: 0 })),
  })),
  default: vi.fn(() => ({})),
}));

vi.mock('../../src/main/db/database', () => ({ getProjectDb: vi.fn(() => ({})) }));
vi.mock('../../src/main/db/repositories/task-repository', () => ({
  TaskRepository: class {},
}));
vi.mock('../../src/main/db/repositories/session-repository', () => ({
  SessionRepository: class {
    getLatestForTask = vi.fn(() => null);
    updateGitStats = vi.fn();
  },
}));
vi.mock('../../src/main/db/repositories/swimlane-repository', () => ({
  SwimlaneRepository: class {},
}));
vi.mock('../../src/main/db/repositories/action-repository', () => ({
  ActionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/attachment-repository', () => ({
  AttachmentRepository: class {},
}));

vi.mock('../../src/main/git/worktree-manager', () => ({
  GitQueuePriority: { USER: 0, BACKGROUND: 10 },
  WorktreeManager: class {
    withLock = mockWithLock;
    removeWorktree = mockRemoveWorktree;
    pruneWorktrees = mockPruneWorktrees;
    removeBranch = mockRemoveBranch;
    static scheduleBackgroundPrune = vi.fn();
  },
}));

vi.mock('../../src/main/analytics/analytics', () => ({ trackEvent: vi.fn() }));

vi.mock('../../src/main/transition-engine/session-lifecycle', () => ({
  markRecordExited: vi.fn(),
  markRecordSuspended: vi.fn(),
}));

vi.mock('../../src/main/transition-engine/spawn-progress', () => ({
  emitSpawnProgress: vi.fn(),
  emitSpawnWaiting: vi.fn(),
  clearSpawnProgress: vi.fn(),
  createProgressCallback: vi.fn(() => vi.fn()),
  getInFlightSpawnProgress: vi.fn(() => ({})),
}));

vi.mock('../../src/main/transition-engine/agent-resolver', () => ({
  resolveTargetAgent: vi.fn(() => ({ agent: 'claude', isHandoff: false })),
}));

vi.mock('../../src/main/ipc/handlers/backlog', () => ({
  abortBacklogPromotion: vi.fn(),
}));

vi.mock('../../src/main/ipc/handlers/session-metrics', () => ({
  captureSessionMetrics: vi.fn(),
  refineTranscriptTokens: vi.fn(),
  refineTranscriptToolCounts: vi.fn(),
}));

vi.mock('../../src/main/agent/shared', () => ({
  interpolateTemplate: vi.fn((template: string) => template),
  resolveBridgeScript: vi.fn(() => '/mock/bridge.js'),
  execVersion: vi.fn(async () => '1.0.0'),
}));

vi.mock('../../src/main/shutdown-state', () => ({
  isShuttingDown: vi.fn(() => false),
  setShuttingDown: vi.fn(),
}));

const mockEnsureTaskWorktree = vi.fn(async () => null);
const mockEnsureTaskBranchCheckout = vi.fn(async () => {});
const mockSpawnAgent = vi.fn(async () => {});

vi.mock('../../src/main/ipc/helpers/index', () => ({
  getProjectRepos: (...args: unknown[]) => mockGetProjectRepos(...args),
  ensureTaskWorktree: (...args: unknown[]) => mockEnsureTaskWorktree(...args),
  ensureTaskBranchCheckout: (...args: unknown[]) => mockEnsureTaskBranchCheckout(...args),
  spawnAgent: (...args: unknown[]) => mockSpawnAgent(...args),
  createTransitionEngine: vi.fn(() => ({})),
  cleanupTaskResources: vi.fn(async () => {}),
  deleteTaskWorktree: vi.fn(async () => true),
  autoSpawnForTask: vi.fn(async () => {}),
}));
vi.mock('../../src/main/pr/pr-linking', () => ({
  autoLinkPRForTask: vi.fn(),
}));

const mockGetProjectRepos = vi.fn();

// ---------------------------------------------------------------------------
// Import under test
// ---------------------------------------------------------------------------

import { handleTaskMove } from '../../src/main/ipc/handlers/task-move';
import { legacyAutoBranchNameFor } from '../../src/main/git/task-worktree-folder';
import { isAutoGeneratedBranch } from '../../src/main/git/git-checks';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const TASK_ID = 'task-branchguard-0001';
const SOURCE_LANE_ID = 'lane-todo';
const TARGET_LANE_ID = 'lane-doing';
const TASK_TITLE = 'Rework notifications';
/** The exact branch #538 carried, and the shape of any agent-supplied name. */
const CUSTOM_BRANCH = 'rework-notifications-desktop-push';

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: TASK_ID,
    display_id: 1,
    title: TASK_TITLE,
    description: '',
    swimlane_id: SOURCE_LANE_ID,
    position: 0,
    agent: null,
    session_id: null,
    worktree_path: null,
    branch_name: null,
    pr_number: null,
    pr_url: null,
    base_branch: null,
    use_worktree: null,
    labels: [],
    priority: 0,
    attachment_count: 0,
    archived_at: null,
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-01T00:00:00.000Z',
    ...overrides,
  };
}

function makeSwimlane(id: string, overrides: Partial<Swimlane> = {}): Swimlane {
  return {
    id,
    name: `Lane ${id}`,
    role: null,
    position: 0,
    color: '#888',
    icon: null,
    is_archived: false,
    is_ghost: false,
    permission_mode: null,
    auto_spawn: true,
    auto_command: null,
    plan_exit_target_id: null,
    agent_override: null,
    model_override: null,
    effort_override: null,
    handoff_context: false,
    created_at: '2025-01-01T00:00:00.000Z',
    ...overrides,
  };
}

function makeContext() {
  return {
    currentProjectId: 'proj-branchguard',
    currentProjectPath: '/mock/branchguard-project',
    boardEvents: { emitBoardChanged: vi.fn() },
    mainWindow: {
      isDestroyed: vi.fn(() => false),
      webContents: { send: vi.fn() },
    },
    sessionManager: {
      removeByTaskId: vi.fn(),
      killByTaskId: vi.fn(),
      listSessions: vi.fn(() => []),
      suspend: vi.fn(async () => {}),
      // Phase 1 reconciles task.session_id against the registry before the
      // Priority ladder; a live row for the pointed-at id keeps these
      // fixtures on the branches they exercise.
      getSession: vi.fn((id: string) => ({ id, status: 'running' })),
      findLiveSessionByTaskId: vi.fn(() => null),
    },
    configManager: {
      getEffectiveConfig: vi.fn(() => ({ git: { defaultBaseBranch: 'main' } })),
    },
    boardConfigManager: { getDefaultBaseBranch: vi.fn(() => null) },
    terminalSubmitScheduler: { cancel: vi.fn(), scheduleKeystrokes: vi.fn() },
    projectRepo: { getById: vi.fn(() => ({ id: 'proj-branchguard', default_agent: 'claude' })) },
  };
}

/**
 * Drive a move whose worktree creation fails, so the stale-resource cleanup
 * runs. The move rejects by design (`Worktree setup failed: ...`), which is what
 * the renderer turns into its toast.
 */
async function runFailingMove(task: Task): Promise<void> {
  const sourceLane = makeSwimlane(SOURCE_LANE_ID, { role: 'todo' });
  const targetLane = makeSwimlane(TARGET_LANE_ID, { role: null, auto_spawn: true });

  mockGetProjectRepos.mockReturnValue({
    tasks: {
      getById: vi.fn(() => ({ ...task })),
      move: vi.fn(),
      update: vi.fn(),
      list: vi.fn(() => [{ ...task }]),
      archive: vi.fn(),
    },
    swimlanes: {
      getById: vi.fn((id: string) => {
        if (id === SOURCE_LANE_ID) return sourceLane;
        if (id === TARGET_LANE_ID) return targetLane;
        return null;
      }),
      list: vi.fn(() => [sourceLane, targetLane]),
    },
    actions: { getTransitionsFor: vi.fn(() => []) },
    attachments: { deleteByTaskId: vi.fn() },
  });

  mockEnsureTaskWorktree.mockRejectedValue(new Error("fatal: 'branch' is already used by worktree at '/repo'"));

  await expect(
    handleTaskMove(makeContext() as never, {
      taskId: task.id,
      targetSwimlaneId: TARGET_LANE_ID,
      targetPosition: 0,
    }, 'renderer'),
  ).rejects.toThrow(/Worktree setup failed/);
}

beforeEach(() => {
  vi.clearAllMocks();
  mockWithLock.mockImplementation(async (fn: () => Promise<unknown>) => fn());
  mockRemoveWorktree.mockResolvedValue(true);
  mockPruneWorktrees.mockResolvedValue(undefined);
  mockRemoveBranch.mockResolvedValue(undefined);
  mockEnsureTaskBranchCheckout.mockResolvedValue(undefined);
  mockSpawnAgent.mockResolvedValue(undefined);
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('handleTaskMove stale-resource cleanup: branch deletion', () => {
  it('does NOT delete a custom, agent-supplied branch when worktree creation fails', async () => {
    // Sanity-check the fixture against the real predicate, so this test cannot
    // silently pass because the branch name happened to look auto-generated.
    expect(isAutoGeneratedBranch(CUSTOM_BRANCH, TASK_ID, TASK_TITLE)).toBe(false);

    await runFailingMove(makeTask({ branch_name: CUSTOM_BRANCH }));

    // The data-loss guard. Pre-fix this was `git branch -D
    // rework-notifications-desktop-push` with the error swallowed, destroying
    // commit 4261ff1e on an unpushed branch.
    expect(mockRemoveBranch).not.toHaveBeenCalled();
    // The rest of the cleanup must still have run - the guard is scoped to the
    // branch deletion, not the whole block.
    expect(mockPruneWorktrees).toHaveBeenCalledTimes(1);
  });

  it('still deletes an auto-generated branch, so stale leftovers are cleaned', async () => {
    const task = makeTask();
    const autoBranch = legacyAutoBranchNameFor(task);
    expect(isAutoGeneratedBranch(autoBranch, TASK_ID, TASK_TITLE)).toBe(true);

    await runFailingMove(makeTask({ branch_name: autoBranch }));

    // The other direction: an over-correcting fix would strand stale branches.
    expect(mockRemoveBranch).toHaveBeenCalledWith(autoBranch);
  });

  it('still deletes the derived legacy name when the task has no branch_name at all', async () => {
    const task = makeTask({ branch_name: null });

    await runFailingMove(task);

    // The null case falls back to `legacyAutoBranchNameFor`, which is
    // auto-generated by construction, so it stays deletable.
    expect(mockRemoveBranch).toHaveBeenCalledWith(legacyAutoBranchNameFor(task));
  });

  it('cleans the stale worktree with the moderate profile, not the default thorough', async () => {
    // Creation just failed on this same path, so a second full-budget grind
    // re-proves what we already know while the user waits on a failure toast
    // and the git queue stays held. Measured in a preview: two thorough passes
    // put the toast ~62s out against ~34s with this profile.
    //
    // The removal loop is gated on the candidate existing on disk, and this
    // suite otherwise runs against the real fs with fixture paths, so the gate
    // is opened for this case only.
    const existsSpy = vi.spyOn(fs, 'existsSync').mockReturnValue(true);
    try {
      await runFailingMove(makeTask());

      expect(mockRemoveWorktree).toHaveBeenCalled();
      for (const call of mockRemoveWorktree.mock.calls) {
        expect(call[1]).toEqual({ removalProfile: 'moderate' });
      }
    } finally {
      existsSpy.mockRestore();
    }
  });
});
